using BrutalAPI;
using BrutalAPI.Items;
using SaltEnemies_Reseasoned;
using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace SaltsEnemies_Reseasoned
{
    public static class UnlocksOne
    {
        public static void Add()
        {
            PerformEffect_Item sword = new PerformEffect_Item("Salt_PaperSword_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyRupturedEffect>(), 2, Slots.Front)]);
            sword.Name = "Paper Sword";
            sword.Flavour = "\"As sharp as it is feeble\"";
            sword.Description = "On dealing damage, inflict 2 Ruptured on the Opposing enemy.";
            sword.Icon = ResourceLoader.LoadSprite("item_papersword.png");
            sword.EquippedModifiers = [];
            sword.TriggerOn = TriggerCalls.OnDidApplyDamage;
            sword.DoesPopUpInfo = true;
            sword.Conditions = [];
            sword.DoesActionOnTriggerAttached = false;
            sword.ConsumeOnTrigger = TriggerCalls.Count;
            sword.ConsumeOnUse = false;
            sword.ConsumeConditions = [];
            sword.ShopPrice = 2;
            sword.IsShopItem = true;
            sword.StartsLocked = true;
            sword.OnUnlockUsesTHE = true;
            sword.UsesSpecialUnlockText = false;
            sword.SpecialUnlockID = UILocID.None;
            sword.item._ItemTypeIDs = ["Knife"];
            sword.item.AddBlueSkyUnlock("Boyle_CH", "locked_papersword.png", "ach_papersword.png");

            PerformEffect_Item inkwell = new PerformEffect_Item("Salt_Inkwell_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplySlipSlotEffect>(), 2, Slots.Front)]);
            inkwell.Name = "Ink Well";
            inkwell.Flavour = "\"Gets messy fast\"";
            inkwell.Description = "On using an ability, apply 2 Slip to the Opposing position.";
            inkwell.Icon = ResourceLoader.LoadSprite("item_inkwell.png");
            inkwell.EquippedModifiers = [];
            inkwell.TriggerOn = TriggerCalls.OnAbilityUsed;
            inkwell.DoesPopUpInfo = true;
            inkwell.Conditions = [];
            inkwell.DoesActionOnTriggerAttached = false;
            inkwell.ConsumeOnTrigger = TriggerCalls.Count;
            inkwell.ConsumeOnUse = false;
            inkwell.ConsumeConditions = [];
            inkwell.ShopPrice = 2;
            inkwell.IsShopItem = true;
            inkwell.StartsLocked = true;
            inkwell.OnUnlockUsesTHE = true;
            inkwell.UsesSpecialUnlockText = false;
            inkwell.SpecialUnlockID = UILocID.None;
            inkwell.item._ItemTypeIDs = [];
            inkwell.item.AddBlueSkyUnlock("Hans_CH", "locked_inkwell.png", "ach_inkwell.png");

            PerformEffect_Item war = new PerformEffect_Item("Salt_AbstractWar_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyDeterminedEffect>(), 1, Slots.Self)]);
            war.Name = "Abstract War";
            war.Flavour = "\"Depictions of Violence\"";
            war.Description = "On any party member receiving direct damage, gain 1 Determined.";
            war.Icon = ResourceLoader.LoadSprite("item_abstractwar.png");
            war.EquippedModifiers = [];
            war.TriggerOn = AllyTriggersHandler.AllyDirectDamaged;
            war.DoesPopUpInfo = true;
            war.Conditions = [];
            war.DoesActionOnTriggerAttached = false;
            war.ConsumeOnTrigger = TriggerCalls.Count;
            war.ConsumeOnUse = false;
            war.ConsumeConditions = [];
            war.ShopPrice = 6;
            war.IsShopItem = true;
            war.StartsLocked = true;
            war.OnUnlockUsesTHE = true;
            war.UsesSpecialUnlockText = false;
            war.SpecialUnlockID = UILocID.None;
            war.item._ItemTypeIDs = [];
            war.item.AddBlueSkyUnlock("Anton_CH", "locked_abstractwar.png", "ach_abstractwar.png");

            PerformEffect_Item flower = new PerformEffect_Item("Salt_LittleFlower_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyDeterminedEffect>(), 3, Slots.Self)]);
            flower.Name = "Little Flower";
            flower.Flavour = "\"So delicate yet full of hope...\"";
            flower.Description = "At the start of combat gain 3 Determined.\nThis item is destroyed on death.";
            flower.Icon = ResourceLoader.LoadSprite("item_littleflower.png");
            flower.EquippedModifiers = [];
            flower.TriggerOn = TriggerCalls.OnFirstTurnStart;
            flower.DoesPopUpInfo = true;
            flower.Conditions = [];
            flower.DoesActionOnTriggerAttached = false;
            flower.ConsumeOnTrigger = TriggerCalls.OnDeath;
            flower.ConsumeOnUse = false;
            flower.ConsumeConditions = [];
            flower.ShopPrice = 3;
            flower.IsShopItem = false;
            flower.StartsLocked = true;
            flower.OnUnlockUsesTHE = true;
            flower.UsesSpecialUnlockText = false;
            flower.SpecialUnlockID = UILocID.None;
            flower.item._ItemTypeIDs = ["Magic"];
            flower.item.AddBlueSkyUnlock("Splig_CH", "locked_littleflower.png", "ach_littleflower.png");

            PerformEffect_Item waste = new PerformEffect_Item("Salt_WasteDisposal_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<DamageEffect>(), 2, Slots.Front)]);
            waste.Name = "Waste Disposal";
            waste.Flavour = "\"Full of sharps and biohazards.\"";
            waste.Description = "On any ability being used, deal 2 damage to the Opposing enemy.";
            waste.Icon = ResourceLoader.LoadSprite("item_wastedisposal.png");
            waste.EquippedModifiers = [];
            waste.TriggerOn = TriggerCalls.OnAnyAbilityUsed;
            waste.DoesPopUpInfo = true;
            waste.Conditions = [];
            waste.DoesActionOnTriggerAttached = false;
            waste.ConsumeOnTrigger = TriggerCalls.Count;
            waste.ConsumeOnUse = false;
            waste.ConsumeConditions = [];
            waste.ShopPrice = 0;
            waste.IsShopItem = true;
            waste.StartsLocked = true;
            waste.OnUnlockUsesTHE = true;
            waste.UsesSpecialUnlockText = false;
            waste.SpecialUnlockID = UILocID.None;
            waste.item._ItemTypeIDs = [];
            waste.item.AddBlueSkyUnlock("Pearl_CH", "locked_wastedisposal.png", "ach_wastedisposal.png");

            PerformEffect_Item photo = new PerformEffect_Item("Salt_RedPhoto_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPowerEffect>(), 1, Slots.Self)]);
            photo.Name = "Red Photo";
            photo.Flavour = "\"Abstract Violence\"";
            photo.Description = "On any party member receiving direct damage, gain 1 Power.";
            photo.Icon = ResourceLoader.LoadSprite("item_redphoto.png");
            photo.EquippedModifiers = [];
            photo.TriggerOn = AllyTriggersHandler.AllyDirectDamaged;
            photo.DoesPopUpInfo = true;
            photo.Conditions = [];
            photo.DoesActionOnTriggerAttached = false;
            photo.ConsumeOnTrigger = TriggerCalls.Count;
            photo.ConsumeOnUse = false;
            photo.ConsumeConditions = [];
            photo.ShopPrice = 6;
            photo.IsShopItem = true;
            photo.StartsLocked = true;
            photo.OnUnlockUsesTHE = true;
            photo.UsesSpecialUnlockText = false;
            photo.SpecialUnlockID = UILocID.None;
            photo.item._ItemTypeIDs = [];
            photo.item.AddBlueSkyUnlock("Thype_CH", "locked_redphoto.png", "ach_redphoto.png");

            RandomAbilityPassive construct = ScriptableObject.CreateInstance<RandomAbilityPassive>();
            construct._passiveName = LoadedAssetsHandler.GetCharacter("Doll_CH").passiveAbilities[0]._passiveName;
            construct.passiveIcon = LoadedAssetsHandler.GetCharacter("Doll_CH").passiveAbilities[0].passiveIcon;
            construct.m_PassiveID = LoadedAssetsHandler.GetCharacter("Doll_CH").passiveAbilities[0].m_PassiveID;
            construct._enemyDescription = LoadedAssetsHandler.GetCharacter("Doll_CH").passiveAbilities[0]._enemyDescription;
            construct._characterDescription = LoadedAssetsHandler.GetCharacter("Doll_CH").passiveAbilities[0]._characterDescription;
            construct._triggerOn = new TriggerCalls[]
            {
                (TriggerCalls) 889532//old zensuke trigger
            };

            ExtraPassiveAbility_Wearable_SMS add_construct = ScriptableObject.CreateInstance<ExtraPassiveAbility_Wearable_SMS>();
            add_construct._extraPassiveAbility = construct;

            PerformEffect_Item halo = new PerformEffect_Item("Salt_SteelHalo_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<RerollTargetConstructEffect>(), 1, Slots.Self)]);
            halo.Name = "Steel Halo";
            halo.Flavour = "\"Artificial Angel\"";
            halo.Description = "This party member has \"Construct\" as a passive.\nOn taking any damage, reroll this party member's Construct ability.";
            halo.Icon = ResourceLoader.LoadSprite("item_steelhalo.png");
            halo.EquippedModifiers = [add_construct];
            halo.TriggerOn = TriggerCalls.OnDamaged;
            halo.DoesPopUpInfo = true;
            halo.Conditions = [];
            halo.DoesActionOnTriggerAttached = false;
            halo.ConsumeOnTrigger = TriggerCalls.Count;
            halo.ConsumeOnUse = false;
            halo.ConsumeConditions = [];
            halo.ShopPrice = 5;
            halo.IsShopItem = false;
            halo.StartsLocked = true;
            halo.OnUnlockUsesTHE = true;
            halo.UsesSpecialUnlockText = false;
            halo.SpecialUnlockID = UILocID.None;
            halo.item._ItemTypeIDs = ["Angel"];
            halo.item.AddBlueSkyUnlock("Burnout_CH", "locked_steelhalo.png", "ach_steelhalo.png");

            MultiPerformEffectItem nail = new MultiPerformEffectItem("Salt_LeftNail_TW", [Effects.GenerateEffect(Hauntling.Spawn, 1, Slots.Self)]);
            nail.Name = "Nail of the Left Eye";
            nail.Flavour = "\"It hates you so much\"";
            nail.Description = "Deal 30% more damage. \nOn taking direct damage, spawn something else.";
            nail.Icon = ResourceLoader.LoadSprite("item_leftnail.png");
            nail.EquippedModifiers = [];
            nail.TriggerOn = TriggerCalls.OnDirectDamaged;
            nail.DoesPopUpInfo = true;
            nail.Conditions = [];
            nail.DoesActionOnTriggerAttached = false;
            nail.ConsumeOnTrigger = TriggerCalls.Count;
            nail.ConsumeOnUse = false;
            nail.ConsumeConditions = [ItemExtensions.Chance(30)];
            nail.ShopPrice = 4;
            nail.IsShopItem = false;
            nail.StartsLocked = true;
            nail.OnUnlockUsesTHE = true;
            nail.UsesSpecialUnlockText = false;
            nail.SpecialUnlockID = UILocID.None;
            nail.item._ItemTypeIDs = ["Knife"];
            EffectTrigger nail_second = new EffectTrigger([], [TriggerCalls.OnWillApplyDamage], [ItemExtensions.Damage(30, true)], false);
            nail.AddEffectTrigger(nail_second);
            nail.item.AddBlueSkyUnlock("Fennec_CH", "locked_leftnail.png", "ach_leftnail.png");

            PerformEffect_Item propaganda = new PerformEffect_Item("Salt_BlatantPropaganda_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<DoubleMaxHealthTargetEffect>(), 1, Slots.Self)], true);
            propaganda.Name = "Blatant Propaganda";
            propaganda.Flavour = "\"Not even trying to hide it, huh...\"";
            propaganda.Description = "Increase healing dealt by 4.\nDouble maximum health on healing a target.";
            propaganda.Icon = ResourceLoader.LoadSprite("item_blatantpropaganda.png");
            propaganda.EquippedModifiers = [];
            propaganda.TriggerOn = TriggerCalls.OnWillApplyHeal;
            propaganda.DoesPopUpInfo = false;
            propaganda.Conditions = [ItemExtensions.Heal(4, true, false)];
            propaganda.DoesActionOnTriggerAttached = false;
            propaganda.ConsumeOnTrigger = TriggerCalls.Count;
            propaganda.ConsumeOnUse = false;
            propaganda.ConsumeConditions = [];
            propaganda.ShopPrice = 4;
            propaganda.IsShopItem = true;
            propaganda.StartsLocked = true;
            propaganda.OnUnlockUsesTHE = false;
            propaganda.UsesSpecialUnlockText = false;
            propaganda.SpecialUnlockID = UILocID.None;
            propaganda.item._ItemTypeIDs = [];
            propaganda.item.AddBlueSkyUnlock("Griffin_CH", "locked_blatantpropaganda.png", "ach_blatantpropaganda.png");

            ApplyEntropyEffect entropy_btw = ScriptableObject.CreateInstance<ApplyEntropyEffect>();
            entropy_btw._RandomBetweenPrevious = true;

            MultiPerformEffectItem crown = new MultiPerformEffectItem("Salt_HerCrown_TW", []);
            crown.Name = "Her Crown";
            crown.Flavour = "\"Worth less than nothing.\"";
            crown.Description = "Inflict Entropy equal to damage dealt to targets.\nOn dealing damage, gain 3-5 Entropy.";
            crown.Icon = ResourceLoader.LoadSprite("item_hercrown.png");
            crown.EquippedModifiers = [];
            crown.TriggerOn = AdvancedDamageTrigger.Dealt;
            crown.DoesPopUpInfo = false;
            crown.Conditions = [EntropyToTargetsCondition.Create()];
            crown.DoesActionOnTriggerAttached = false;
            crown.ConsumeOnTrigger = TriggerCalls.Count;
            crown.ConsumeOnUse = false;
            crown.ConsumeConditions = [];
            crown.ShopPrice = 4;
            crown.IsShopItem = false;
            crown.StartsLocked = true;
            crown.OnUnlockUsesTHE = false;
            crown.UsesSpecialUnlockText = false;
            crown.SpecialUnlockID = UILocID.None;
            crown.item._ItemTypeIDs = [];
            crown.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(BasicEffects.Empty, 3), Effects.GenerateEffect(entropy_btw, 5, Slots.Self)], [TriggerCalls.OnDidApplyDamage], [], false));
            crown.item.AddBlueSkyUnlock("Arnold_CH", "locked_hercrown.png", "ach_hercrown.png");

            RandomizeAllManaEffect randomize = ScriptableObject.CreateInstance<RandomizeAllManaEffect>();
            randomize.manaRandomOptions = [Pigments.Red, Pigments.Blue, Pigments.Yellow, Pigments.Purple];

            ExtraPassiveAbility_Wearable_SMS unstable = ScriptableObject.CreateInstance<ExtraPassiveAbility_Wearable_SMS>();
            unstable._extraPassiveAbility = Passives.Unstable;

            PerformEffect_Item rubber = new PerformEffect_Item("Salt_RubberKnife_SW", [Effects.GenerateEffect(randomize, 1, Slots.Self)]);
            rubber.Name = "Rubber Knife";
            rubber.Flavour = "\"Wibbly Wobbly\"";
            rubber.Description = "This party member has \"Unstable\" as a passive.\nOn using an ability, randomize all pigment.";
            rubber.Icon = ResourceLoader.LoadSprite("item_rubberknife.png");
            rubber.TriggerOn = TriggerCalls.OnAbilityUsed;
            rubber.EquippedModifiers = [unstable];
            rubber.DoesPopUpInfo = true;
            rubber.Conditions = [];
            rubber.DoesActionOnTriggerAttached = false;
            rubber.ConsumeOnTrigger = TriggerCalls.Count;
            rubber.ConsumeOnUse = false;
            rubber.ConsumeConditions = [];
            rubber.ShopPrice = 2;
            rubber.IsShopItem = true;
            rubber.StartsLocked = true;
            rubber.OnUnlockUsesTHE = true;
            rubber.UsesSpecialUnlockText = false;
            rubber.SpecialUnlockID = UILocID.None;
            rubber.item._ItemTypeIDs = ["Knife"];
            rubber.item.AddBlueSkyUnlock("Dimitri_CH", "locked_rubberknife.png", "ach_rubberknife.png");

            BaseCombatTargettingSO right = Targeting.GenerateSlotTarget(new int[] { 1, -4 }, false);

            Ability apotheosis = new Ability("Process Towards Apotheosis", "Salt_Apotheosis_A");
            apotheosis.Description = "Fully heal the Right ally.\nInflict Acid on them equal to the health healed.\nThis ability assumes the grid loops around.";
            apotheosis.AbilitySprite = ResourceLoader.LoadSprite("ability_apotheosis.png");
            apotheosis.Cost = [Pigments.Purple];
            apotheosis.Effects = new EffectInfo[2];
            apotheosis.Effects[0] = Effects.GenerateEffect(ScriptableObject.CreateInstance<FullHealEffect>(), 1, right);
            ApplyAcidEffect acid_exit = ScriptableObject.CreateInstance<ApplyAcidEffect>();
            acid_exit._MultPreviousExitValueForEntry = true;
            apotheosis.Effects[1] = Effects.GenerateEffect(acid_exit, 1, right);
            apotheosis.AddIntentsToTarget(right, [IntentType_GameIDs.Heal_11_20.ToString(), Acid.Intent]);
            apotheosis.AnimationTarget = right;
            apotheosis.Visuals = Visuals.Excommunicate;

            ExtraAbility_Wearable_SMS add_apotheosis = ScriptableObject.CreateInstance<ExtraAbility_Wearable_SMS>();
            add_apotheosis._extraAbility = apotheosis.GenerateCharacterAbility(true);

            ((Passives.Construct as Connection_PerformEffectPassiveAbility).connectionEffects[1].effect as CasterAddRandomExtraAbilityEffect)._extraData.Add(add_apotheosis);

            Basic_Item hearts = new Basic_Item("Salt_BleedingHearts_TW");
            hearts.Name = "Bleeding Hearts";
            hearts.Flavour = "\"One day you will die, but I will live forever.\"";
            hearts.Description = "Adds the extra ability \"Process Towards Apotheosis,\" a powerful healing ability with a downside.";
            hearts.Icon = ResourceLoader.LoadSprite("item_bleedinghearts.png");
            hearts.EquippedModifiers = [add_apotheosis];
            hearts.TriggerOn = TriggerCalls.Count;
            hearts.DoesPopUpInfo = false;
            hearts.Conditions = [];
            hearts.DoesActionOnTriggerAttached = false;
            hearts.ConsumeOnUse = false;
            hearts.ConsumeOnTrigger = TriggerCalls.Count;
            hearts.ConsumeConditions = [];
            hearts.ShopPrice = 4;
            hearts.IsShopItem = false;
            hearts.StartsLocked = true;
            hearts.OnUnlockUsesTHE = true;
            hearts.UsesSpecialUnlockText = false;
            hearts.SpecialUnlockID = UILocID.None;
            hearts.item._ItemTypeIDs = ["Heart"];
            hearts.item.AddBlueSkyUnlock("ShellyK_CH", "locked_bleedinghearts.png", "ach_bleedinghearts.png");

            MultiPerformEffectItem friend = new MultiPerformEffectItem("Salt_FriendshipBriefcase_SW", []);
            friend.Name = "Friendship Briefcase";
            friend.Flavour = "\"Friends everywhere you look!\"";
            friend.Description = "Deal 2 additional damage and healing.\n20% chance to be destroyed on dealing damage.";
            friend.Icon = ResourceLoader.LoadSprite("item_friendshipbriefcase.png");
            friend.EquippedModifiers = [];
            friend.TriggerOn = TriggerCalls.OnWillApplyHeal;
            friend.DoesPopUpInfo = true;
            friend.Conditions = [ItemExtensions.Heal(2, true, false, false)];
            friend.DoesActionOnTriggerAttached = false;
            friend.ConsumeOnTrigger = TriggerCalls.OnDidApplyDamage;
            friend.ConsumeOnUse = false;
            friend.ConsumeConditions = [ItemExtensions.Chance(20)];
            friend.ShopPrice = 5;
            friend.IsShopItem = true;
            friend.StartsLocked = true;
            friend.OnUnlockUsesTHE = true;
            friend.UsesSpecialUnlockText = false;
            friend.SpecialUnlockID = UILocID.None;
            friend.item._ItemTypeIDs = [];
            friend.AddEffectTrigger(new EffectTrigger([], [TriggerCalls.OnWillApplyDamage], [ItemExtensions.Damage(2, true, false)], false));
            friend.item.AddBlueSkyUnlock("LongLiver_CH", "locked_friendshipbriefcase.png", "ach_friendshipbriefcase.png");

            PerformEffect_Item recipe = new PerformEffect_Item("Salt_FalseImmortalityRecipe_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ResurrectEffect>(), 1, Slots.Self)]);
            recipe.Name = "False Immortality Recipe";
            recipe.Flavour = "\"Worked in my head...\"";
            recipe.Description = "On death, attempt to resurrect a random party member in this party member's former position if it is empty.";
            recipe.Icon = ResourceLoader.LoadSprite("item_falseimmortality.png");
            recipe.EquippedModifiers = [];
            recipe.TriggerOn = TriggerCalls.OnDeath;
            recipe.DoesPopUpInfo = true;
            recipe.Conditions = [];
            recipe.DoesActionOnTriggerAttached = false;
            recipe.ConsumeOnTrigger = TriggerCalls.Count;
            recipe.ConsumeOnUse = false;
            recipe.ConsumeConditions = [];
            recipe.ShopPrice = 10;
            recipe.IsShopItem = true;
            recipe.StartsLocked = true;
            recipe.OnUnlockUsesTHE = true;
            recipe.UsesSpecialUnlockText = false;
            recipe.SpecialUnlockID = UILocID.None;
            recipe.item._ItemTypeIDs = ["Magic"];
            recipe.item.AddBlueSkyUnlock("Clive_CH", "locked_falseimmortality.png", "ach_falseimmortality.png");

            PerformEffect_Item match = new PerformEffect_Item("Salt_LittleMatchbox_SW", [], true);
            match.Name = "Little Matchbox";
            match.Flavour = "\"Warm forever.\"";
            match.Description = "Fire no longer decreases on this party member's position.\nThis party member receives -100% Fire damage.";
            match.Icon = ResourceLoader.LoadSprite("item_littlematchbox.png");
            match.EquippedModifiers = [];
            match.TriggerOn = TriggerCalls.OnBeingDamaged;
            match.DoesPopUpInfo = true;
            match.Conditions = [ScriptableObject.CreateInstance<ColdHealCondition>()];
            match.DoesActionOnTriggerAttached = false;
            match.ConsumeOnTrigger = TriggerCalls.Count;
            match.ConsumeOnUse = false;
            match.ConsumeConditions = [];
            match.ShopPrice = 8;
            match.IsShopItem = true;
            match.StartsLocked = true;
            match.OnUnlockUsesTHE = true;
            match.UsesSpecialUnlockText = false;
            match.SpecialUnlockID = UILocID.None;
            match.item._ItemTypeIDs = [];
            match.item.AddBlueSkyUnlock("Kleiver_CH", "locked_littlematchbox.png", "ach_littlematchbox.png");

            PerformEffect_Item rations = new PerformEffect_Item("Salt_RadioactiveRations_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<HealEffect>(), 1, Slots.Self)]);
            rations.Name = "Radioactive Rations";
            rations.Flavour = "\"Not safe for, I mean, maybe safe for consumption.\"";
            rations.Description = "Heal 1 health on any ability being used.\nConsume this item at the end of combat if at full health.";
            rations.Icon = ResourceLoader.LoadSprite("item_radioactiverations.png");
            rations.TriggerOn = TriggerCalls.OnAnyAbilityUsed;
            rations.EquippedModifiers = [];
            rations.DoesPopUpInfo = true;
            rations.Conditions = [];
            rations.DoesActionOnTriggerAttached = false;
            rations.ConsumeOnTrigger = TriggerCalls.OnCombatEnd;
            rations.ConsumeOnUse = false;
            rations.ConsumeConditions = [ScriptableObject.CreateInstance<FullHealthEffectorCondition>()];
            rations.ShopPrice = 8;
            rations.IsShopItem = true;
            rations.StartsLocked = true;
            rations.OnUnlockUsesTHE = true;
            rations.UsesSpecialUnlockText = false;
            rations.SpecialUnlockID = UILocID.None;
            rations.item._ItemTypeIDs = [];
            rations.item.AddBlueSkyUnlock("Cranes_CH", "locked_radioactiverations.png", "ach_radioactiverations.png");

            PerformEffect_Item play = new PerformEffect_Item("Salt_ThePlay_SW", [], true);
            play.Name = "The Play";
            play.Flavour = "\"Your role isn't done yet.\"";
            play.Description = "On death, prevent it and heal 1 health.\nThis item is destroyed upon taking any damage.";
            play.Icon = ResourceLoader.LoadSprite("item_theplay.png");
            play.EquippedModifiers = [];
            play.TriggerOn = TriggerCalls.CanDie;
            play.DoesPopUpInfo = true;
            play.Conditions = [ScriptableObject.CreateInstance<TinCanCondition>()];
            play.DoesActionOnTriggerAttached = false;
            play.ConsumeOnTrigger = TriggerCalls.OnDamaged;
            play.ConsumeOnUse = false;
            play.ConsumeConditions = [];
            play.ShopPrice = 4;
            play.IsShopItem = true;
            play.StartsLocked = true;
            play.OnUnlockUsesTHE = false;
            play.UsesSpecialUnlockText = false;
            play.SpecialUnlockID = UILocID.None;
            play.item._ItemTypeIDs = [];
            play.item.AddBlueSkyUnlock("Agon_CH", "locked_theplay.png", "ach_theplay.png");

            PostFireEffect.Setup();
            Ability postfire = new Ability("Post-Fire", "PostFire_A");
            postfire.Description = "Deal 6-9 damage to the last enemy this party member dealt damage to.";
            postfire.Cost = [Pigments.Red, Pigments.Red];
            postfire.Rarity = Rarity.GetCustomRarity("rarity5");
            postfire.AbilitySprite = ResourceLoader.LoadSprite("ability_postfire.png");
            postfire.Effects = [Effects.GenerateEffect(ScriptableObject.CreateInstance<PostFireEffect>(), 6, Targeting.Unit_AllOpponents)];
            postfire.AddIntentsToTarget(Targeting.Unit_AllOpponents, ["Misc_Hidden", "Damage_7_10"]);
            postfire.Visuals = null;
            postfire.AnimationTarget = Slots.Self;

            ExtraAbility_Wearable_SMS add_postfire = ScriptableObject.CreateInstance<ExtraAbility_Wearable_SMS>();
            add_postfire._extraAbility = postfire.GenerateCharacterAbility(true);

            ((Passives.Construct as Connection_PerformEffectPassiveAbility).connectionEffects[1].effect as CasterAddRandomExtraAbilityEffect)._extraData.Add(add_postfire);

            Basic_Item receiver = new Basic_Item("Salt_Receiver_SW");
            receiver.Name = "Receiver";
            receiver.Flavour = "\"Voice from beyond\"";
            receiver.Description = "Adds the extra ability \"Post-Fire,\", a cheap long range damage ability.";
            receiver.Icon = ResourceLoader.LoadSprite("item_receiver.png");
            receiver.EquippedModifiers = [add_postfire];
            receiver.TriggerOn = TriggerCalls.Count;
            receiver.DoesPopUpInfo = false;
            receiver.Conditions = [];
            receiver.DoesActionOnTriggerAttached = false;
            receiver.ConsumeOnTrigger = TriggerCalls.Count;
            receiver.ConsumeOnUse = false;
            receiver.ConsumeConditions = [];
            receiver.ShopPrice = 5;
            receiver.IsShopItem = true;
            receiver.StartsLocked = true;
            receiver.OnUnlockUsesTHE = true;
            receiver.UsesSpecialUnlockText = false;
            receiver.SpecialUnlockID = UILocID.None;
            receiver.item._ItemTypeIDs = [];
            receiver.item.AddBlueSkyUnlock("Rags_CH", "locked_receiver.png", "ach_receiver.png");

            PerformEffect_Item death = new PerformEffect_Item("Salt_DeathCertificate_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<FullHealEffect>(), 1, Slots.Self), Effects.GenerateEffect(ScriptableObject.CreateInstance<FleeTargetEffect>(), 1, Slots.Self)]);
            death.Name = "Death Certificate";
            death.Flavour = "\"Who's in that grave!?\"";
            death.Description = "On taking any damage, fully heal this party member and instantly flee.";
            death.Icon = ResourceLoader.LoadSprite("item_deathcertificate.png");
            death.EquippedModifiers = [];
            death.TriggerOn = TriggerCalls.OnDamaged;
            death.DoesPopUpInfo = true;
            death.Conditions = [];
            death.DoesActionOnTriggerAttached = false;
            death.ConsumeOnTrigger = TriggerCalls.Count;
            death.ConsumeOnUse = false;
            death.ConsumeConditions = [];
            death.ShopPrice = 4;
            death.IsShopItem = true;
            death.StartsLocked = true;
            death.OnUnlockUsesTHE = true;
            death.UsesSpecialUnlockText = false;
            death.SpecialUnlockID = UILocID.None;
            death.item._ItemTypeIDs = [];
            death.item.AddBlueSkyUnlock("SmokeStacks_CH", "locked_deathcertificate.png", "ach_deathcertificate.png");

            MultiPerformEffectItem manual = new MultiPerformEffectItem("Salt_DissectionManual_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<GainPlayerCurrencyEffect>(), 5, Slots.Self)]);
            manual.Name = "Dissection Manual";
            manual.Flavour = "\"Follow precise instructions.\"";
            manual.Description = "On getting a kill, gain 5 coins.\nOn using an ability, lose 2 coins.";
            manual.Icon = ResourceLoader.LoadSprite("item_dissectionmanual.png");
            manual.TriggerOn = TriggerCalls.OnKill;
            manual.EquippedModifiers = [];
            manual.DoesPopUpInfo = true;
            manual.Conditions = [];
            manual.DoesActionOnTriggerAttached = false;
            manual.ConsumeOnTrigger = TriggerCalls.Count;
            manual.ConsumeOnUse = false;
            manual.ConsumeConditions = [];
            manual.ShopPrice = 5;
            manual.IsShopItem = true;
            manual.StartsLocked = true;
            manual.OnUnlockUsesTHE = true;
            manual.UsesSpecialUnlockText = false;
            manual.SpecialUnlockID = UILocID.None;
            manual.item._ItemTypeIDs = [];
            manual.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(ScriptableObject.CreateInstance<LosePlayerCurrencyEffect>(), 2, Slots.Self)], [TriggerCalls.OnAbilityWillBeUsed], []));
            manual.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(ScriptableObject.CreateInstance<ShowPlayerCurrencyEffect>(), 1, Slots.Self)], [TriggerCalls.OnCombatStart], [], false));
            manual.item.AddBlueSkyUnlock("Leviat_CH", "locked_dissectionmanual.png", "ach_dissectionmanual.png");

            Ability cat = new Ability("Cataclysm", "Salt_Cataclysm_A");
            cat.Description = "Deal 15 damage to all enemies.";
            cat.Cost = [Pigments.Purple, Pigments.Purple, Pigments.Purple];
            cat.Rarity = Rarity.GetCustomRarity("rarity5");
            cat.AbilitySprite = ResourceLoader.LoadSprite("ability_cataclysm.png");
            cat.Effects = [Effects.GenerateEffect(ScriptableObject.CreateInstance<DamageEffect>(), 15, Targeting.Unit_AllOpponents)];
            cat.AddIntentsToTarget(Targeting.Unit_AllOpponents, ["Damage_11_15"]);
            cat.Visuals = CustomVisuals.GetVisuals("Salt/StarBomb");
            cat.AnimationTarget = Targetting.Everything(false);

            ExtraAbility_Wearable_SMS add_cat = ScriptableObject.CreateInstance<ExtraAbility_Wearable_SMS>();
            add_cat._extraAbility = cat.GenerateCharacterAbility(true);

            ((Passives.Construct as Connection_PerformEffectPassiveAbility).connectionEffects[1].effect as CasterAddRandomExtraAbilityEffect)._extraData.Add(add_cat);

            PerformEffect_Item lunar = new PerformEffect_Item("Salt_LunarCharm_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<CasterRemoveItemExtraAbilityEffect>())]);
            lunar.Name = "Lunar Charm";
            lunar.Flavour = "\"Skyfall\"";
            lunar.Description = "Adds the extra ability \"Cataclysm\", an expensive but powerful mass damaging move.\nThis item is destroyed upon taking any damage.";
            lunar.Icon = ResourceLoader.LoadSprite("item_lunarcharm.png");
            lunar.EquippedModifiers = [add_cat];
            lunar.TriggerOn = TriggerCalls.OnDamaged;
            lunar.DoesPopUpInfo = true;
            lunar.Conditions = [];
            lunar.DoesActionOnTriggerAttached = false;
            lunar.ConsumeOnTrigger = TriggerCalls.Count;
            lunar.ConsumeOnUse = true;
            lunar.ConsumeConditions = [];
            lunar.ShopPrice = 4;
            lunar.IsShopItem = true;
            lunar.StartsLocked = true;
            lunar.OnUnlockUsesTHE = true;
            lunar.UsesSpecialUnlockText = false;
            lunar.SpecialUnlockID = UILocID.None;
            lunar.item._ItemTypeIDs = ["Magic"];
            lunar.item.AddBlueSkyUnlock("Bimini_CH", "locked_lunarcharm.png", "ach_lunarcharm.png");

            PerformEffect_Item weep = new PerformEffect_Item("Salt_WeepingAngel_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<SwapToSidesEffect>(), 1, Slots.Self), Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyFocusedEffect>(), 1, Slots.Self)]);
            weep.Name = "Weeping Angel";
            weep.Flavour = "\"Cry for me.\"";
            weep.Description = "On turn end, if there is no Opposing enemy, move Left or Right and become Focused.";
            weep.Icon = ResourceLoader.LoadSprite("item_weepingangel.png");
            weep.EquippedModifiers = [];
            weep.TriggerOn = TriggerCalls.OnTurnFinished;
            weep.DoesPopUpInfo = true;
            weep.Conditions = [];
            weep.DoesActionOnTriggerAttached = false;
            weep.ConsumeOnTrigger = TriggerCalls.Count;
            weep.ConsumeOnUse = false;
            weep.ConsumeConditions = [];
            weep.ShopPrice = 4;
            weep.IsShopItem = true;
            weep.StartsLocked = true;
            weep.OnUnlockUsesTHE = true;
            weep.UsesSpecialUnlockText = false;
            weep.SpecialUnlockID = UILocID.None;
            weep.item._ItemTypeIDs = ["Angel"];
            weep.item.AddBlueSkyUnlock("Formosus_CH", "locked_weepingangel.png", "ach_weepingangel.png");

            PassiveLockingEffect cogEffect = ScriptableObject.CreateInstance<PassiveLockingEffect>();
            cogEffect.m_PassiveIDs = [
                Passives.Skittish.m_PassiveID, Passives.Slippery.m_PassiveID, Passives.Constricting.m_PassiveID, PassiveType_GameIDs.Anchored.ToString(),
                "Jumpy_PA", "Lightweight_PA", "Scramble_PA", "Evasive_PA", "Turbulent_PA", "CCTV_PA", "Jittery_PA", "Fluttery_PA", "Warping_PA",
                "Lonely_PA", "Melancholy_PA", "Gluttony_PA", "Rotary_PA", "Marching_PA", "Hiding_PA", "Seeking_PA", 
                "Lockstep_ID", "Cadence_ID", "RightStrafe_ID", "LeftStrafe_ID",
                "Sweeping_PA", "Shy_PA", "Confrontational_PA", "Escapist_PA",
                ];

            PerformEffect_Item cog = new PerformEffect_Item("Salt_Cog_SW", [Effects.GenerateEffect(cogEffect)]);
            cog.Name = "The Cog";
            cog.Flavour = "\"it's a metaphor.\"";
            cog.Description = "Disable most movement passives.";
            cog.Icon = ResourceLoader.LoadSprite("item_cog.png");
            cog.EquippedModifiers = [];
            cog.TriggerOn = TriggerCalls.OnBeforeCombatStart;
            cog.DoesPopUpInfo = false;
            cog.Conditions = [];
            cog.DoesActionOnTriggerAttached = false;
            cog.ConsumeOnTrigger = TriggerCalls.Count;
            cog.ConsumeOnUse = false;
            cog.ConsumeConditions = [];
            cog.ShopPrice = 4;
            cog.IsShopItem = true;
            cog.StartsLocked = true;
            cog.OnUnlockUsesTHE = false;
            cog.UsesSpecialUnlockText = false;
            cog.SpecialUnlockID = UILocID.None;
            cog.item._ItemTypeIDs = [];
            cog.item.AddBlueSkyUnlock("Gospel_CH", "locked_cog.png", "ach_cog.png");

            PerformEffect_Item nautilus = new PerformEffect_Item("Salt_Nautilus_EW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<HealEffect>(), 4, Slots.Self), Effects.GenerateEffect(ScriptableObject.CreateInstance<RemoveAllStatusEffectsEffect>(), 1, Slots.Self)]);
            nautilus.Name = "Nautilus";
            nautilus.Flavour = "\"You caught a... Chambered Nautilus! 18cm.\"";
            nautilus.Description = "At the end of each turn, heal this party member 4 health and remove all their Status Effects.\n35% chance to be consumed upon activation.";
            nautilus.Icon = ResourceLoader.LoadSprite("item_nautilus.png");
            nautilus.EquippedModifiers = [];
            nautilus.TriggerOn = TriggerCalls.OnTurnFinished;
            nautilus.DoesPopUpInfo = true;
            nautilus.Conditions = [];
            nautilus.DoesActionOnTriggerAttached = false;
            nautilus.ConsumeOnTrigger = TriggerCalls.Count;
            nautilus.ConsumeOnUse = true;
            nautilus.ConsumeConditions = [ItemExtensions.Chance(35)];
            nautilus.ShopPrice = 6;
            nautilus.IsShopItem = false;
            nautilus.StartsLocked = true;
            nautilus.OnUnlockUsesTHE = true;
            nautilus.UsesSpecialUnlockText = true;
            nautilus.SpecialUnlockID = UILocID.ItemFishLocationLabel;
            nautilus.item._ItemTypeIDs = [];
            nautilus.item.AddBlueSkyUnlock("Mung_CH", "locked_nautilus.png", "ach_nautilus.png", 2);

            MultiPerformEffectItem smile = new MultiPerformEffectItem("Salt_SmileMask_TW", []);
            smile.Name = "Smile Mask";
            smile.Flavour = "\"People like you better this way.\"";
            smile.Description = "Deal 50% more damage.\nApply 3 Anesthetics to damaged targets.";
            smile.Icon = ResourceLoader.LoadSprite("item_smilemask.png");
            smile.EquippedModifiers = [];
            smile.TriggerOn = TriggerCalls.OnWillApplyDamage;
            smile.DoesPopUpInfo = false;
            smile.Conditions = [ItemExtensions.Damage(50, true)];
            smile.DoesActionOnTriggerAttached = false;
            smile.ConsumeOnTrigger = TriggerCalls.Count;
            smile.ConsumeOnUse = false;
            smile.ConsumeConditions = [];
            smile.ShopPrice = 5;
            smile.IsShopItem = false;
            smile.StartsLocked = true;
            smile.OnUnlockUsesTHE = true;
            smile.UsesSpecialUnlockText = false;
            smile.SpecialUnlockID = UILocID.None;
            smile.item._ItemTypeIDs = ["Face"];
            smile.AddEffectTrigger(new EffectTrigger([], [AdvancedDamageTrigger.Dealt], [DamageTargetEffectsCondition.Create([Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyAnestheticsEffect>(), 3, Slots.Self)], true)], false));
            smile.item.AddBlueSkyUnlock("Mordrake_CH", "locked_smilemask.png", "ach_smilemask.png");
        }
    }
}
