using BrutalAPI.Items;
using BrutalAPI;
using System;
using System.Collections.Generic;
using System.Text;
using static SaltsEnemies_Reseasoned.Shore.H;
using UnityEngine;
using SaltEnemies_Reseasoned;

namespace SaltsEnemies_Reseasoned
{
    public static class UnlocksFour
    {
        public static void Add()
        {
            MultiPerformEffectItem heart = new MultiPerformEffectItem("Salt_SecondHeart_SW", []);
            heart.Name = "Second Heart";
            heart.Flavour = "\"As a precaution\"";
            heart.Description = "Receive 100% more healing.\nOn being directly damaged, gain Cursed.";
            heart.Icon = ResourceLoader.LoadSprite("item_secondheart.png");
            heart.TriggerOn = TriggerCalls.OnBeingHealed;
            heart.EquippedModifiers = [];
            heart.DoesPopUpInfo = false;
            heart.Conditions = [HealingReceivedCondition.Create(100, true)];
            heart.DoesActionOnTriggerAttached = false;
            heart.ConsumeOnTrigger = TriggerCalls.Count;
            heart.ConsumeOnUse = false;
            heart.ConsumeConditions = [];
            heart.ShopPrice = 6;
            heart.IsShopItem = true;
            heart.StartsLocked = true;
            heart.OnUnlockUsesTHE = true;
            heart.UsesSpecialUnlockText = false;
            heart.SpecialUnlockID = UILocID.None;
            heart.item._ItemTypeIDs = ["Heart", "Meat"];
            heart.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyCursedEffect>(), 1, Slots.Self)], [TriggerCalls.OnDirectDamaged], []));
            heart.item.AddBlueSkyUnlock("Mazur_CH", "locked_secondheart.png", "ach_secondheart.png");

            MultiPerformEffectItem charcoal = new MultiPerformEffectItem("Salt_Charcoal_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyFireSlotEffect>(), 1, Slots.Self)]);
            charcoal.Name = "Charcoal";
            charcoal.Flavour = "\"Leftover fire\"";
            charcoal.Description = "On moving, gain 1 Fire.\nTake 50% less direct damage.";
            charcoal.Icon = ResourceLoader.LoadSprite("item_charcoal.png");
            charcoal.EquippedModifiers = [];
            charcoal.TriggerOn = TriggerCalls.OnMoved;
            charcoal.DoesPopUpInfo = true;
            charcoal.Conditions = [];
            charcoal.DoesActionOnTriggerAttached = false;
            charcoal.ConsumeOnTrigger = TriggerCalls.Count;
            charcoal.ConsumeOnUse = false;
            charcoal.ConsumeConditions = [];
            charcoal.ShopPrice = 4;
            charcoal.IsShopItem = true;
            charcoal.StartsLocked = true;
            charcoal.OnUnlockUsesTHE = true;
            charcoal.UsesSpecialUnlockText = false;
            charcoal.SpecialUnlockID = UILocID.None;
            charcoal.item._ItemTypeIDs = [];
            charcoal.AddEffectTrigger(new EffectTrigger([], [TriggerCalls.OnBeingDamaged], [ItemExtensions.Defense(0, false, true)], false));
            charcoal.item.AddBlueSkyUnlock("Ash_CH", "locked_charcoal.png", "ach_charcoal.png");
            ApplyFoundStatusEffect wildcard = ScriptableObject.CreateInstance<ApplyFoundStatusEffect>();
            wildcard.useStatus = "WildCard_ID";

            MultiPerformEffectItem entropy = new MultiPerformEffectItem("Salt_EntropicAnalysis_TW", [Effects.GenerateEffect(wildcard, 2, Slots.Self)]);
            entropy.Name = "Entropic Analysis";
            entropy.Flavour = "\"Are you truly ready to pay the debt this machine has incurred?\"";
            entropy.Description = "At the start of each turn, gain 2 Wild Card.\nAt the end of each turn, give the Opposing enemy 2 Wild Card.";
            entropy.Icon = ResourceLoader.LoadSprite("item_entropicanalysis.png");
            entropy.EquippedModifiers = [];
            entropy.TriggerOn = TriggerCalls.OnTurnStart;
            entropy.DoesPopUpInfo = true;
            entropy.Conditions = [];
            entropy.DoesActionOnTriggerAttached = false;
            entropy.ConsumeOnTrigger = TriggerCalls.Count;
            entropy.ConsumeOnUse = false;
            entropy.ConsumeConditions = [];
            entropy.ShopPrice = 4;
            entropy.IsShopItem = false;
            entropy.StartsLocked = true;
            entropy.OnUnlockUsesTHE = true;
            entropy.UsesSpecialUnlockText = false;
            entropy.SpecialUnlockID = UILocID.None;
            entropy.item._ItemTypeIDs = [];
            entropy.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(wildcard, 2, Slots.Front)], [TriggerCalls.OnTurnFinished], []));
            entropy.item.AddBlueSkyUnlock("Andy_CH", "locked_entropicanalysis.png", "ach_entropicanalysis.png");

            PerformEffect_Item boot = new PerformEffect_Item("Salt_MuddyBoot_SW", [Effects.GenerateEffect(BasicEffects.Empty, 2), Effects.GenerateEffect(ScriptableObject.CreateInstance<RandomHealBetweenPreviousAndEntryEffect>(), 3, Slots.Self), Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplySlipSlotEffect>(), 2, Slots.Self)]);
            boot.Name = "Muddy Boot";
            boot.Flavour = "\"Splish Splash\"";
            boot.Description = "At the end of each turn, heal 2-3 health and gain 2 Slip.";
            boot.Icon = ResourceLoader.LoadSprite("item_muddyboot.png");
            boot.TriggerOn = TriggerCalls.OnTurnFinished;
            boot.EquippedModifiers = [];
            boot.DoesPopUpInfo = true;
            boot.Conditions = [];
            boot.DoesActionOnTriggerAttached = false;
            boot.ConsumeOnTrigger = TriggerCalls.Count;
            boot.ConsumeOnUse = false;
            boot.ConsumeConditions = [];
            boot.ShopPrice = 4;
            boot.IsShopItem = true;
            boot.StartsLocked = true;
            boot.OnUnlockUsesTHE = true;
            boot.UsesSpecialUnlockText = false;
            boot.SpecialUnlockID = UILocID.None;
            boot.item._ItemTypeIDs = ["Fabric"];
            boot.item.AddBlueSkyUnlock("Kraus_CH", "locked_muddyboot.png", "ach_muddyboot.png");

            PerformEffect_Item eye = new PerformEffect_Item("Salt_OpalescentEye_SW", []);
            eye.Name = "Opalescent Eye";
            eye.Flavour = "\"Look away!\"";
            eye.Description = "Heal 60% more to non-Purple targets.";
            eye.Icon = ResourceLoader.LoadSprite("item_opalescenteye.png");
            eye.TriggerOn = TriggerCalls.OnWillApplyHeal;
            eye.EquippedModifiers = [];
            eye.DoesPopUpInfo = false;
            eye.Conditions = [ScriptableObject.CreateInstance<HealMoreNonPurpleCondition>()];
            eye.DoesActionOnTriggerAttached = false;
            eye.ConsumeOnTrigger = TriggerCalls.Count;
            eye.ConsumeOnUse = false;
            eye.ConsumeConditions = [];
            eye.ShopPrice = 5;
            eye.IsShopItem = true;
            eye.StartsLocked = true;
            eye.OnUnlockUsesTHE = true;
            eye.UsesSpecialUnlockText = false;
            eye.SpecialUnlockID = UILocID.None;
            eye.item._ItemTypeIDs = [];
            eye.item.AddBlueSkyUnlock("Vendella_CH", "locked_opalescenteye.png", "ach_opalescenteye.png");

            PerformEffect_Item mosquito = new PerformEffect_Item("Salt_BigMosquito_SW", []);
            mosquito.Name = "Big Mosquito";
            mosquito.Flavour = "\"It's very big.\"";
            mosquito.Description = "Heal for damage dealt.\nDestroy this item on dealing over 21 damage in 1 combat.";
            mosquito.Icon = ResourceLoader.LoadSprite("item_bigmosquito.png");
            mosquito.TriggerOn = TriggerCalls.OnDidApplyDamage;
            mosquito.EquippedModifiers = [];
            mosquito.DoesPopUpInfo = false;
            mosquito.Conditions = [ScriptableObject.CreateInstance<BigMosquitoCondition>()];
            mosquito.DoesActionOnTriggerAttached = false;
            mosquito.ConsumeOnTrigger = TriggerCalls.Count;
            mosquito.ConsumeOnUse = false;
            mosquito.ConsumeConditions = [];
            mosquito.ShopPrice = 6;
            mosquito.IsShopItem = true;
            mosquito.StartsLocked = true;
            mosquito.OnUnlockUsesTHE = true;
            mosquito.UsesSpecialUnlockText = false;
            mosquito.SpecialUnlockID = UILocID.None;
            mosquito.item._ItemTypeIDs = [];
            mosquito.item.AddBlueSkyUnlock("Jarova_CH", "locked_bigmosquito.png", "ach_bigmosquito.png");

            MultiPerformEffectItem stick = new MultiPerformEffectItem("Salt_ReallyBigStick_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyScarsEffect>(), 2, Slots.Self)]);
            stick.Name = "Really Big Stick";
            stick.Flavour = "\"Dammit! Splinters!\"";
            stick.Description = "Deal 2 additional damage.\nGain 2 Scars on kill.";
            stick.Icon = ResourceLoader.LoadSprite("item_reallybigstick.png");
            stick.EquippedModifiers = [];
            stick.TriggerOn = TriggerCalls.OnKill;
            stick.DoesPopUpInfo = true;
            stick.Conditions = [];
            stick.DoesActionOnTriggerAttached = false;
            stick.ConsumeOnTrigger = TriggerCalls.Count;
            stick.ConsumeOnUse = false;
            stick.ConsumeConditions = [];
            stick.ShopPrice = 8;
            stick.IsShopItem = true;
            stick.StartsLocked = true;
            stick.OnUnlockUsesTHE = true;
            stick.UsesSpecialUnlockText = false;
            stick.SpecialUnlockID = UILocID.None;
            stick.item._ItemTypeIDs = [];
            stick.AddEffectTrigger(new EffectTrigger([], [TriggerCalls.OnWillApplyDamage], [ItemExtensions.Damage(2, true, false)], false));
            stick.item.AddBlueSkyUnlock("Raphe_CH", "locked_reallybigstick.png", "ach_reallybigstick.png");

            PerformEffect_Item symbiote = new PerformEffect_Item("Salt_SymbioteInjection_TW", []);
            symbiote.Name = "Symbiote Injection";
            symbiote.Flavour = "\"Are you sure I need this shot?\"";
            symbiote.Description = "On being directly damaged, gain an equal amount of Growth.";
            symbiote.Icon = ResourceLoader.LoadSprite("item_symbioteinjection.png");
            symbiote.EquippedModifiers = [];
            symbiote.TriggerOn = TriggerCalls.OnDirectDamaged;
            symbiote.DoesPopUpInfo = false;
            symbiote.Conditions = [ScriptableObject.CreateInstance<SymbioteCondition>()];
            symbiote.DoesActionOnTriggerAttached = false;
            symbiote.ConsumeOnTrigger = TriggerCalls.Count;
            symbiote.ConsumeOnUse = false;
            symbiote.ConsumeConditions = [];
            symbiote.ShopPrice = 6;
            symbiote.IsShopItem = false;
            symbiote.StartsLocked = true;
            symbiote.OnUnlockUsesTHE = true;
            symbiote.UsesSpecialUnlockText = false;
            symbiote.SpecialUnlockID = UILocID.None;
            symbiote.item._ItemTypeIDs = [];
            symbiote.item.AddBlueSkyUnlock("Thern_CH", "locked_symbioteinjection.png", "ach_symbioteinjection.png");

            PerformEffect_Item hammer = new PerformEffect_Item("Salt_GlassHammer_SW", []);
            hammer.Name = "Glass Hammer";
            hammer.Flavour = "\"Decorative power.\"";
            hammer.Description = "Damage dealt spreads indirectly Left and Right.\nThis item is destroyed upon being directly damaged.";
            hammer.Icon = ResourceLoader.LoadSprite("item_glasshammer.png");
            hammer.EquippedModifiers = [];
            hammer.TriggerOn = CascadingDamageItemHandler.Call;
            hammer.DoesPopUpInfo = true;
            hammer.Conditions = [BooleanSetterCondition.Create(true, true, false)];
            hammer.DoesActionOnTriggerAttached = false;
            hammer.ConsumeOnTrigger = TriggerCalls.OnDirectDamaged;
            hammer.ConsumeOnUse = false;
            hammer.ConsumeConditions = [];
            hammer.ShopPrice = 9;
            hammer.IsShopItem = true;
            hammer.StartsLocked = true;
            hammer.OnUnlockUsesTHE = true;
            hammer.UsesSpecialUnlockText = false;
            hammer.SpecialUnlockID = UILocID.None;
            hammer.item._ItemTypeIDs = [];
            hammer.item.AddBlueSkyUnlock("Lilian_CH", "locked_glasshammer.png", "ach_glasshammer.png");

            PerformEffect_Item anchor = new PerformEffect_Item("Salt_WoodenAnchor_SW", []);
            anchor.Name = "Wooden Anchor";
            anchor.Flavour = "\"Sinks as well as it floats\"";
            anchor.Description = "Direct heaing received by this party member is instead distributed amongst all other party members.";
            anchor.Icon = ResourceLoader.LoadSprite("item_woodenanchor.png");
            anchor.EquippedModifiers = [];
            anchor.TriggerOn = TriggerCalls.OnBeingHealed;
            anchor.DoesPopUpInfo = false;
            anchor.Conditions = [ScriptableObject.CreateInstance<DistributeHealCondition>()];
            anchor.DoesActionOnTriggerAttached = false;
            anchor.ConsumeOnTrigger = TriggerCalls.Count;
            anchor.ConsumeOnUse = false;
            anchor.ConsumeConditions = [];
            anchor.ShopPrice = 3;
            anchor.IsShopItem = true;
            anchor.StartsLocked = true;
            anchor.OnUnlockUsesTHE = true;
            anchor.UsesSpecialUnlockText = false;
            anchor.SpecialUnlockID = UILocID.None;
            anchor.item._ItemTypeIDs = [];
            anchor.item.AddBlueSkyUnlock("Lawrence_CH", "locked_woodenanchor.png", "ach_woodenanchor.png");

            PerformEffect_Item guide = new PerformEffect_Item("Salt_HarmGuide_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<RestoreSwapUseEffect>(), 1, Slots.Self)]);
            guide.Name = "Guide to Harming Others";
            guide.Flavour = "\"Simpler than it seems!\"";
            guide.Description = "On using an ability while in Shield, refresh movement.";
            guide.Icon = ResourceLoader.LoadSprite("item_harmguide.png");
            guide.EquippedModifiers = [];
            guide.TriggerOn = TriggerCalls.OnAbilityUsed;
            guide.DoesPopUpInfo = true;
            guide.Conditions = [ScriptableObject.CreateInstance<InShieldEffectorCondition>()];
            guide.DoesActionOnTriggerAttached = false;
            guide.ConsumeOnTrigger = TriggerCalls.Count;
            guide.ConsumeOnUse = false;
            guide.ConsumeConditions = [];
            guide.ShopPrice = 3;
            guide.IsShopItem = true;
            guide.StartsLocked = true;
            guide.OnUnlockUsesTHE = true;
            guide.UsesSpecialUnlockText = false;
            guide.SpecialUnlockID = UILocID.None;
            guide.item._ItemTypeIDs = [];
            guide.item.AddBlueSkyUnlock("Warsaw_CH", "locked_harmguide.png", "ach_harmguide.png");

            ApplyFoundFieldEffect spikes = ScriptableObject.CreateInstance<ApplyFoundFieldEffect>();
            spikes.useField = "Spikes_ID";

            PerformEffect_Item dmz = new PerformEffect_Item("Salt_DMZ_TW", [Effects.GenerateEffect(spikes, 1, Slots.Self), Effects.GenerateEffect(spikes, 4, Slots.Front)]);
            dmz.Name = "Demilitarized Zone";
            dmz.Flavour = "\"The whole thing.\"";
            dmz.Description = "On manually moving, gain 1 Spikes and inflict 4 Spikes on the Opposing position.";
            dmz.Icon = ResourceLoader.LoadSprite("item_dmz.png");
            dmz.TriggerOn = TriggerCalls.OnSwapTo;
            dmz.EquippedModifiers = [];
            dmz.DoesPopUpInfo = true;
            dmz.Conditions = [];
            dmz.DoesActionOnTriggerAttached = false;
            dmz.ConsumeOnTrigger = TriggerCalls.Count;
            dmz.ConsumeOnUse = false;
            dmz.ConsumeConditions = [];
            dmz.ShopPrice = 3;
            dmz.IsShopItem = false;
            dmz.StartsLocked = true;
            dmz.OnUnlockUsesTHE = true;
            dmz.UsesSpecialUnlockText = false;
            dmz.SpecialUnlockID = UILocID.None;
            dmz.item._ItemTypeIDs = [];
            dmz.item.AddBlueSkyUnlock("Bingo_CH", "locked_dmz.png", "ach_dmz.png");

            PerformEffect_Item gloves = new PerformEffect_Item("Salt_Antigloves_SW", []);
            gloves.Name = "Antigloves";
            gloves.Flavour = "\"From Antiworld.\"";
            gloves.Description = "Apply 1 Slip to damaged targets.";
            gloves.Icon = ResourceLoader.LoadSprite("item_antigloves.png");
            gloves.EquippedModifiers = [];
            gloves.TriggerOn = AdvancedDamageTrigger.Dealt;
            gloves.DoesPopUpInfo = false;
            gloves.Conditions = [DamageTargetEffectsCondition.Create([Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplySlipSlotEffect>(), 1, Targeting.Slot_SelfAll)], true)];
            gloves.DoesActionOnTriggerAttached = false;
            gloves.ConsumeOnTrigger = TriggerCalls.Count;
            gloves.ConsumeOnUse = false;
            gloves.ConsumeConditions = [];
            gloves.ShopPrice = 2;
            gloves.IsShopItem = true;
            gloves.StartsLocked = true;
            gloves.OnUnlockUsesTHE = true;
            gloves.UsesSpecialUnlockText = false;
            gloves.SpecialUnlockID = UILocID.None;
            gloves.item._ItemTypeIDs = ["Fabric"];
            gloves.item.AddBlueSkyUnlock("Macy_CH", "locked_antigloves.png", "ach_antigloves.png");

            PerformEffect_Item kaleidoscope = new PerformEffect_Item("Salt_Kaleidoscope_TW", []);
            kaleidoscope.Name = "Kaleidoscope";
            kaleidoscope.Flavour = "\"Transmutate the world\"";
            kaleidoscope.Description = "Damage dealt to non-Red enemies spreads indirectly left and right.";
            kaleidoscope.Icon = ResourceLoader.LoadSprite("item_kaleidoscope.png");
            kaleidoscope.TriggerOn = CascadingDamageItemHandler.Call;
            kaleidoscope.EquippedModifiers = [];
            kaleidoscope.DoesPopUpInfo = false;
            kaleidoscope.Conditions = [ScriptableObject.CreateInstance<KaleidoscopeCondition>()];
            kaleidoscope.DoesActionOnTriggerAttached = false;
            kaleidoscope.ConsumeOnTrigger = TriggerCalls.Count;
            kaleidoscope.ConsumeOnUse = false;
            kaleidoscope.ConsumeConditions = [];
            kaleidoscope.ShopPrice = 5;
            kaleidoscope.IsShopItem = false;
            kaleidoscope.StartsLocked = true;
            kaleidoscope.OnUnlockUsesTHE = true;
            kaleidoscope.UsesSpecialUnlockText = false;
            kaleidoscope.SpecialUnlockID = UILocID.None;
            kaleidoscope.item._ItemTypeIDs = [];
            kaleidoscope.item.AddBlueSkyUnlock("Jebrick_CH", "locked_kaleidoscope.png", "ach_kaleidoscope.png");
        }
    }
}
