using BrutalAPI;
using BrutalAPI.Items;
using SaltEnemies_Reseasoned;
using SaltsEnemies_Reseasoneds;
using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace SaltsEnemies_Reseasoned
{
    public static class UnlocksSix
    {
        public static void Add()
        {
            PerformEffect_Item hammer = new PerformEffect_Item("Salt_KindnessHammer_SW", []);
            hammer.Name = "Kindness Hammer";
            hammer.Flavour = "\"So generous...\"";
            hammer.Description = "Deal 25% more damage.\nHeal targets 4 health before damaging them.";
            hammer.Icon = ResourceLoader.LoadSprite("item_kindnesshammer.png");
            hammer.TriggerOn = TriggerCalls.OnWillApplyDamage;
            hammer.EquippedModifiers = [];
            hammer.DoesPopUpInfo = false;
            hammer.Conditions = [ScriptableObject.CreateInstance<KindnessHammerCondition>()];
            hammer.DoesActionOnTriggerAttached = false;
            hammer.ConsumeOnTrigger = TriggerCalls.Count;
            hammer.ConsumeOnUse = false;
            hammer.ConsumeConditions = [];
            hammer.ShopPrice = 4;
            hammer.IsShopItem = true;
            hammer.StartsLocked = true;
            hammer.OnUnlockUsesTHE = true;
            hammer.UsesSpecialUnlockText = false;
            hammer.SpecialUnlockID = UILocID.None;
            hammer.item._ItemTypeIDs = [];
            hammer.item.AddBlueSkyUnlock("Ham_CH", "locked_kindnesshammer.png", "ach_kindnesshammer.png");

            PerformEffect_Item pylon = new PerformEffect_Item("Salt_Pylon_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyFocusedEffect>(), 1, Slots.Self), Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplySlipSlotEffect>(), 10, Slots.Self)]);
            pylon.Name = "Pylon";
            pylon.Flavour = "\"Plastic Power\"";
            pylon.Description = "At the start of each turn, gain Focused and 10 Slip.";
            pylon.Icon = ResourceLoader.LoadSprite("item_pylon.png");
            pylon.TriggerOn = TriggerCalls.OnTurnStart;
            pylon.EquippedModifiers = [];
            pylon.DoesPopUpInfo = true;
            pylon.Conditions = [];
            pylon.DoesActionOnTriggerAttached = false;
            pylon.ConsumeOnTrigger = TriggerCalls.Count;
            pylon.ConsumeOnUse = false;
            pylon.ConsumeConditions = [];
            pylon.ShopPrice = 3;
            pylon.IsShopItem = true;
            pylon.StartsLocked = true;
            pylon.OnUnlockUsesTHE = true;
            pylon.UsesSpecialUnlockText = false;
            pylon.SpecialUnlockID = UILocID.None;
            pylon.item._ItemTypeIDs = [];
            pylon.item.AddBlueSkyUnlock("Knotty_CH", "locked_pylon.png", "ach_pylon.png");

            RemoveStatusEffectEffect rem_curse = ScriptableObject.CreateInstance<RemoveStatusEffectEffect>();
            rem_curse._status = StatusField.Cursed;

            MultiPerformEffectItem staff = new MultiPerformEffectItem("Salt_PharaohScepter_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyCursedEffect>(), 1, Slots.Self)]);
            staff.Name = "Pharaoh's Scepter";
            staff.Flavour = "\"The Pharaoh's Curse!!!\"";
            staff.Description = "On being directly damaged, become Cursed.\nOn using an ability while Cursed, remove Cursed and refresh this party member's ability usage.";
            staff.Icon = ResourceLoader.LoadSprite("item_pharaohscepter.png");
            staff.TriggerOn = TriggerCalls.OnDirectDamaged;
            staff.EquippedModifiers = [];
            staff.DoesPopUpInfo = true;
            staff.Conditions = [];
            staff.DoesActionOnTriggerAttached = false;
            staff.ConsumeOnTrigger = TriggerCalls.Count;
            staff.ConsumeOnUse = false;
            staff.ConsumeConditions = [];
            staff.ShopPrice = 7;
            staff.IsShopItem = false;
            staff.StartsLocked = true;
            staff.OnUnlockUsesTHE = true;
            staff.UsesSpecialUnlockText = false;
            staff.SpecialUnlockID = UILocID.None;
            staff.item._ItemTypeIDs = ["Magic"];
            staff.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(rem_curse, 1, Slots.Self), Effects.GenerateEffect(ScriptableObject.CreateInstance<RefreshAbilityUseEffect>(), 1, Slots.Self)], [TriggerCalls.OnAbilityUsed], [ScriptableObject.CreateInstance<IsCursedEffectorCondition>()]));
            staff.item.AddBlueSkyUnlock("Serpent_CH", "locked_pharaohscepter.png", "ach_pharaohscepter.png");

            PerformEffect_Item scalpel = new PerformEffect_Item("Salt_Scalpel_SW", []);
            scalpel.Name = "Scalpel";
            scalpel.Flavour = "\"Be careful with that!\"";
            scalpel.Description = "Reduce negative status effects on healed targets by 2.";
            scalpel.Icon = ResourceLoader.LoadSprite("item_scalpel.png");
            scalpel.TriggerOn = TriggerCalls.OnWillApplyHeal;
            scalpel.EquippedModifiers = [];
            scalpel.DoesPopUpInfo = false;
            scalpel.Conditions = [ScriptableObject.CreateInstance<ReduceNegStatusOnHealTargetsEffectorCondition>()];
            scalpel.DoesActionOnTriggerAttached = false;
            scalpel.ConsumeOnTrigger = TriggerCalls.Count;
            scalpel.ConsumeOnUse = false;
            scalpel.ConsumeConditions = [];
            scalpel.ShopPrice = 7;
            scalpel.IsShopItem = true;
            scalpel.StartsLocked = true;
            scalpel.OnUnlockUsesTHE = true;
            scalpel.UsesSpecialUnlockText = false;
            scalpel.SpecialUnlockID = UILocID.None;
            scalpel.item._ItemTypeIDs = ["Knife"];
            scalpel.item.AddBlueSkyUnlock("WormWoomb_CH", "locked_scalpel.png", "ach_scalpel.png");

            ExtraPassiveAbility_Wearable_SMS leaky = ScriptableObject.CreateInstance<ExtraPassiveAbility_Wearable_SMS>();
            leaky._extraPassiveAbility = Passives.Leaky3;

            PerformEffect_Item meat = new PerformEffect_Item("Salt_MeatMan_SW", [Effects.GenerateEffect(BasicEffects.Empty, 1), Effects.GenerateEffect(ScriptableObject.CreateInstance<RandomHealBetweenPreviousAndEntryEffect>(), 5, Slots.Self)]);
            meat.Name = "Meat Man";
            meat.Flavour = "\"Do you ever seek forgiveness?\"";
            meat.Description = "Heal 1-5 health at the start of each turn.\nThis party member has Leaky (3) as a passive.";
            meat.Icon = ResourceLoader.LoadSprite("item_meatman.png");
            meat.TriggerOn = TriggerCalls.OnTurnStart;
            meat.EquippedModifiers = [leaky];
            meat.DoesPopUpInfo = true;
            meat.Conditions = [];
            meat.DoesActionOnTriggerAttached = false;
            meat.ConsumeOnTrigger = TriggerCalls.Count;
            meat.ConsumeOnUse = false;
            meat.ConsumeConditions = [];
            meat.ShopPrice = 4;
            meat.IsShopItem = true;
            meat.StartsLocked = true;
            meat.OnUnlockUsesTHE = true;
            meat.UsesSpecialUnlockText = false;
            meat.SpecialUnlockID = UILocID.None;
            meat.item._ItemTypeIDs = ["Meat"];
            meat.item.AddBlueSkyUnlock("Flodhest_CH", "locked_meatman.png", "ach_meatman.png");

            ApplyFoundStatusEffect coral = ScriptableObject.CreateInstance<ApplyFoundStatusEffect>();
            coral.useStatus = "CoralColony_ID";
            ApplyFoundStatusEffect random_coral = ScriptableObject.CreateInstance<ApplyFoundStatusEffect>();
            random_coral.useStatus = "CoralColony_ID";
            random_coral._RandomBetweenPrevious = true;

            PerformEffect_Item berry = new PerformEffect_Item("Salt_StrawberryFriend_TW", [Effects.GenerateEffect(BasicEffects.Empty, 2), Effects.GenerateEffect(random_coral, 4, Targetting.Random(false)), Effects.GenerateEffect(coral, 2, Slots.Self)]);
            berry.Name = "Strawberry Friend";
            berry.Flavour = "\"Sensory Stimulation\"";
            berry.Description = "At the start of each turn, inflict 2-4 Coral Colony on a random enemy and 2 Coral Colony to this party member.";
            berry.Icon = ResourceLoader.LoadSprite("item_strawberryfriend.png");
            berry.TriggerOn = TriggerCalls.OnTurnStart;
            berry.EquippedModifiers = [];
            berry.DoesPopUpInfo = true;
            berry.Conditions = [];
            berry.DoesActionOnTriggerAttached = false;
            berry.ConsumeOnTrigger = TriggerCalls.Count;
            berry.ConsumeOnUse = false;
            berry.ConsumeConditions = [];
            berry.ShopPrice = 5;
            berry.IsShopItem = false;
            berry.StartsLocked = true;
            berry.OnUnlockUsesTHE = true;
            berry.UsesSpecialUnlockText = false;
            berry.SpecialUnlockID = UILocID.None;
            berry.item._ItemTypeIDs = [];
            berry.item.AddBlueSkyUnlock("Coral_CH", "locked_strawberryfriend.png", "ach_strawberryfriend.png");

            PerformEffect_Item soul = new PerformEffect_Item("Salt_SoulDestabilizer_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ShiftCostsEffect>(), 1, Slots.Self)]);
            soul.Name = "Soul Destabilizer";
            soul.Flavour = "\"GONE!??\"";
            soul.Description = "Increase damage dealt by the amount of Pigment used in the ability.\nOn using an ability, shift this party member's Pigment costs.";
            soul.Icon = ResourceLoader.LoadSprite("item_souldestabilizer.png");
            soul.TriggerOn = TriggerCalls.OnAbilityUsed;
            soul.EquippedModifiers = [];
            soul.DoesPopUpInfo = true;
            soul.Conditions = [];
            soul.DoesActionOnTriggerAttached = false;
            soul.ConsumeOnTrigger = TriggerCalls.OnWillApplyDamage;
            soul.ConsumeOnUse = false;
            soul.ConsumeConditions = [ScriptableObject.CreateInstance<IncreaseDamageByPigmentUsedCondition>()];
            soul.ShopPrice = 5;
            soul.IsShopItem = true;
            soul.StartsLocked = true;
            soul.OnUnlockUsesTHE = true;
            soul.UsesSpecialUnlockText = false;
            soul.SpecialUnlockID = UILocID.None;
            soul.item._ItemTypeIDs = ["Magic"];
            soul.item.AddBlueSkyUnlock("Sulfuric_CH", "locked_souldestabilizer.png", "ach_souldestabilizer.png");

            PerformEffect_Item marker = new PerformEffect_Item("Salt_BlueMarker_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<DecreaseLuckyBluePercentageEffect>(), 10)]);
            marker.Name = "Blue Marker";
            marker.Flavour = "\"Delishits!\"";
            marker.Description = "Increase damage dealt by the amount of Blue Pigment in the tray.\nOn using an ability, decrease the Lucky Pigment percent chance by 10.";
            marker.Icon = ResourceLoader.LoadSprite("item_bluemarker.png");
            marker.TriggerOn = TriggerCalls.OnAbilityUsed;
            marker.EquippedModifiers = [];
            marker.DoesPopUpInfo = true;
            marker.Conditions = [];
            marker.DoesActionOnTriggerAttached = false;
            marker.ConsumeOnTrigger = TriggerCalls.OnWillApplyDamage;
            marker.ConsumeOnUse = false;
            marker.ConsumeConditions = [ScriptableObject.CreateInstance<DamagelMoreByBlueCondition>()];
            marker.ShopPrice = 6;
            marker.IsShopItem = false;
            marker.StartsLocked = true;
            marker.OnUnlockUsesTHE = true;
            marker.UsesSpecialUnlockText = false;
            marker.SpecialUnlockID = UILocID.None;
            marker.item._ItemTypeIDs = [];
            marker.item.AddBlueSkyUnlock("Vertus_CH", "locked_bluemarker.png", "ach_bluemarker.png");

            PerformEffect_Item siren = new PerformEffect_Item("Salt_AmbulanceSirens_SW", []);
            siren.Name = "Ambulance Sirens";
            siren.Flavour = "\"Noisy Noisy Noisy\"";
            siren.Description = "Increase healing dealt by 40% if this party member manually swapped this turn.";
            siren.Icon = ResourceLoader.LoadSprite("item_ambulancesirens.png");
            siren.TriggerOn = TriggerCalls.OnWillApplyHeal;
            siren.EquippedModifiers = [];
            siren.DoesPopUpInfo = false;
            siren.Conditions = [ScriptableObject.CreateInstance<IncreaseHealIfManuallyMovedCondition>()];
            siren.DoesActionOnTriggerAttached = false;
            siren.ConsumeOnTrigger = TriggerCalls.Count;
            siren.ConsumeOnUse = false;
            siren.ConsumeConditions = [];
            siren.ShopPrice = 4;
            siren.IsShopItem = true;
            siren.StartsLocked = true;
            siren.OnUnlockUsesTHE = true;
            siren.UsesSpecialUnlockText = false;
            siren.SpecialUnlockID = UILocID.None;
            siren.item._ItemTypeIDs = [];
            siren.item.AddBlueSkyUnlock("Reyes_CH", "locked_ambulancesirens.png", "ach_ambulancesirens.png");

            PerformEffect_Item recycler = new PerformEffect_Item("Salt_Recycler_TW", []);
            recycler.Name = "Recycler";
            recycler.Flavour = "\"Waste not, want not.\"";
            recycler.Description = "On using an ability, re-produce the Pigments used to perform the ability.";
            recycler.Icon = ResourceLoader.LoadSprite("item_recycler.png");
            recycler.TriggerOn = TriggerCalls.OnAbilityWillBeUsed;
            recycler.EquippedModifiers = [];
            recycler.DoesPopUpInfo = false;
            recycler.Conditions = [ScriptableObject.CreateInstance<RecyclerCondition>()];
            recycler.DoesActionOnTriggerAttached = false;
            recycler.ConsumeOnTrigger = TriggerCalls.Count;
            recycler.ConsumeOnUse = false;
            recycler.ConsumeConditions = [];
            recycler.ShopPrice = 3;
            recycler.IsShopItem = false;
            recycler.StartsLocked = true;
            recycler.OnUnlockUsesTHE = true;
            recycler.UsesSpecialUnlockText = false;
            recycler.SpecialUnlockID = UILocID.None;
            recycler.item._ItemTypeIDs = [];
            recycler.item.AddBlueSkyUnlock("Drubberslunger_CH", "locked_recycler.png", "ach_recycler.png");

            ApplyFoundStatusEffect partaking = ScriptableObject.CreateInstance<ApplyFoundStatusEffect>();
            partaking.useStatus = "Partaking_ID";
            PerformEffect_Item confession = new PerformEffect_Item("Salt_Confession_SW", [Effects.GenerateEffect(partaking, 1, Slots.Self)]);
            confession.Name = "Confession";
            confession.Flavour = "\"Have you done anything to feel guilty of?\"";
            confession.Description = "On being healed, gain 1 Partaking.";
            confession.Icon = ResourceLoader.LoadSprite("item_confession.png");
            confession.TriggerOn = TriggerCalls.OnWillBeHealed;
            confession.EquippedModifiers = [];
            confession.DoesPopUpInfo = true;
            confession.Conditions = [];
            confession.DoesActionOnTriggerAttached = false;
            confession.ConsumeOnTrigger = TriggerCalls.Count;
            confession.ConsumeOnUse = false;
            confession.ConsumeConditions = [];
            confession.ShopPrice = 5;
            confession.IsShopItem = true;
            confession.StartsLocked = true;
            confession.OnUnlockUsesTHE = true;
            confession.UsesSpecialUnlockText = false;
            confession.SpecialUnlockID = UILocID.None;
            confession.item._ItemTypeIDs = ["Heart"];
            confession.item.AddBlueSkyUnlock("Pavel&Perseus_CH", "locked_confession.png", "ach_confession.png");
        }
    }
}
