using BrutalAPI;
using BrutalAPI.Items;
using SaltEnemies_Reseasoned;
using SaltsEnemies_Reseasoneds;
using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace SaltsEnemies_Reseasoned
{
    public static class UnlocksTwo
    {
        public static void Add()
        {
            PerformEffect_Item agony = new PerformEffect_Item("Salt_AgonyToken_TW", [Effects.GenerateEffect(BasicEffects.GenPigment(Pigments.Red), 1, Slots.Self)]);
            agony.Name = "Agony Token";
            agony.Flavour = "\"The air is filled with pain.\"";
            agony.Description = "On dealing damage, generate 1 Red pigment.";
            agony.Icon = ResourceLoader.LoadSprite("item_agonytoken.png");
            agony.EquippedModifiers = [];
            agony.TriggerOn = TriggerCalls.OnDidApplyDamage;
            agony.DoesPopUpInfo = true;
            agony.Conditions = [];
            agony.DoesActionOnTriggerAttached = false;
            agony.ConsumeOnTrigger = TriggerCalls.Count;
            agony.ConsumeOnUse = false;
            agony.ConsumeConditions = [];
            agony.ShopPrice = 4;
            agony.IsShopItem = false;
            agony.StartsLocked = true;
            agony.OnUnlockUsesTHE = true;
            agony.UsesSpecialUnlockText = false;
            agony.SpecialUnlockID = UILocID.None;
            agony.item._ItemTypeIDs = [];
            agony.item.AddBlueSkyUnlock("Merced_CH", "locked_agonytoken.png", "ach_agonytoken.png");

            PerformEffect_Item fantasy = new PerformEffect_Item("Salt_FantasyToken_TW", [Effects.GenerateEffect(BasicEffects.GenPigment(Pigments.Purple), 1, Slots.Self)]);
            fantasy.Name = "Fantasy Token";
            fantasy.Flavour = "\"The desire to be anywhere but here.\"";
            fantasy.Description = "At the start of each turn generate 1 Purple pigment.";
            fantasy.Icon = ResourceLoader.LoadSprite("item_fantasytoken.png");
            fantasy.EquippedModifiers = [];
            fantasy.TriggerOn = TriggerCalls.OnTurnStart;
            fantasy.DoesPopUpInfo = true;
            fantasy.Conditions = [];
            fantasy.DoesActionOnTriggerAttached = false;
            fantasy.ConsumeOnTrigger = TriggerCalls.Count;
            fantasy.ConsumeOnUse = false;
            fantasy.ConsumeConditions = [];
            fantasy.ShopPrice = 4;
            fantasy.IsShopItem = false;
            fantasy.StartsLocked = true;
            fantasy.OnUnlockUsesTHE = true;
            fantasy.UsesSpecialUnlockText = false;
            fantasy.SpecialUnlockID = UILocID.None;
            fantasy.item._ItemTypeIDs = [];
            fantasy.item.AddBlueSkyUnlock("Cora_CH", "locked_fantasytoken.png", "ach_fantasytoken.png");

            PerformEffect_Item material = new PerformEffect_Item("Salt_MaterialToken_TW", [Effects.GenerateEffect(BasicEffects.GenPigment(Pigments.Yellow), 1, Slots.Self)]);
            material.Name = "Material Token";
            material.Flavour = "\"The world abstracts into its simplest components\"";
            material.Description = "On using an ability, generate 1 Yellow pigment.";
            material.Icon = ResourceLoader.LoadSprite("item_materialtoken.png");
            material.EquippedModifiers = [];
            material.TriggerOn = TriggerCalls.OnAbilityUsed;
            material.DoesPopUpInfo = true;
            material.Conditions = [];
            material.DoesActionOnTriggerAttached = false;
            material.ConsumeOnTrigger = TriggerCalls.Count;
            material.ConsumeOnUse = false;
            material.ConsumeConditions = [];
            material.ShopPrice = 4;
            material.IsShopItem = false;
            material.StartsLocked = true;
            material.OnUnlockUsesTHE = true;
            material.UsesSpecialUnlockText = false;
            material.SpecialUnlockID = UILocID.None;
            material.item._ItemTypeIDs = [];
            material.item.AddBlueSkyUnlock("Xet_CH", "locked_materialtoken.png", "ach_materialtoken.png");

            PerformEffect_Item death = new PerformEffect_Item("Salt_DeathToken_TW", [Effects.GenerateEffect(BasicEffects.GenPigment(Pigments.Blue), 1, Slots.Self)]);
            death.Name = "Death Token";
            death.Flavour = "\"When the dead are forgotten...\"";
            death.Description = "On taking any damage, generate 1 Blue pigment.";
            death.Icon = ResourceLoader.LoadSprite("item_deathtoken.png");
            death.EquippedModifiers = [];
            death.TriggerOn = TriggerCalls.OnDamaged;
            death.DoesPopUpInfo = true;
            death.Conditions = [];
            death.DoesActionOnTriggerAttached = false;
            death.ConsumeOnTrigger = TriggerCalls.Count;
            death.ConsumeOnUse = false;
            death.ConsumeConditions = [];
            death.ShopPrice = 4;
            death.IsShopItem = false;
            death.StartsLocked = true;
            death.OnUnlockUsesTHE = true;
            death.UsesSpecialUnlockText = false;
            death.SpecialUnlockID = UILocID.None;
            death.item._ItemTypeIDs = [];
            death.item.AddBlueSkyUnlock("Saline_CH", "locked_deathtoken.png", "ach_deathtoken.png");

            Basic_Item spores = new Basic_Item("Salt_BlueSpores_TW");
            spores.Name = "Blue Spores";
            spores.Flavour = "\"Glows in the night\"";
            spores.Description = "All damage dealt by this party member ignores Shield.";
            spores.Icon = ResourceLoader.LoadSprite("item_bluespores.png");
            spores.EquippedModifiers = [];
            spores.TriggerOn = TriggerCalls.Count;
            spores.DoesPopUpInfo = false;
            spores.Conditions = [];
            spores.DoesActionOnTriggerAttached = false;
            spores.ConsumeOnTrigger = TriggerCalls.Count;
            spores.ConsumeOnUse = false;
            spores.ConsumeConditions = [];
            spores.ShopPrice = 6;
            spores.IsShopItem = false;
            spores.StartsLocked = true;
            spores.OnUnlockUsesTHE = true;
            spores.UsesSpecialUnlockText = false;
            spores.SpecialUnlockID = UILocID.None;
            spores.item._ItemTypeIDs = ["PierceShield"];
            spores.item.AddBlueSkyUnlock("Didion_CH", "locked_bluespores.png", "ach_bluespores.png");

            PerformEffect_Item lens = new PerformEffect_Item("Salt_StalkingLens_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<CasterCloneItemEffect>(), 2), Effects.GenerateEffect(ScriptableObject.CreateInstance<ConsumeItemEffect>(), 1, Slots.Self)]);
            lens.Name = "Stalking Lens";
            lens.Flavour = "\"See through the dark\"";
            lens.Description = "All damage dealt by this party member ignores Shield.\nOn taking any damage, destroy this item and produce 2 copies of it.";
            lens.Icon = ResourceLoader.LoadSprite("item_stalkinglens.png");
            lens.EquippedModifiers = [];
            lens.TriggerOn = TriggerCalls.OnDamaged;
            lens.DoesPopUpInfo = false;
            lens.Conditions = [];
            lens.DoesActionOnTriggerAttached = false;
            lens.ConsumeOnTrigger = TriggerCalls.Count;
            lens.ConsumeOnUse = false;
            lens.ConsumeConditions = [];
            lens.ShopPrice = 6;
            lens.IsShopItem = true;
            lens.StartsLocked = true;
            lens.OnUnlockUsesTHE = true;
            lens.UsesSpecialUnlockText = false;
            lens.SpecialUnlockID = UILocID.None;
            lens.item._ItemTypeIDs = ["PierceShield"];
            lens.item.AddBlueSkyUnlock("Rose_CH", "locked_stalkinglens.png", "ach_stalkinglens.png");

            PerformEffect_Item poison = new PerformEffect_Item("Salt_PoisonVial_SW", []);
            poison.Name = "Poison Vial";
            poison.Flavour = "\"Unapetizing.\"";
            poison.Description = "Damaged targets gain 2 Acid.";
            poison.Icon = ResourceLoader.LoadSprite("item_poisonvial.png");
            poison.EquippedModifiers = [];
            poison.TriggerOn = AdvancedDamageTrigger.Dealt;
            poison.DoesPopUpInfo = false;
            poison.Conditions = [DamageTargetEffectsCondition.Create([Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyAcidEffect>(), 2, Slots.Self)], true)];
            poison.DoesActionOnTriggerAttached = false;
            poison.ConsumeOnTrigger = TriggerCalls.Count;
            poison.ConsumeOnUse = false;
            poison.ConsumeConditions = [];
            poison.ShopPrice = 3;
            poison.IsShopItem = true;
            poison.StartsLocked = true;
            poison.OnUnlockUsesTHE = true;
            poison.UsesSpecialUnlockText = false;
            poison.SpecialUnlockID = UILocID.None;
            poison.item._ItemTypeIDs = [];
            poison.item.AddBlueSkyUnlock("Prayer_CH", "locked_poisonvial.png", "ach_poisonvial.png");

            CopyAndSpawnCustomCharacterAnywhereEffect windle = ScriptableObject.CreateInstance<CopyAndSpawnCustomCharacterAnywhereEffect>();
            windle._characterCopy = "Windle_CH";
            windle._permanentSpawn = true;
            windle._extraModifiers = [];

            PerformEffect_Item key = new PerformEffect_Item("Salt_WindleKey_TW", [Effects.GenerateEffect(windle, 1)]);
            key.Name = "Windle Key";
            key.Flavour = "\"The key to my mechanical heart.\"";
            key.Description = "On taking any damage, spawn a Windle.";
            key.Icon = ResourceLoader.LoadSprite("item_windlekey.png");
            key.EquippedModifiers = [];
            key.TriggerOn = TriggerCalls.OnDamaged;
            key.DoesPopUpInfo = true;
            key.Conditions = [];
            key.DoesActionOnTriggerAttached = false;
            key.ConsumeOnTrigger = TriggerCalls.Count;
            key.ConsumeOnUse = false;
            key.ConsumeConditions = [];
            key.ShopPrice = 10;
            key.IsShopItem = false;
            key.StartsLocked = true;
            key.OnUnlockUsesTHE = true;
            key.UsesSpecialUnlockText = false;
            key.SpecialUnlockID = UILocID.None;
            key.item._ItemTypeIDs = [];
            key.item.AddBlueSkyUnlock("Kafka_CH", "locked_windlekey.png", "ach_windlekey.png");

            PerformEffect_Item ice = new PerformEffect_Item("Salt_BlackIce_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<PermenantApplyWaterEffect>(), 1, MultiTargetting.Create(Targetting.Everything(false), Targetting.Everything(true)))]);
            ice.Name = "Black Ice";
            ice.Flavour = "\"Frozen from somewhere\"";
            ice.Description = "At the start of combat, permenantly apply Deep Water to all positions.";
            ice.Icon = ResourceLoader.LoadSprite("item_blackice.png");
            ice.EquippedModifiers = [];
            ice.TriggerOn = TriggerCalls.OnCombatStart;
            ice.DoesPopUpInfo = true;
            ice.Conditions = [];
            ice.DoesActionOnTriggerAttached = false;
            ice.ConsumeOnTrigger = TriggerCalls.Count;
            ice.ConsumeConditions = [];
            ice.ConsumeOnUse = false;
            ice.ShopPrice = 0;
            ice.IsShopItem = false;
            ice.StartsLocked = true;
            ice.OnUnlockUsesTHE = true;
            ice.UsesSpecialUnlockText = false;
            ice.SpecialUnlockID = UILocID.None;
            ice.item._ItemTypeIDs = [];
            ice.item.AddBlueSkyUnlock("Bodybag_CH", "locked_blackice.png", "ach_blackice.png");

            MultiPerformEffectItem challenger = new MultiPerformEffectItem("Salt_Challenger_SW", []);
            challenger.Name = "Challenger";
            challenger.Flavour = "\"1986\"";
            challenger.Description = "Deal 60% more healing.\nGain 2 Slip on manually moving.";
            challenger.Icon = ResourceLoader.LoadSprite("item_challenger.png");
            challenger.TriggerOn = TriggerCalls.OnWillApplyHeal;
            challenger.EquippedModifiers = [];
            challenger.DoesPopUpInfo = false;
            challenger.Conditions = [ItemExtensions.Heal(60, true)];
            challenger.DoesActionOnTriggerAttached = false;
            challenger.ConsumeOnTrigger = TriggerCalls.Count;
            challenger.ConsumeOnUse = false;
            challenger.ConsumeConditions = [];
            challenger.ShopPrice = 6;
            challenger.IsShopItem = true;
            challenger.StartsLocked = true;
            challenger.OnUnlockUsesTHE = true;
            challenger.UsesSpecialUnlockText = false;
            challenger.SpecialUnlockID = UILocID.None;
            challenger.item._ItemTypeIDs = [];
            challenger.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplySlipSlotEffect>(), 2, Slots.Self)], [TriggerCalls.OnSwapTo], []));
            challenger.item.AddBlueSkyUnlock("Hangman_CH", "locked_challenger.png", "ach_challenger.png");

            PerformEffect_Item plug = new PerformEffect_Item("Salt_ThePlug_SW", []);
            plug.Name = "The Plug";
            plug.Flavour = "\"Hole In The Wall\"";
            plug.Description = "Damaged targets gain 10 Pale.";
            plug.Icon = ResourceLoader.LoadSprite("item_theplug.png");
            plug.EquippedModifiers = [];
            plug.TriggerOn = AdvancedDamageTrigger.Dealt;
            plug.DoesPopUpInfo = false;
            plug.Conditions = [DamageTargetEffectsCondition.Create([Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPaleByTenEffect>(), 1, Slots.Self)], true)];
            plug.DoesActionOnTriggerAttached = false;
            plug.ConsumeOnTrigger = TriggerCalls.Count;
            plug.ConsumeOnUse = false;
            plug.ConsumeConditions = [];
            plug.ShopPrice = 5;
            plug.IsShopItem = true;
            plug.StartsLocked = true;
            plug.OnUnlockUsesTHE = false;
            plug.UsesSpecialUnlockText = false;
            plug.SpecialUnlockID = UILocID.None;
            plug.item._ItemTypeIDs = [];
            plug.item.AddBlueSkyUnlock("Saturn_CH", "locked_theplug.png", "ach_theplug.png");

            PerformEffect_Item scope = new PerformEffect_Item("Salt_HexedScope_TW", []);
            scope.Name = "Hexed Scope";
            scope.Flavour = "\"Sin of Sloth\"";
            scope.Description = "Deal 15% less damage.\nDeal 50% more damage instead if this is the first ability used this turn.";
            scope.Icon = ResourceLoader.LoadSprite("item_hexedscope.png");
            scope.EquippedModifiers = [];
            scope.TriggerOn = TriggerCalls.OnWillApplyDamage;
            scope.DoesPopUpInfo = false;
            scope.Conditions = [ScriptableObject.CreateInstance<HexedScopeCondition>()];
            scope.DoesActionOnTriggerAttached = false;
            scope.ConsumeOnTrigger = TriggerCalls.Count;
            scope.ConsumeOnUse = false;
            scope.ConsumeConditions = [];
            scope.ShopPrice = 5;
            scope.IsShopItem = false;
            scope.StartsLocked = true;
            scope.OnUnlockUsesTHE = true;
            scope.UsesSpecialUnlockText = false;
            scope.SpecialUnlockID = UILocID.None;
            scope.item._ItemTypeIDs = [];
            scope.item.AddBlueSkyUnlock("Hare_CH", "locked_hexedscope.png", "ach_hexedscope.png");

            MultiPerformEffectItem logicsink = new MultiPerformEffectItem("Salt_LogicSink_SW", [Effects.GenerateEffect(BasicEffects.GoRight, 1, Slots.Self)]);
            logicsink.Name = "Logic Sink";
            logicsink.Flavour = "\"Spiral down your own mind\"";
            logicsink.Description = "Deal 20% more damage.\nOn moving left, move right.";
            logicsink.Icon = ResourceLoader.LoadSprite("item_logicsink.png");
            logicsink.EquippedModifiers = [];
            logicsink.TriggerOn = TriggerCalls.OnMoved;
            logicsink.DoesPopUpInfo = true;
            logicsink.Conditions = [SwapDirectionCondition.Create(false)];
            logicsink.DoesActionOnTriggerAttached = false;
            logicsink.ConsumeOnTrigger = TriggerCalls.Count;
            logicsink.ConsumeOnUse = false;
            logicsink.ConsumeConditions = [];
            logicsink.ShopPrice = 4;
            logicsink.IsShopItem = true;
            logicsink.StartsLocked = true;
            logicsink.OnUnlockUsesTHE = true;
            logicsink.UsesSpecialUnlockText = false;
            logicsink.SpecialUnlockID = UILocID.None;
            logicsink.item._ItemTypeIDs = [];
            logicsink.AddEffectTrigger(new EffectTrigger([], [TriggerCalls.OnWillApplyDamage], [ItemExtensions.Damage(20, true)], false));
            logicsink.item.AddBlueSkyUnlock("Moon_CH", "locked_logicsink.png", "ach_logicsink.png");

            MultiPerformEffectItem mercycheck = new MultiPerformEffectItem("Salt_MercyCheck_SW", [Effects.GenerateEffect(BasicEffects.GoLeft, 1, Slots.Self)]);
            mercycheck.Name = "Mercy Check";
            mercycheck.Flavour = "\"Pray for everything and receive nothing.\"";
            mercycheck.Description = "At the end of each turn heal 0-4 health.\nOn moving right, move left.";
            mercycheck.Icon = ResourceLoader.LoadSprite("item_mercycheck.png");
            mercycheck.EquippedModifiers = [];
            mercycheck.TriggerOn = TriggerCalls.OnMoved;
            mercycheck.DoesPopUpInfo = true;
            mercycheck.Conditions = [SwapDirectionCondition.Create(true)];
            mercycheck.DoesActionOnTriggerAttached = false;
            mercycheck.ConsumeOnTrigger = TriggerCalls.Count;
            mercycheck.ConsumeOnUse = false;
            mercycheck.ConsumeConditions = [];
            mercycheck.ShopPrice = 4;
            mercycheck.IsShopItem = true;
            mercycheck.StartsLocked = true;
            mercycheck.OnUnlockUsesTHE = true;
            mercycheck.UsesSpecialUnlockText = false;
            mercycheck.SpecialUnlockID = UILocID.None;
            mercycheck.item._ItemTypeIDs = [];
            mercycheck.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(ScriptableObject.CreateInstance<RandomHealBetweenPreviousAndEntryEffect>(), 4, Slots.Self)], [TriggerCalls.OnTurnFinished], []));
            mercycheck.item.AddBlueSkyUnlock("Clerk_CH", "locked_mercycheck.png", "ach_mercycheck.png");

            PerformEffect_Item time = new PerformEffect_Item("Salt_MarchOfTime_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<DamageByTurnsEffect>(), 1, Slots.Front)]);
            time.Name = "March of Time";
            time.Flavour = "\"Two by Two\"";
            time.Description = "At the end of each turn, deal damage to the Opposing enemy equal to the amount of turns passed.";
            time.Icon = ResourceLoader.LoadSprite("item_marchoftime.png");
            time.EquippedModifiers = [];
            time.TriggerOn = TriggerCalls.OnTurnFinished;
            time.DoesPopUpInfo = true;
            time.Conditions = [];
            time.DoesActionOnTriggerAttached = false;
            time.ConsumeOnTrigger = TriggerCalls.Count;
            time.ConsumeOnUse = false;
            time.ConsumeConditions = [];
            time.ShopPrice = 3;
            time.IsShopItem = false;
            time.StartsLocked = true;
            time.OnUnlockUsesTHE = true;
            time.UsesSpecialUnlockText = false;
            time.SpecialUnlockID = UILocID.None;
            time.item._ItemTypeIDs = [];
            time.item.AddBlueSkyUnlock("Esther_CH", "locked_marchoftime.png", "ach_marchoftime.png");

            PerformEffect_Item copy = new PerformEffect_Item("Salt_Replicator_TW", []);
            copy.Name = "Replicator";
            copy.Flavour = "\"No, you're copying me!\"";
            copy.Description = "On manually using an ability, use it again.\nAdds the used ability to the Opposing enemy's moveset.";
            copy.Icon = ResourceLoader.LoadSprite("item_replicator.png");
            copy.EquippedModifiers = [];
            copy.TriggerOn = TriggerCalls.OnAbilityWillBeUsed;
            copy.DoesPopUpInfo = false;
            copy.Conditions = [ScriptableObject.CreateInstance<ReplicatorCondition>()];
            copy.DoesActionOnTriggerAttached = false;
            copy.ConsumeOnTrigger = TriggerCalls.Count;
            copy.ConsumeOnUse = false;
            copy.ConsumeConditions = [];
            copy.ShopPrice = 7;
            copy.IsShopItem = false;
            copy.StartsLocked = true;
            copy.OnUnlockUsesTHE = true;
            copy.UsesSpecialUnlockText = false;
            copy.SpecialUnlockID = UILocID.None;
            copy.item._ItemTypeIDs = [];
            copy.item.AddBlueSkyUnlock("Rhys_CH", "locked_replicator.png", "ach_replicator.png");

            MultiPerformEffectItem roger = new MultiPerformEffectItem("Salt_UnloadedRogers_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<SwapToSidesEffect>(), 1, Slots.Self)]);
            roger.Name = "Unloaded Roger's";
            roger.Flavour = "\"It's not actually a gun, it's just a rock.\"";
            roger.Description = "Deal 50% more damage.\nOn any party member manually moving, move Left or Right.";
            roger.Icon = ResourceLoader.LoadSprite("item_unloadedrogers.png");
            roger.EquippedModifiers = [];
            roger.TriggerOn = JitteryHandler.Ally;
            roger.DoesPopUpInfo = true;
            roger.Conditions = [];
            roger.DoesActionOnTriggerAttached = false;
            roger.ConsumeOnTrigger = TriggerCalls.Count;
            roger.ConsumeOnUse = false;
            roger.ConsumeConditions = [];
            roger.ShopPrice = 4;
            roger.IsShopItem = true;
            roger.StartsLocked = true;
            roger.OnUnlockUsesTHE = true;
            roger.UsesSpecialUnlockText = false;
            roger.SpecialUnlockID = UILocID.None;
            roger.item._ItemTypeIDs = [];
            roger.AddEffectTrigger(new EffectTrigger([], [TriggerCalls.OnWillApplyDamage], [ItemExtensions.Damage(50, true)], false));
            roger.item.AddBlueSkyUnlock("Wtmiyr_CH", "locked_unloadedrogers.png", "ach_unloadedrogers.png");

            MultiPerformEffectItem sound = new MultiPerformEffectItem("Salt_SoundGun_SW", []);
            sound.Name = "Sound Gun";
            sound.Flavour = "\"Noisy.\"";
            sound.Description = "Damage dealt spreads indirectly left and right.\nApply Focused to directly damaged targets.";
            sound.Icon = ResourceLoader.LoadSprite("item_soundgun.png");
            sound.TriggerOn = CascadingDamageItemHandler.Call;
            sound.EquippedModifiers = [];
            sound.DoesPopUpInfo = false;
            sound.Conditions = [BooleanSetterCondition.Create(true, true, false)];
            sound.DoesActionOnTriggerAttached = false;
            sound.ConsumeOnTrigger = TriggerCalls.Count;
            sound.ConsumeOnUse = false;
            sound.ConsumeConditions = [];
            sound.ShopPrice = 6;
            sound.IsShopItem = true;
            sound.StartsLocked = true;
            sound.OnUnlockUsesTHE = true;
            sound.UsesSpecialUnlockText = false;
            sound.SpecialUnlockID = UILocID.None;
            sound.item._ItemTypeIDs = [];
            sound.AddEffectTrigger(new EffectTrigger([], [AdvancedDamageTrigger.Dealt], [DamageTargetEffectsCondition.Create([Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyFocusedEffect>(), 1, Slots.Self)], true)], false));
            sound.item.AddBlueSkyUnlock("Joy_CH", "locked_soundgun.png", "ach_soundgun.png");

            PerformEffect_Item sea = new PerformEffect_Item("Salt_SeaGlass_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<RerollTimelineEffect>())]);
            sea.Name = "Sea Glass";
            sea.Flavour = "\"Product of industry and nature\"";
            sea.Description = "On moving, reroll the entire timeline.";
            sea.Icon = ResourceLoader.LoadSprite("item_seaglass.png");
            sea.EquippedModifiers = [];
            sea.TriggerOn = TriggerCalls.OnMoved;
            sea.DoesPopUpInfo = true;
            sea.Conditions = [];
            sea.DoesActionOnTriggerAttached = false;
            sea.ConsumeOnTrigger = TriggerCalls.Count;
            sea.ConsumeOnUse = false;
            sea.ConsumeConditions = [];
            sea.ShopPrice = 3;
            sea.IsShopItem = true;
            sea.StartsLocked = true;
            sea.OnUnlockUsesTHE = true;
            sea.UsesSpecialUnlockText = false;
            sea.SpecialUnlockID = UILocID.None;
            sea.item._ItemTypeIDs = [];
            sea.item.AddBlueSkyUnlock("Patch_CH", "locked_seaglass.png", "ach_seaglass.png");

            CopyAndSpawnCustomCharacterAnywhereEffect spawn_six = ScriptableObject.CreateInstance<CopyAndSpawnCustomCharacterAnywhereEffect>();
            spawn_six._characterCopy = "Six_CH";
            spawn_six._permanentSpawn = true;
            spawn_six._extraModifiers = [];

            PerformEffect_Item six = new PerformEffect_Item("Salt_Six_EW", [Effects.GenerateEffect(spawn_six, 1, Slots.Self)]);
            six.Name = "Six";
            six.Flavour = "\"Hi I'm Six!\"";
            six.Description = "On combat start, destroy this item and spawn Six.";
            six.Icon = ResourceLoader.LoadSprite("item_six.png");
            six.TriggerOn = TriggerCalls.OnCombatStart;
            six.EquippedModifiers = [];
            six.DoesPopUpInfo = true;
            six.Conditions = [];
            six.DoesActionOnTriggerAttached = false;
            six.ConsumeOnTrigger = TriggerCalls.Count;
            six.ConsumeOnUse = true;
            six.ConsumeConditions = [];
            six.ShopPrice = 7;
            six.IsShopItem = false;
            six.StartsLocked = true;
            six.OnUnlockUsesTHE = true;
            six.UsesSpecialUnlockText = true;
            six.SpecialUnlockID = UILocID.ItemFishLocationLabel;
            six.item._ItemTypeIDs = [];
            six.item.AddBlueSkyUnlock("Six_CH", "locked_six.png", "ach_six.png", 1);

            Ability inbetweener = new Ability("Inbetweener", "Inbetweener_A");
            inbetweener.Description = "Deal 5-10 damage to the Opposing enemy.\nAttempt to split the Opposing enemy in two.";
            inbetweener.AbilitySprite = ResourceLoader.LoadSprite("ability_inbetweener.png");
            inbetweener.Cost = [Pigments.Red, Pigments.Yellow];
            inbetweener.Effects = [
                Effects.GenerateEffect(BasicEffects.Empty, 5),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<RandomDamageBetweenPreviousAndEntryEffect>(), 10, Slots.Front),
                Effects.GenerateEffect(SubActionEffect.Create(
                        [Effects.GenerateEffect(ScriptableObject.CreateInstance<SplitInTwoEffect>(), 1, Slots.Self, ScriptableObject.CreateInstance<HasCasterSizeEffectCondition>())]
                    ), 1, Slots.Front)
                ];
            inbetweener.AddIntentsToTarget(Slots.Front, ["Damage_7_10", "Misc"]);
            inbetweener.Visuals = Visuals.Mitosis;
            inbetweener.AnimationTarget = Slots.Front;

            ExtraAbility_Wearable_SMS add_btw = ScriptableObject.CreateInstance<ExtraAbility_Wearable_SMS>();
            add_btw._extraAbility = inbetweener.GenerateCharacterAbility(true);

            ((Passives.Construct as Connection_PerformEffectPassiveAbility).connectionEffects[1].effect as CasterAddRandomExtraAbilityEffect)._extraData.Add(add_btw);

            Basic_Item lost = new Basic_Item("Salt_LostKnow_TW");
            lost.Name = "Lost Know";
            lost.Flavour = "\"From where?\"";
            lost.Description = "Adds the extra ability \"Inbetweener,\" a tactical move that splits the Opposing enemy in two.";
            lost.Icon = ResourceLoader.LoadSprite("item_lostknow.png");
            lost.TriggerOn = TriggerCalls.Count;
            lost.EquippedModifiers = [add_btw];
            lost.DoesPopUpInfo = false;
            lost.Conditions = [];
            lost.DoesActionOnTriggerAttached = false;
            lost.ConsumeOnTrigger = TriggerCalls.Count;
            lost.ConsumeOnUse = false;
            lost.ConsumeConditions = [];
            lost.ShopPrice = 5;
            lost.IsShopItem = false;
            lost.StartsLocked = true;
            lost.OnUnlockUsesTHE = true;
            lost.UsesSpecialUnlockText = false;
            lost.SpecialUnlockID = UILocID.None;
            lost.item._ItemTypeIDs = [];
            lost.item.AddBlueSkyUnlock("Rotcore_CH", "locked_lostknow.png", "ach_lostknow.png");

            Ability panic = new Ability("Salt_Panic_A");
            panic.Name = "Panic";
            panic.Description = "Apply 2 Slip to all party member positions.\nRefresh this party member's ability usage.";
            panic.AbilitySprite = ResourceLoader.LoadSprite("ability_panic.png");
            panic.Cost = [Pigments.Yellow];
            panic.Effects = [
                Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplySlipSlotEffect>(), 2, Targetting.Everything(true)),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<RefreshAbilityUseEffect>(), 1, Slots.Self)];
            panic.AddIntentsToTarget(Targetting.Everything(true), [Slip.Intent]);
            panic.AddIntentsToTarget(Slots.Self, [IntentType_GameIDs.Misc_Additional.ToString()]);
            panic.Visuals = null;
            panic.AnimationTarget = Slots.Self;

            ExtraAbility_Wearable_SMS add_panic = ScriptableObject.CreateInstance<ExtraAbility_Wearable_SMS>();
            add_panic._extraAbility = panic.GenerateCharacterAbility(true);

            ((Passives.Construct as Connection_PerformEffectPassiveAbility).connectionEffects[1].effect as CasterAddRandomExtraAbilityEffect)._extraData.Add(add_panic);

            PerformEffect_Item stop = new PerformEffect_Item("Salt_SecondStop_TW", []);
            stop.Name = "2nd Stop";
            stop.Flavour = "\"Between Here and Nowhere\"";
            stop.Description = "While in Slip, damage dealt spreads indirectly Left and Right.\nAdds the extra ability \"Panic\" which can be used to apply Slip to the party members' side.";
            stop.Icon = ResourceLoader.LoadSprite("item_secondstop.png");
            stop.TriggerOn = CascadingDamageItemHandler.Call;
            stop.EquippedModifiers = [add_panic];
            stop.DoesPopUpInfo = false;
            stop.Conditions = [ScriptableObject.CreateInstance<BooleanValueInSlipSetter>()];
            stop.DoesActionOnTriggerAttached = false;
            stop.ConsumeOnTrigger = TriggerCalls.Count;
            stop.ConsumeOnUse = false;
            stop.ConsumeConditions = [];
            stop.ShopPrice = 5;
            stop.IsShopItem = false;
            stop.StartsLocked = true;
            stop.OnUnlockUsesTHE = true;
            stop.SpecialUnlockID = UILocID.None;
            stop.item._ItemTypeIDs = [];
            stop.item.AddBlueSkyUnlock("Catten_CH", "locked_secondstop.png", "ach_secondstop.png");

            Ability outpour = new Ability("Salt_Outpour_A");
            outpour.Name = "Outpour";
            outpour.Description = "Inflict 2 Slip on all enemy positions.\n50% chance to refresh this party member's ability usage.";
            outpour.AbilitySprite = ResourceLoader.LoadSprite("ability_outpour.png");
            outpour.Cost = [Pigments.Grey, Pigments.Grey];
            outpour.Effects = [
                Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplySlipSlotEffect>(), 2, Targetting.Everything(false)),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<RefreshAbilityUseEffect>(), 1, Slots.Self, Effects.ChanceCondition(50))
                ];
            outpour.AddIntentsToTarget(Targetting.Everything(false), [Slip.Intent]);
            outpour.AddIntentsToTarget(Slots.Self, ["Misc"]);
            outpour.Visuals = Visuals.Puke;
            outpour.AnimationTarget = Targetting.Everything(false);

            ExtraAbility_Wearable_SMS add_pour = ScriptableObject.CreateInstance<ExtraAbility_Wearable_SMS>();
            add_pour._extraAbility = outpour.GenerateCharacterAbility(true);

            ((Passives.Construct as Connection_PerformEffectPassiveAbility).connectionEffects[1].effect as CasterAddRandomExtraAbilityEffect)._extraData.Add(add_pour);

            Basic_Item bucket = new Basic_Item("Salt_Bucket_TW");
            bucket.Name = "Bucket";
            bucket.Flavour = "\"This... is a bucket.\"";
            bucket.Description = "Adds the extra ability \"Outpour,\" a cheap, easily repeatable ability that inflicts Slip to all enemies.";
            bucket.Icon = ResourceLoader.LoadSprite("item_bucket.png");
            bucket.TriggerOn = TriggerCalls.Count;
            bucket.EquippedModifiers = [add_pour];
            bucket.DoesPopUpInfo = false;
            bucket.Conditions = [];
            bucket.DoesActionOnTriggerAttached = false;
            bucket.ConsumeOnTrigger = TriggerCalls.Count;
            bucket.ConsumeOnUse = false;
            bucket.ConsumeConditions = [];
            bucket.ShopPrice = 4;
            bucket.IsShopItem = false;
            bucket.StartsLocked = true;
            bucket.OnUnlockUsesTHE = true;
            bucket.SpecialUnlockID = UILocID.None;
            bucket.item._ItemTypeIDs = [];
            bucket.item.AddBlueSkyUnlock("Sunflower_CH", "locked_bucket.png", "ach_bucket.png");

            SpawnEnemyByStringNameEffect haunt = ScriptableObject.CreateInstance<SpawnEnemyByStringNameEffect>();
            haunt._spawnTypeID = "Spawn_Basic";
            haunt.enemyName = "Hauntling_EN";

            PerformEffect_Item that = new PerformEffect_Item("Salt_That_SW", []);
            that.Name = "THAT.";
            that.Flavour = "\"Over there... Can you see it?\"";
            that.Description = "On dealing damage to a target, apply Spotlight to them.\nSomething else may spawn.";
            that.Icon = ResourceLoader.LoadSprite("item_that.png");
            that.EquippedModifiers = [];
            that.TriggerOn = AdvancedDamageTrigger.Dealt;
            that.DoesPopUpInfo = false;
            that.Conditions = [DamageTargetEffectsCondition.Create([Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplySpotlightEffect>(), 1, Slots.Self), Effects.GenerateEffect(haunt, 1, Slots.Self)], true)];
            that.DoesActionOnTriggerAttached = false;
            that.ConsumeOnTrigger = TriggerCalls.Count;
            that.ConsumeOnUse = false;
            that.ConsumeConditions = [];
            that.ShopPrice = 9;
            that.IsShopItem = true;
            that.StartsLocked = true;
            that.OnUnlockUsesTHE = false;
            that.UsesSpecialUnlockText = false;
            that.SpecialUnlockID = UILocID.None;
            that.item._ItemTypeIDs = [];
            that.item.AddBlueSkyUnlock("Snail_CH", "locked_that.png", "ach_that.png");

            AddPassiveWithDisplayEffect add_automated = ScriptableObject.CreateInstance<AddPassiveWithDisplayEffect>();
            PerformEffectPassiveAbility auto = ScriptableObject.CreateInstance<PerformEffectPassiveAbility>();
            auto._passiveName = "Automated";
            auto.passiveIcon = ResourceLoader.LoadSprite("WindlePassive.png");
            auto.m_PassiveID = "Automated_PA";
            auto._enemyDescription = "idk";
            auto._characterDescription = "At the end of each turn, if this party member has not manually performed an ability, perform a random ability.";
            auto.doesPassiveTriggerInformationPanel = true; auto._triggerOn = new TriggerCalls[] { TriggerCalls.OnTurnFinished };
            ManuallyActionDoneEffectorCondition m = ScriptableObject.CreateInstance<ManuallyActionDoneEffectorCondition>();
            m._resultShouldBe = false;
            m._justCheckAbility = true;
            auto.conditions = new EffectorConditionSO[] { m };
            auto.effects = Effects.GenerateEffect(ScriptableObject.CreateInstance<PerformRandomAbilityEffect>(), 1, Slots.Self).SelfArray();
            add_automated.passive = auto;
            BaseCombatTargettingSO right = Targeting.GenerateSlotTarget(new int[] { 1, -4 }, false);

            PerformEffect_Item eggs = new PerformEffect_Item("Salt_BrainEggsAndHam_SW", [Effects.GenerateEffect(add_automated, 1, right)]);
            eggs.Name = "Brain Eggs and Ham";
            eggs.Flavour = "\"Worms Worms Worms!\"";
            eggs.Description = "At the start of each turn, add \"Automated\" as a passive to the Right ally.\nThis item assumes the grid loops around.";
            eggs.Icon = ResourceLoader.LoadSprite("item_braineggsandham.png");
            eggs.EquippedModifiers = [];
            eggs.TriggerOn = TriggerCalls.OnTurnStart;
            eggs.DoesPopUpInfo = true;
            eggs.Conditions = [];
            eggs.DoesActionOnTriggerAttached = false;
            eggs.ConsumeOnTrigger = TriggerCalls.Count;
            eggs.ConsumeOnUse = false;
            eggs.ConsumeConditions = [];
            eggs.ShopPrice = 8;
            eggs.IsShopItem = true;
            eggs.StartsLocked = true;
            eggs.OnUnlockUsesTHE = true;
            eggs.UsesSpecialUnlockText = false;
            eggs.SpecialUnlockID = UILocID.None;
            eggs.item._ItemTypeIDs = ["Meat"];
            eggs.item.AddBlueSkyUnlock("Lich_CH", "locked_braineggsandham.png", "ach_braineggsandham.png");

            MultiPerformEffectItem forever = new MultiPerformEffectItem("Salt_Forever_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ResurrectOnRandomSlotEffect>(), 1, Targetting.Everything(true))]);
            forever.Name = "Forever";
            forever.Flavour = "\"I need you.\"";
            forever.Description = "On kill, attempt to resurrect a random party member at 1 health.\nOn taking any damage, something else appears.\nThis item is destroyed on death.";
            forever.Icon = ResourceLoader.LoadSprite("item_forever.png");
            forever.EquippedModifiers = [];
            forever.TriggerOn = TriggerCalls.OnKill;
            forever.DoesPopUpInfo = true;
            forever.Conditions = [];
            forever.DoesActionOnTriggerAttached = false;
            forever.ConsumeOnTrigger = TriggerCalls.OnDeath;
            forever.ConsumeOnUse = false;
            forever.ConsumeConditions = [];
            forever.ShopPrice = 10;
            forever.IsShopItem = false;
            forever.StartsLocked = true;
            forever.OnUnlockUsesTHE = false;
            forever.UsesSpecialUnlockText = false;
            forever.SpecialUnlockID = UILocID.None;
            forever.item._ItemTypeIDs = ["Magic"];
            forever.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(haunt, 1)], [TriggerCalls.OnDamaged], []));
            forever.item.AddBlueSkyUnlock("Izide_CH", "locked_forever.png", "ach_forever.png");

            PerformEffect_Item ring = new PerformEffect_Item("Salt_TheRing_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPaleByTenEffect>(), 1, Slots.Front)]);
            ring.Name = "The Ring";
            ring.Flavour = "\"For whom?\"";
            ring.Description = "On moving, inflict 10 Pale on the Opposing enemy.";
            ring.Icon = ResourceLoader.LoadSprite("item_ring.png");
            ring.TriggerOn = TriggerCalls.OnMoved;
            ring.EquippedModifiers = [];
            ring.DoesPopUpInfo = true;
            ring.Conditions = [];
            ring.DoesActionOnTriggerAttached = false;
            ring.ConsumeOnTrigger = TriggerCalls.Count;
            ring.ConsumeOnUse = false;
            ring.ConsumeConditions = [];
            ring.ShopPrice = 6;
            ring.IsShopItem = false;
            ring.StartsLocked = true;
            ring.OnUnlockUsesTHE = false;
            ring.UsesSpecialUnlockText = false;
            ring.SpecialUnlockID = UILocID.None;
            ring.item._ItemTypeIDs = ["Magic"];
            ring.item.AddBlueSkyUnlock("Saea_CH", "locked_ring.png", "ach_ring.png");

            PerformEffect_Item sanddial = new PerformEffect_Item("Salt_SandDial_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<AddTurnTargetToTimelineEffect>(), 1, Slots.Front)]);
            sanddial.Name = "Sand Dial";
            sanddial.Flavour = "\"A constant battle against the eventual decay into chaos\"";
            sanddial.Description = "Damage dealt spreads indirectly without fallof.\nOn moving, give the Opposing enemy another action.";
            sanddial.Icon = ResourceLoader.LoadSprite("item_sanddial.png");
            sanddial.TriggerOn = TriggerCalls.OnMoved;
            sanddial.EquippedModifiers = [];
            sanddial.DoesPopUpInfo = true;
            sanddial.Conditions = [];
            sanddial.DoesActionOnTriggerAttached = false;
            sanddial.ConsumeOnTrigger = CascadingDamageItemHandler.Call;
            sanddial.ConsumeOnUse = false;
            sanddial.ConsumeConditions = [ScriptableObject.CreateInstance<NoFallofCascadeCondition>()];
            sanddial.ShopPrice = 6;
            sanddial.IsShopItem = false;
            sanddial.StartsLocked = true;
            sanddial.OnUnlockUsesTHE = true;
            sanddial.UsesSpecialUnlockText = false;
            sanddial.SpecialUnlockID = UILocID.None;
            sanddial.Item._ItemTypeIDs = [];
            sanddial.item.AddBlueSkyUnlock("Alpha_CH", "locked_sanddial.png", "ach_sanddial.png");

            CopyAndSpawnCustomCharacterAnywhereEffect spawn_fribble = ScriptableObject.CreateInstance<CopyAndSpawnCustomCharacterAnywhereEffect>();
            spawn_fribble._characterCopy = "Fribble_CH";
            spawn_fribble._permanentSpawn = true;
            spawn_fribble._rank = 0;
            spawn_fribble._extraModifiers = [];

            PerformEffect_Item fribble = new PerformEffect_Item("Salt_Fribble_SW", [Effects.GenerateEffect(spawn_fribble, 1)]);
            fribble.Name = "Fribble";
            fribble.Flavour = "\"Hi my name is: Fribble\"";
            fribble.Description = "At the start of combat, spawn a permenant level 1 party member.\nThis item is consumed on use.";
            fribble.Icon = ResourceLoader.LoadSprite("item_fribble.png");
            fribble.TriggerOn = TriggerCalls.OnCombatStart;
            fribble.EquippedModifiers = [];
            fribble.DoesPopUpInfo = true;
            fribble.Conditions = [];
            fribble.DoesActionOnTriggerAttached = false;
            fribble.ConsumeOnTrigger = TriggerCalls.Count;
            fribble.ConsumeOnUse = true;
            fribble.ConsumeConditions = [];
            fribble.ShopPrice = 7;
            fribble.IsShopItem = true;
            fribble.StartsLocked = true;
            fribble.OnUnlockUsesTHE = false;
            fribble.UsesSpecialUnlockText = false;
            fribble.SpecialUnlockID = UILocID.None;
            fribble.item._ItemTypeIDs = [];
            fribble.item.AddBlueSkyUnlock("Qualia_CH", "locked_fribble.png", "ach_fribble.png");

            RankChange_Wearable_SMS up1 = ScriptableObject.CreateInstance<RankChange_Wearable_SMS>();
            up1._rankAdditive = 1;

            MultiPerformEffectItem seams = new MultiPerformEffectItem("Salt_Seams_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplySlipSlotEffect>(), 3, Slots.Self)]);
            seams.Name = "Seams";
            seams.Flavour = "\"Slice of Life\"";
            seams.Description = "This party member is 1 level higher than usual.\nAt the start and end of each turn, gain 3 Slip.";
            seams.Icon = ResourceLoader.LoadSprite("item_seams.png");
            seams.TriggerOn = TriggerCalls.OnTurnStart;
            seams.EquippedModifiers = [up1];
            seams.DoesPopUpInfo = true;
            seams.Conditions = [];
            seams.DoesActionOnTriggerAttached = false;
            seams.ConsumeOnTrigger = TriggerCalls.Count;
            seams.ConsumeOnUse = false;
            seams.ConsumeConditions = [];
            seams.ShopPrice = 6;
            seams.IsShopItem = true;
            seams.StartsLocked = true;
            seams.OnUnlockUsesTHE = false;
            seams.UsesSpecialUnlockText = false;
            seams.SpecialUnlockID = UILocID.None;
            seams.item._ItemTypeIDs = ["Fabric"];
            seams.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplySlipSlotEffect>(), 3, Slots.Self)], [TriggerCalls.OnTurnFinished], []));
            seams.item.AddBlueSkyUnlock("Secret_CH", "locked_seams.png", "ach_seams.png");
        }
    }
}
