using BrutalAPI;
using BrutalAPI.Items;
using SaltEnemies_Reseasoned;
using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace SaltsEnemies_Reseasoned
{
    public static class UnlocksTwo
    {
        public static void Add()
        {
            MultiPerformEffectItem friend = new MultiPerformEffectItem("Salt_FriendshipBriefcase_SW", []);
            friend.Name = "Friendship Briefcase";
            friend.Flavour = "\"Friends everywhere you look!\"";
            friend.Description = "Deal 2 additional damage and healing.\n20% chance to be destroyed on dealing damage.";
            friend.Icon = ResourceLoader.LoadSprite("item_friendshipbriefcase.png");
            friend.EquippedModifiers = [];
            friend.TriggerOn = TriggerCalls.OnWillApplyHeal;
            friend.DoesPopUpInfo = true;
            friend.Conditions = [ItemExtensions.Heal(2, true, false, false)];
            friend.DoesActionOnTriggerAttached = false;
            friend.ConsumeOnTrigger = TriggerCalls.OnDidApplyDamage;
            friend.ConsumeOnUse = false;
            friend.ConsumeConditions = [ItemExtensions.Chance(20)];
            friend.ShopPrice = 5;
            friend.IsShopItem = true;
            friend.StartsLocked = true;
            friend.OnUnlockUsesTHE = true;
            friend.UsesSpecialUnlockText = false;
            friend.SpecialUnlockID = UILocID.None;
            friend.item._ItemTypeIDs = [];
            friend.AddEffectTrigger(new EffectTrigger([], [TriggerCalls.OnWillApplyDamage], [ItemExtensions.Damage(2, true, false)], false));
            friend.item.AddBlueSkyUnlock("LongLiver_CH", "locked_friendshipbriefcase.png", "ach_friendshipbriefcase.png");

            PerformEffect_Item war = new PerformEffect_Item("Salt_AbstractWar_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyDeterminedEffect>(), 1, Slots.Self)]);
            war.Name = "Abstract War";
            war.Flavour = "\"Depictions of Violence\"";
            war.Description = "On any party member receiving direct damage, gain 1 Determined.";
            war.Icon = ResourceLoader.LoadSprite("item_abstractwar.png");
            war.EquippedModifiers = [];
            war.TriggerOn = AllyTriggersHandler.AllyDirectDamaged;
            war.DoesPopUpInfo = true;
            war.Conditions = [];
            war.DoesActionOnTriggerAttached = false;
            war.ConsumeOnTrigger = TriggerCalls.Count;
            war.ConsumeOnUse = false;
            war.ConsumeConditions = [];
            war.ShopPrice = 6;
            war.IsShopItem = true;
            war.StartsLocked = true;
            war.OnUnlockUsesTHE = true;
            war.UsesSpecialUnlockText = false;
            war.SpecialUnlockID = UILocID.None;
            war.item._ItemTypeIDs = [];
            war.item.AddBlueSkyUnlock("Anton_CH", "locked_abstractwar.png", "ach_abstractwar.png");

            PerformEffect_Item photo = new PerformEffect_Item("Salt_RedPhoto_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPowerEffect>(), 1, Slots.Self)]);
            photo.Name = "Red Photo";
            photo.Flavour = "\"Abstract Violence\"";
            photo.Description = "On any party member receiving direct damage, gain 1 Power.";
            photo.Icon = ResourceLoader.LoadSprite("item_redphoto.png");
            photo.EquippedModifiers = [];
            photo.TriggerOn = AllyTriggersHandler.AllyDirectDamaged;
            photo.DoesPopUpInfo = true;
            photo.Conditions = [];
            photo.DoesActionOnTriggerAttached = false;
            photo.ConsumeOnTrigger = TriggerCalls.Count;
            photo.ConsumeOnUse = false;
            photo.ConsumeConditions = [];
            photo.ShopPrice = 6;
            photo.IsShopItem = true;
            photo.StartsLocked = true;
            photo.OnUnlockUsesTHE = true;
            photo.UsesSpecialUnlockText = false;
            photo.SpecialUnlockID = UILocID.None;
            photo.item._ItemTypeIDs = [];
            photo.item.AddBlueSkyUnlock("Thype_CH", "locked_redphoto.png", "ach_redphoto.png");

            ApplyFoundStatusEffect wildcard = ScriptableObject.CreateInstance<ApplyFoundStatusEffect>();
            wildcard.useStatus = "WildCard_ID";

            MultiPerformEffectItem entropy = new MultiPerformEffectItem("Salt_EntropicAnalysis_TW", [Effects.GenerateEffect(wildcard, 2, Slots.Self)]);
            entropy.Name = "Entropic Analysis";
            entropy.Flavour = "\"Are you truly ready to pay the debt this machine has incurred?\"";
            entropy.Description = "At the start of each turn, gain 2 Wild Card.\nAt the end of each turn, give the Opposing enemy 2 Wild Card.";
            entropy.Icon = ResourceLoader.LoadSprite("item_entropicanalysis.png");
            entropy.EquippedModifiers = [];
            entropy.TriggerOn = TriggerCalls.OnTurnStart;
            entropy.DoesPopUpInfo = true;
            entropy.Conditions = [];
            entropy.DoesActionOnTriggerAttached = false;
            entropy.ConsumeOnTrigger = TriggerCalls.Count;
            entropy.ConsumeOnUse = false;
            entropy.ConsumeConditions = [];
            entropy.ShopPrice = 4;
            entropy.IsShopItem = false;
            entropy.StartsLocked = true;
            entropy.OnUnlockUsesTHE = true;
            entropy.UsesSpecialUnlockText = false;
            entropy.SpecialUnlockID = UILocID.None;
            entropy.item._ItemTypeIDs = [];
            entropy.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(wildcard, 2, Slots.Front)], [TriggerCalls.OnTurnFinished], []));
            entropy.item.AddBlueSkyUnlock("Andy_CH", "locked_entropicanalysis.png", "ach_entropicanalysis.png");

            PerformEffect_Item death = new PerformEffect_Item("Salt_DeathCertificate_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<FullHealEffect>(), 1, Slots.Self), Effects.GenerateEffect(ScriptableObject.CreateInstance<FleeTargetEffect>(), 1, Slots.Self)]);
            death.Name = "Death Certificate";
            death.Flavour = "\"Who's in that grave!?\"";
            death.Description = "On taking any damage, fully heal this party member and instantly flee.";
            death.Icon = ResourceLoader.LoadSprite("item_deathcertificate.png");
            death.EquippedModifiers = [];
            death.TriggerOn = TriggerCalls.OnDamaged;
            death.DoesPopUpInfo = true;
            death.Conditions = [];
            death.DoesActionOnTriggerAttached = false;
            death.ConsumeOnTrigger = TriggerCalls.Count;
            death.ConsumeOnUse = false;
            death.ConsumeConditions = [];
            death.ShopPrice = 4;
            death.IsShopItem = true;
            death.StartsLocked = true;
            death.OnUnlockUsesTHE = true;
            death.UsesSpecialUnlockText = false;
            death.SpecialUnlockID = UILocID.None;
            death.item._ItemTypeIDs = [];
            death.item.AddBlueSkyUnlock("SmokeStacks_CH", "locked_deathcertificate.png", "ach_deathcertificate.png");

            MultiPerformEffectItem logicsink = new MultiPerformEffectItem("Salt_LogicSink_SW", [Effects.GenerateEffect(BasicEffects.GoRight, 1, Slots.Self)]);
            logicsink.Name = "Logic Sink";
            logicsink.Flavour = "\"Spiral down your own mind\"";
            logicsink.Description = "Deal 20% more damage.\nOn moving left, move right.";
            logicsink.Icon = ResourceLoader.LoadSprite("item_logicsink.png");
            logicsink.EquippedModifiers = [];
            logicsink.TriggerOn = TriggerCalls.OnMoved;
            logicsink.DoesPopUpInfo = true;
            logicsink.Conditions = [SwapDirectionCondition.Create(false)];
            logicsink.DoesActionOnTriggerAttached = false;
            logicsink.ConsumeOnTrigger = TriggerCalls.Count;
            logicsink.ConsumeOnUse = false;
            logicsink.ConsumeConditions = [];
            logicsink.ShopPrice = 4;
            logicsink.IsShopItem = true;
            logicsink.StartsLocked = true;
            logicsink.OnUnlockUsesTHE = true;
            logicsink.UsesSpecialUnlockText = false;
            logicsink.SpecialUnlockID = UILocID.None;
            logicsink.item._ItemTypeIDs = [];
            logicsink.AddEffectTrigger(new EffectTrigger([], [TriggerCalls.OnWillApplyDamage], [ItemExtensions.Damage(20, true)], false));
            logicsink.item.AddBlueSkyUnlock("Moon_CH", "locked_logicsink.png", "ach_logicsink.png");

            MultiPerformEffectItem mercycheck = new MultiPerformEffectItem("Salt_MercyCheck_SW", [Effects.GenerateEffect(BasicEffects.GoLeft, 1, Slots.Self)]);
            mercycheck.Name = "Mercy Check";
            mercycheck.Flavour = "\"Pray for everything and receive nothing.\"";
            mercycheck.Description = "At the end of each turn heal 0-4 health.\nOn moving right, move left.";
            mercycheck.Icon = ResourceLoader.LoadSprite("item_mercycheck.png");
            mercycheck.EquippedModifiers = [];
            mercycheck.TriggerOn = TriggerCalls.OnMoved;
            mercycheck.DoesPopUpInfo = true;
            mercycheck.Conditions = [SwapDirectionCondition.Create(true)];
            mercycheck.DoesActionOnTriggerAttached = false;
            mercycheck.ConsumeOnTrigger = TriggerCalls.Count;
            mercycheck.ConsumeOnUse = false;
            mercycheck.ConsumeConditions = [];
            mercycheck.ShopPrice = 4;
            mercycheck.IsShopItem = true;
            mercycheck.StartsLocked = true;
            mercycheck.OnUnlockUsesTHE = true;
            mercycheck.UsesSpecialUnlockText = false;
            mercycheck.SpecialUnlockID = UILocID.None;
            mercycheck.item._ItemTypeIDs = [];
            mercycheck.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(ScriptableObject.CreateInstance<RandomHealBetweenPreviousAndEntryEffect>(), 4, Slots.Self)], [TriggerCalls.OnTurnFinished], []));
            mercycheck.item.AddBlueSkyUnlock("Clerk_CH", "locked_mercycheck.png", "ach_mercycheck.png");

            PerformEffect_Item flower = new PerformEffect_Item("Salt_LittleFlower_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyDeterminedEffect>(), 3, Slots.Self)]);
            flower.Name = "Little Flower";
            flower.Flavour = "\"So delicate yet full of hope...\"";
            flower.Description = "At the start of combat gain 3 Determined.\nThis item is destroyed on death.";
            flower.Icon = ResourceLoader.LoadSprite("item_littleflower.png");
            flower.EquippedModifiers = [];
            flower.TriggerOn = TriggerCalls.OnCombatStart;
            flower.DoesPopUpInfo = true;
            flower.Conditions = [];
            flower.DoesActionOnTriggerAttached = false;
            flower.ConsumeOnTrigger = TriggerCalls.OnDeath;
            flower.ConsumeOnUse = false;
            flower.ConsumeConditions = [];
            flower.ShopPrice = 3;
            flower.IsShopItem = false;
            flower.StartsLocked = true;
            flower.OnUnlockUsesTHE = true;
            flower.UsesSpecialUnlockText = false;
            flower.SpecialUnlockID = UILocID.None;
            flower.item._ItemTypeIDs = ["Magic"];
            flower.item.AddBlueSkyUnlock("Splig_CH", "locked_littleflower.png", "ach_littleflower.png");

            PerformEffect_Item hammer = new PerformEffect_Item("Salt_GlassHammer_SW", []);
            hammer.Name = "Glass Hammer";
            hammer.Flavour = "\"Decorative power.\"";
            hammer.Description = "Damage dealt spreads indirectly Left and Right.\nThis item is destroyed upon being directly damaged.";
            hammer.Icon = ResourceLoader.LoadSprite("item_glasshammer.png");
            hammer.EquippedModifiers = [];
            hammer.TriggerOn = CascadingDamageItemHandler.Call;
            hammer.DoesPopUpInfo = true;
            hammer.Conditions = [BooleanSetterCondition.Create(true, true, false)];
            hammer.DoesActionOnTriggerAttached = false;
            hammer.ConsumeOnTrigger = TriggerCalls.OnDirectDamaged;
            hammer.ConsumeOnUse = false;
            hammer.ConsumeConditions = [];
            hammer.ShopPrice = 9;
            hammer.IsShopItem = true;
            hammer.StartsLocked = true;
            hammer.OnUnlockUsesTHE = true;
            hammer.UsesSpecialUnlockText = false;
            hammer.SpecialUnlockID = UILocID.None;
            hammer.item._ItemTypeIDs = [];
            hammer.item.AddBlueSkyUnlock("Lilian_CH", "locked_glasshammer.png", "ach_glasshammer.png");

            Ability cat = new Ability("Cataclysm", "Salt_Cataclysm_A");
            cat.Description = "Deal 15 damage to all enemies.";
            cat.Cost = [Pigments.Purple, Pigments.Purple, Pigments.Purple];
            cat.Rarity = Rarity.GetCustomRarity("rarity5");
            cat.AbilitySprite = ResourceLoader.LoadSprite("ability_cataclysm.png");
            cat.Effects = [Effects.GenerateEffect(ScriptableObject.CreateInstance<DamageEffect>(), 15, Targeting.Unit_AllOpponents)];
            cat.AddIntentsToTarget(Targeting.Unit_AllOpponents, ["Damage_11_15"]);
            cat.Visuals = CustomVisuals.GetVisuals("Salt/StarBomb");
            cat.AnimationTarget = Targetting.Everything(false);

            ExtraAbility_Wearable_SMS add_cat = ScriptableObject.CreateInstance<ExtraAbility_Wearable_SMS>();
            add_cat._extraAbility = cat.GenerateCharacterAbility(true);

            PerformEffect_Item lunar = new PerformEffect_Item("Salt_LunarCharm_SW", []);
            lunar.Name = "Lunar Charm";
            lunar.Flavour = "\"Skyfall\"";
            lunar.Description = "Adds the extra ability \"Cataclysm\", an expensive but powerful mass damaging move.\nThis item is destroyed upon taking any damage.";
            lunar.Icon = ResourceLoader.LoadSprite("item_lunarcharm.png");
            lunar.EquippedModifiers = [add_cat];
            lunar.TriggerOn = TriggerCalls.Count;
            lunar.DoesPopUpInfo = true;
            lunar.Conditions = [];
            lunar.DoesActionOnTriggerAttached = false;
            lunar.ConsumeOnTrigger = TriggerCalls.OnDamaged;
            lunar.ConsumeOnUse = false;
            lunar.ConsumeConditions = [];
            lunar.ShopPrice = 4;
            lunar.IsShopItem = true;
            lunar.StartsLocked = true;
            lunar.OnUnlockUsesTHE = true;
            lunar.UsesSpecialUnlockText = false;
            lunar.SpecialUnlockID = UILocID.None;
            lunar.item._ItemTypeIDs = ["Magic"];
            lunar.item.AddBlueSkyUnlock("Bimini_CH", "locked_lunarcharm.png", "ach_lunarcharm.png");

        }
    }
}
