using BrutalAPI.Items;
using BrutalAPI;
using SaltEnemies_Reseasoned;
using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace SaltsEnemies_Reseasoned
{
    public static class UnlocksSeven
    {
        public static void Add()
        {
            PerformEffect_Item poison = new PerformEffect_Item("Salt_PoisonVial_SW", []);
            poison.Name = "Poison Vial";
            poison.Flavour = "\"Unapetizing.\"";
            poison.Description = "Damaged targets gain 2 Acid.";
            poison.Icon = ResourceLoader.LoadSprite("item_poisonvial.png");
            poison.EquippedModifiers = [];
            poison.TriggerOn = AdvancedDamageTrigger.Dealt;
            poison.DoesPopUpInfo = false;
            poison.Conditions = [DamageTargetEffectsCondition.Create([Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyAcidEffect>(), 2, Slots.Self)], true)];
            poison.DoesActionOnTriggerAttached = false;
            poison.ConsumeOnTrigger = TriggerCalls.Count;
            poison.ConsumeOnUse = false;
            poison.ConsumeConditions = [];
            poison.ShopPrice = 3;
            poison.IsShopItem = true;
            poison.StartsLocked = true;
            poison.OnUnlockUsesTHE = false;
            poison.UsesSpecialUnlockText = false;
            poison.SpecialUnlockID = UILocID.None;
            poison.item._ItemTypeIDs = [];
            poison.item.AddBlueSkyUnlock("Prayer_CH", "locked_poisonvial.png", "ach_poisonvial.png");

            PerformEffect_Item sea = new PerformEffect_Item("Salt_SeaGlass_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<RerollTimelineEffect>())]);
            sea.Name = "Sea Glass";
            sea.Flavour = "\"Product of industry and nature\"";
            sea.Description = "On moving, reroll the entire timeline.";
            sea.Icon = ResourceLoader.LoadSprite("item_seaglass.png");
            sea.EquippedModifiers = [];
            sea.TriggerOn = TriggerCalls.OnMoved;
            sea.DoesPopUpInfo = true;
            sea.Conditions = [];
            sea.DoesActionOnTriggerAttached = false;
            sea.ConsumeOnTrigger = TriggerCalls.Count;
            sea.ConsumeOnUse = false;
            sea.ConsumeConditions = [];
            sea.ShopPrice = 3;
            sea.IsShopItem = true;
            sea.StartsLocked = true;
            sea.OnUnlockUsesTHE = true;
            sea.UsesSpecialUnlockText = false;
            sea.SpecialUnlockID = UILocID.None;
            sea.item._ItemTypeIDs = [];
            sea.item.AddBlueSkyUnlock("Patch_CH", "locked_seaglass.png", "ach_seaglass.png");

            MultiPerformEffectItem stick = new MultiPerformEffectItem("Salt_ReallyBigStick_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyScarsEffect>(), 2, Slots.Self)]);
            stick.Name = "Really Big Stick";
            stick.Flavour = "\"Dammit! Splinters!\"";
            stick.Description = "Deal 2 additional damage.\nGain 2 Scars on kill.";
            stick.Icon = ResourceLoader.LoadSprite("item_reallybigstick.png");
            stick.EquippedModifiers = [];
            stick.TriggerOn = TriggerCalls.OnKill;
            stick.DoesPopUpInfo = true;
            stick.Conditions = [];
            stick.DoesActionOnTriggerAttached = false;
            stick.ConsumeOnTrigger = TriggerCalls.Count;
            stick.ConsumeOnUse = false;
            stick.ConsumeConditions = [];
            stick.ShopPrice = 8;
            stick.IsShopItem = true;
            stick.StartsLocked = true;
            stick.OnUnlockUsesTHE = true;
            stick.UsesSpecialUnlockText = false;
            stick.SpecialUnlockID = UILocID.None;
            stick.item._ItemTypeIDs = [];
            stick.AddEffectTrigger(new EffectTrigger([], [TriggerCalls.OnWillApplyDamage], [ItemExtensions.Damage(2, true, false)], false));
            stick.item.AddBlueSkyUnlock("Raphe_CH", "locked_reallybigstick.png", "ach_reallybigstick.png");

            PerformEffect_Item ice = new PerformEffect_Item("Salt_BlackIce_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<PermenantApplyWaterEffect>(), 1, MultiTargetting.Create(Targetting.Everything(false), Targetting.Everything(true)))]);
            ice.Name = "Black Ice";
            ice.Flavour = "\"Frozen from somewhere\"";
            ice.Description = "At the start of combat, permenantly apply Deep Water to all positions.";
            ice.Icon = ResourceLoader.LoadSprite("item_blackice.png");
            ice.EquippedModifiers = [];
            ice.TriggerOn = TriggerCalls.OnCombatStart;
            ice.DoesPopUpInfo = true;
            ice.Conditions = [];
            ice.DoesActionOnTriggerAttached = false;
            ice.ConsumeOnTrigger = TriggerCalls.Count;
            ice.ConsumeConditions = [];
            ice.ConsumeOnUse = false;
            ice.ShopPrice = 0;
            ice.IsShopItem = false;
            ice.StartsLocked = true;
            ice.OnUnlockUsesTHE = true;
            ice.UsesSpecialUnlockText = false;
            ice.SpecialUnlockID = UILocID.None;
            ice.item._ItemTypeIDs = [];
            ice.item.AddBlueSkyUnlock("Bodybag_CH", "locked_blackice.png", "ach_blackice.png");

            PerformEffect_Item tears = new PerformEffect_Item("Salt_TearDrops_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<DecreaseLuckyBluePercentageEffect>(), 3, Slots.Self)]);
            tears.Name = "Tear Drops";
            tears.Flavour = "\"Fake it till you make it\"";
            tears.Description = "Increase healing dealt by the amount of Blue pigment in the pigment tray.\nReduce the Lucky Pigment chance percentage by 3 on using an ability.";
            tears.Icon = ResourceLoader.LoadSprite("item_teardrops.png");
            tears.EquippedModifiers = [];
            tears.TriggerOn = TriggerCalls.OnAbilityUsed;
            tears.DoesPopUpInfo = true;
            tears.Conditions = [];
            tears.DoesActionOnTriggerAttached = false;
            tears.ConsumeOnTrigger = TriggerCalls.OnWillApplyHeal;
            tears.ConsumeOnUse = false;
            tears.ConsumeConditions = [ScriptableObject.CreateInstance<HealMoreByBlueCondition>()];
            tears.ShopPrice = 4;
            tears.IsShopItem = true;
            tears.StartsLocked = true;
            tears.OnUnlockUsesTHE = true;
            tears.UsesSpecialUnlockText = false;
            tears.SpecialUnlockID = UILocID.None;
            tears.item._ItemTypeIDs = [];
            tears.item.AddBlueSkyUnlock("Carpy_CH", "locked_teardrops.png", "ach_teardrops.png");

            PerformEffect_Item symbiote = new PerformEffect_Item("Salt_SymbioteInjection_TW", []);
            symbiote.Name = "Symbiote Injection";
            symbiote.Flavour = "\"Are you sure I need this shot?\"";
            symbiote.Description = "On being directly damaged, gain an equal amount of Growth.";
            symbiote.Icon = ResourceLoader.LoadSprite("item_symbioteinjection.png");
            symbiote.EquippedModifiers = [];
            symbiote.TriggerOn = TriggerCalls.OnDirectDamaged;
            symbiote.DoesPopUpInfo = false;
            symbiote.Conditions = [ScriptableObject.CreateInstance<SymbioteCondition>()];
            symbiote.DoesActionOnTriggerAttached = false;
            symbiote.ConsumeOnTrigger = TriggerCalls.Count;
            symbiote.ConsumeOnUse = false;
            symbiote.ConsumeConditions = [];
            symbiote.ShopPrice = 6;
            symbiote.IsShopItem = false;
            symbiote.StartsLocked = true;
            symbiote.OnUnlockUsesTHE = true;
            symbiote.UsesSpecialUnlockText = false;
            symbiote.SpecialUnlockID = UILocID.None;
            symbiote.item._ItemTypeIDs = [];
            symbiote.item.AddBlueSkyUnlock("Thern_CH", "locked_symbioteinjection.png", "ach_symbioteinjection.png");

            PerformEffect_Item spurs = new PerformEffect_Item("Salt_HorseSpurs_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<RestoreSwapUseEffect>(), 1, Slots.Self)]);
            spurs.Name = "Horse Spurs";
            spurs.Flavour = "\"You are the horse.\"";
            spurs.Description = "On receiving any damage, restore this party member's movement usage.";
            spurs.Icon = ResourceLoader.LoadSprite("item_horsespurs.png");
            spurs.EquippedModifiers = [];
            spurs.TriggerOn = TriggerCalls.OnDamaged;
            spurs.DoesPopUpInfo = false;
            spurs.Conditions = [];
            spurs.DoesActionOnTriggerAttached = false;
            spurs.ConsumeOnTrigger = TriggerCalls.Count;
            spurs.ConsumeOnUse = false;
            spurs.ConsumeConditions = [];
            spurs.ShopPrice = 2;
            spurs.IsShopItem = true;
            spurs.StartsLocked = true;
            spurs.OnUnlockUsesTHE = true;
            spurs.UsesSpecialUnlockText = false;
            spurs.SpecialUnlockID = UILocID.None;
            spurs.item._ItemTypeIDs = ["Fabric"];
            spurs.item.AddBlueSkyUnlock("Wiwi_CH", "locked_horsespurs.png", "ach_horsespurs.png");
        }
    }
}
