using BrutalAPI;
using BrutalAPI.Items;
using SaltEnemies_Reseasoned;
using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace SaltsEnemies_Reseasoned
{
    public static class UnlocksSix
    {
        public static void Add()
        {
            CopyAndSpawnCustomCharacterAnywhereEffect spawn_six = ScriptableObject.CreateInstance<CopyAndSpawnCustomCharacterAnywhereEffect>();
            spawn_six._characterCopy = "Six_CH";
            spawn_six._permanentSpawn = true;

            PerformEffect_Item six = new PerformEffect_Item("Salt_Six_EW", [Effects.GenerateEffect(spawn_six, 1, Slots.Self)]);
            six.Name = "Six";
            six.Flavour = "\"Hi I'm Six!\"";
            six.Description = "On combat start, destroy this item and spawn Six.";
            six.Icon = ResourceLoader.LoadSprite("item_six.png");
            six.TriggerOn = TriggerCalls.OnCombatStart;
            six.EquippedModifiers = [];
            six.DoesPopUpInfo = true;
            six.Conditions = [];
            six.DoesActionOnTriggerAttached = false;
            six.ConsumeOnTrigger = TriggerCalls.Count;
            six.ConsumeOnUse = true;
            six.ConsumeConditions = [];
            six.ShopPrice = 7;
            six.IsShopItem = false;
            six.StartsLocked = true;
            six.OnUnlockUsesTHE = true;
            six.UsesSpecialUnlockText = true;
            six.SpecialUnlockID = UILocID.ItemFishLocationLabel;
            six.item._ItemTypeIDs = [];
            six.item.AddBlueSkyUnlock("Six_CH", "locked_six.png", "ach_six.png", 1);

            MultiPerformEffectItem manual = new MultiPerformEffectItem("Salt_DissectionManual_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<GainPlayerCurrencyEffect>(), 5, Slots.Self)]);
            manual.Name = "Dissection Manual";
            manual.Flavour = "\"Follow precise instructions.\"";
            manual.Description = "On getting a kill, gain 5 coins.\nOn using an ability, lose 2 coins.";
            manual.Icon = ResourceLoader.LoadSprite("item_dissectionmanual.png");
            manual.TriggerOn = TriggerCalls.OnKill;
            manual.EquippedModifiers = [];
            manual.DoesPopUpInfo = true;
            manual.Conditions = [];
            manual.DoesActionOnTriggerAttached = false;
            manual.ConsumeOnTrigger = TriggerCalls.Count;
            manual.ConsumeOnUse = false;
            manual.ConsumeConditions = [];
            manual.ShopPrice = 5;
            manual.IsShopItem = true;
            manual.StartsLocked = true;
            manual.OnUnlockUsesTHE = true;
            manual.UsesSpecialUnlockText = false;
            manual.SpecialUnlockID = UILocID.None;
            manual.item._ItemTypeIDs = [];
            manual.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(ScriptableObject.CreateInstance<LosePlayerCurrencyEffect>(), 2, Slots.Self)], [TriggerCalls.OnAbilityWillBeUsed], []));
            manual.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(ScriptableObject.CreateInstance<ShowPlayerCurrencyEffect>(), 1, Slots.Self)], [TriggerCalls.OnCombatStart], [], false));
            manual.item.AddBlueSkyUnlock("Leviat_CH", "locked_dissectionmanual.png", "ach_dissectionmanual.png");

            ApplyFoundFieldEffect spikes = ScriptableObject.CreateInstance<ApplyFoundFieldEffect>();
            spikes.useField = "Spikes_ID";

            PerformEffect_Item dmz = new PerformEffect_Item("Salt_DMZ_TW", [Effects.GenerateEffect(spikes, 1, Slots.Self), Effects.GenerateEffect(spikes, 4, Slots.Front)]);
            dmz.Name = "Demilitarized Zone";
            dmz.Flavour = "\"The whole thing.\"";
            dmz.Description = "On manually moving, gain 1 Spikes and inflict 4 Spikes on the Opposing position.";
            dmz.Icon = ResourceLoader.LoadSprite("item_dmz.png");
            dmz.TriggerOn = TriggerCalls.OnSwapTo;
            dmz.EquippedModifiers = [];
            dmz.DoesPopUpInfo = true;
            dmz.Conditions = [];
            dmz.DoesActionOnTriggerAttached = false;
            dmz.ConsumeOnTrigger = TriggerCalls.Count;
            dmz.ConsumeOnUse = false;
            dmz.ConsumeConditions = [];
            dmz.ShopPrice = 3;
            dmz.IsShopItem = false;
            dmz.StartsLocked = true;
            dmz.OnUnlockUsesTHE = true;
            dmz.UsesSpecialUnlockText = false;
            dmz.SpecialUnlockID = UILocID.None;
            dmz.item._ItemTypeIDs = [];
            dmz.item.AddBlueSkyUnlock("Bingo_CH", "locked_dmz.png", "ach_dmz.png");

            PerformEffect_Item blood = new PerformEffect_Item("Salt_BloodSword_SW", []);
            blood.Name = "Blood Sword";
            blood.Flavour = "\"Hurts a lot to use.\"";
            blood.Description = "Deal 25% more damage while at full health.\nThis item is destroyed on death.";
            blood.Icon = ResourceLoader.LoadSprite("item_bloodsword.png");
            blood.TriggerOn = TriggerCalls.OnWillApplyDamage;
            blood.EquippedModifiers = [];
            blood.DoesPopUpInfo = false;
            blood.Conditions = [ScriptableObject.CreateInstance<FullHealthEffectorCondition>(), ItemExtensions.Damage(25, true)];
            blood.DoesActionOnTriggerAttached = false;
            blood.ConsumeOnTrigger = TriggerCalls.OnDeath;
            blood.ConsumeOnUse = false;
            blood.ConsumeConditions = [];
            blood.ShopPrice = 4;
            blood.IsShopItem = true;
            blood.StartsLocked = true;
            blood.OnUnlockUsesTHE = true;
            blood.UsesSpecialUnlockText = false;
            blood.SpecialUnlockID = UILocID.None;
            blood.item._ItemTypeIDs = ["Knife", "Meat"];
            blood.item.AddBlueSkyUnlock("Otto_CH", "locked_bloodsword.png", "ach_bloodsword.png");

            PerformEffect_Item ring = new PerformEffect_Item("Salt_TheRing_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPaleByTenEffect>(), 1, Slots.Front)]);
            ring.Name = "The Ring";
            ring.Flavour = "\"For whom?\"";
            ring.Description = "On moving, inflict 10 Pale on the Opposing enemy.";
            ring.Icon = ResourceLoader.LoadSprite("item_ring.png");
            ring.TriggerOn = TriggerCalls.OnMoved;
            ring.EquippedModifiers = [];
            ring.DoesPopUpInfo = true;
            ring.Conditions = [];
            ring.DoesActionOnTriggerAttached = false;
            ring.ConsumeOnTrigger = TriggerCalls.Count;
            ring.ConsumeOnUse = false;
            ring.ConsumeConditions = [];
            ring.ShopPrice = 6;
            ring.IsShopItem = false;
            ring.StartsLocked = true;
            ring.OnUnlockUsesTHE = false;
            ring.UsesSpecialUnlockText = false;
            ring.SpecialUnlockID = UILocID.None;
            ring.item._ItemTypeIDs = ["Magic"];
            ring.item.AddBlueSkyUnlock("Saea_CH", "locked_ring.png", "ach_ring.png");

            MultiPerformEffectItem heart = new MultiPerformEffectItem("Salt_SecondHeart_SW", []);
            heart.Name = "Second Heart";
            heart.Flavour = "\"As a precaution\"";
            heart.Description = "Receive 100% more healing.\nOn being directly damaged, gain Cursed.";
            heart.Icon = ResourceLoader.LoadSprite("item_secondheart.png");
            heart.TriggerOn = TriggerCalls.OnBeingHealed;
            heart.EquippedModifiers = [];
            heart.DoesPopUpInfo = false;
            heart.Conditions = [HealingReceivedCondition.Create(100, true)];
            heart.DoesActionOnTriggerAttached = false;
            heart.ConsumeOnTrigger = TriggerCalls.Count;
            heart.ConsumeOnUse = false;
            heart.ConsumeConditions = [];
            heart.ShopPrice = 6;
            heart.IsShopItem = true;
            heart.StartsLocked = true;
            heart.OnUnlockUsesTHE = true;
            heart.UsesSpecialUnlockText = false;
            heart.SpecialUnlockID = UILocID.None;
            heart.item._ItemTypeIDs = ["Heart", "Meat"];
            heart.AddEffectTrigger(new EffectTrigger([Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyCursedEffect>(), 1, Slots.Self)], [TriggerCalls.OnDirectDamaged], []));
            heart.item.AddBlueSkyUnlock("Mazur_CH", "locked_secondheart.png", "ach_secondheart.png");

            PerformEffect_Item mosquito = new PerformEffect_Item("Salt_BigMosquito_SW", []);
            mosquito.Name = "Big Mosquito";
            mosquito.Flavour = "\"It's very big.\"";
            mosquito.Description = "Heal for damage dealt.\nDestroy this item on dealing over 21 damage in 1 combat.";
            mosquito.Icon = ResourceLoader.LoadSprite("item_bigmosquito.png");
            mosquito.TriggerOn = TriggerCalls.OnDidApplyDamage;
            mosquito.EquippedModifiers = [];
            mosquito.DoesPopUpInfo = false;
            mosquito.Conditions = [ScriptableObject.CreateInstance<BigMosquitoCondition>()];
            mosquito.DoesActionOnTriggerAttached = false;
            mosquito.ConsumeOnTrigger = TriggerCalls.Count;
            mosquito.ConsumeOnUse = false;
            mosquito.ConsumeConditions = [];
            mosquito.ShopPrice = 6;
            mosquito.IsShopItem = true;
            mosquito.StartsLocked = true;
            mosquito.OnUnlockUsesTHE = true;
            mosquito.UsesSpecialUnlockText = false;
            mosquito.SpecialUnlockID = UILocID.None;
            mosquito.item._ItemTypeIDs = [];
            mosquito.item.AddBlueSkyUnlock("Jarova_CH", "locked_bigmosquito.png", "ach_bigmosquito.png");

            PerformEffect_Item eye = new PerformEffect_Item("Salt_OpalescentEye_SW", []);
            eye.Name = "Opalescent Eye";
            eye.Flavour = "\"Look away!\"";
            eye.Description = "Heal 60% more to non-Purple targets.";
            eye.Icon = ResourceLoader.LoadSprite("item_opalescenteye.png");
            eye.TriggerOn = TriggerCalls.OnWillApplyHeal;
            eye.EquippedModifiers = [];
            eye.DoesPopUpInfo = false;
            eye.Conditions = [ScriptableObject.CreateInstance<HealMoreNonPurpleCondition>()];
            eye.DoesActionOnTriggerAttached = false;
            eye.ConsumeOnTrigger = TriggerCalls.Count;
            eye.ConsumeOnUse = false;
            eye.ConsumeConditions = [];
            eye.ShopPrice = 5;
            eye.IsShopItem = true;
            eye.StartsLocked = true;
            eye.OnUnlockUsesTHE = true;
            eye.UsesSpecialUnlockText = false;
            eye.SpecialUnlockID = UILocID.None;
            eye.item._ItemTypeIDs = [];
            eye.item.AddBlueSkyUnlock("Vendella_CH", "locked_opalescenteye.png", "ach_opalescenteye.png");

            PerformEffect_Item tacks = new PerformEffect_Item("Salt_BluntTacks_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplySlipSlotEffect>(), 1, Slots.Sides)]);
            tacks.Name = "Blunt Tacks";
            tacks.Flavour = "\"You could maybe hurt someone with these if you tried really really hard\"";
            tacks.Description = "At the start of each turn, inflict 1 Slip on the Left and Right allied positions.\nHeal 75% more to units in Slip.";
            tacks.Icon = ResourceLoader.LoadSprite("item_blunttacks.png");
            tacks.TriggerOn = TriggerCalls.OnTurnStart;
            tacks.EquippedModifiers = [];
            tacks.DoesPopUpInfo = true;
            tacks.Conditions = [];
            tacks.DoesActionOnTriggerAttached = false;
            tacks.ConsumeOnTrigger = TriggerCalls.OnWillApplyHeal;
            tacks.ConsumeOnUse = false;
            tacks.ConsumeConditions = [ScriptableObject.CreateInstance<HealMoreInSlipCondition>()];
            tacks.ShopPrice = 5;
            tacks.IsShopItem = false;
            tacks.StartsLocked = true;
            tacks.OnUnlockUsesTHE = true;
            tacks.UsesSpecialUnlockText = false;
            tacks.SpecialUnlockID = UILocID.None;
            tacks.item._ItemTypeIDs = [];
            tacks.item.AddBlueSkyUnlock("Class1_CH", "locked_blunttacks.png", "ach_blunttacks.png");

            PerformEffect_Item sanddial = new PerformEffect_Item("Salt_SandDial_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<AddTurnTargetToTimelineEffect>(), 1, Slots.Front)]);
            sanddial.Name = "Sand Dial";
            sanddial.Flavour = "\"A constant battle against the eventual decay into chaos\"";
            sanddial.Description = "Inflict Entropy equal to damage dealt to all enemies.\nOn moving, give the Opposing enemy another action.";
            sanddial.Icon = ResourceLoader.LoadSprite("item_sanddial.png");
            sanddial.TriggerOn = TriggerCalls.OnMoved;
            sanddial.EquippedModifiers = [];
            sanddial.DoesPopUpInfo = true;
            sanddial.Conditions = [];
            sanddial.DoesActionOnTriggerAttached = false;
            sanddial.ConsumeOnTrigger = TriggerCalls.OnDidApplyDamage;
            sanddial.ConsumeOnUse = false;
            sanddial.ConsumeConditions = [ScriptableObject.CreateInstance<SandDialCondition>()];
            sanddial.ShopPrice = 6;
            sanddial.IsShopItem = false;
            sanddial.StartsLocked = true;
            sanddial.OnUnlockUsesTHE = true;
            sanddial.UsesSpecialUnlockText = false;
            sanddial.SpecialUnlockID = UILocID.None;
            sanddial.Item._ItemTypeIDs = [];
            sanddial.item.AddBlueSkyUnlock("Alpha_CH", "locked_sanddial.png", "ach_sanddial.png");
        }
    }
}
