using BrutalAPI;
using BrutalAPI.Items;
using HarmonyLib;
using SaltEnemies_Reseasoned;
using SaltsEnemies_Reseasoneds;
using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace SaltsEnemies_Reseasoned
{
    public static class ItemsFirst
    {
        public static bool Test = false;
        public static void Add()
        {
            Basic_Item choco = new Basic_Item("Salt_ChocolateCoin_TW");
            choco.Name = "Chocolate Coin";
            choco.Flavour = "\"Reduced value.\"";
            choco.Description = "While this item is in your inventory, decrease the price of all items in the shop by 20%.";
            choco.Icon = ResourceLoader.LoadSprite("Item_ChocolateCoin.png");
            choco.EquippedModifiers = [];
            choco.TriggerOn = TriggerCalls.Count;
            choco.DoesPopUpInfo = false;
            choco.Conditions = [];
            choco.DoesActionOnTriggerAttached = false;
            choco.ConsumeOnTrigger = TriggerCalls.Count;
            choco.ConsumeOnUse = false;
            choco.ConsumeConditions = [];
            choco.ShopPrice = 0;
            choco.IsShopItem = false;
            choco.StartsLocked = true;
            choco.OnUnlockUsesTHE = true;
            choco.UsesSpecialUnlockText = false;
            choco.SpecialUnlockID = UILocID.None;
            choco.item.AddItem("Locked_ChocolateCoin.png", AchievementIDs.Shiny, Test);

            PerformEffect_Item sign = new PerformEffect_Item("Salt_CardboardSign_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyShieldSlotEffect>(), 5, Slots.Self)], true);
            sign.Name = "Cardboard Sign";
            sign.Flavour = "\"Barely fooled me.\"";
            sign.Description = "On an enemy moving in front of this party member, gain 5 Shield.";
            sign.Icon = ResourceLoader.LoadSprite("Item_WoodSign.png");
            sign.EquippedModifiers = [];
            sign.TriggerOn = (TriggerCalls)AmbushManager.Patiently;
            sign.DoesPopUpInfo = true;
            sign.Conditions = [];
            sign.DoesActionOnTriggerAttached = false;
            sign.ConsumeOnTrigger = TriggerCalls.Count;
            sign.ConsumeOnUse = false;
            sign.ConsumeConditions = [];
            sign.ShopPrice = 8;
            sign.IsShopItem = true;
            sign.StartsLocked = true;
            sign.OnUnlockUsesTHE = true;
            sign.UsesSpecialUnlockText = false;
            sign.SpecialUnlockID = UILocID.None;
            sign.item.AddItem("Locked_WoodSign.png", AchievementIDs.SnakeGod, Test);

            PerformEffect_Item pom = new PerformEffect_Item("Salt_PomPoms_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPowerEffect>(), 1, Slots.Sides)]);
            pom.Name = "Pom-Poms";
            pom.Flavour = "\"It's the thought that counts.\"";
            pom.Description = "On dealing damage, apply 1 Power to the Left and Right allies.";
            pom.Icon = ResourceLoader.LoadSprite("Item_PomPom.png");
            pom.EquippedModifiers = [];
            pom.TriggerOn = TriggerCalls.OnDidApplyDamage;
            pom.DoesPopUpInfo = true;
            pom.Conditions = [];
            pom.DoesActionOnTriggerAttached = false;
            pom.ConsumeOnTrigger = TriggerCalls.Count;
            pom.ConsumeOnUse = false;
            pom.ConsumeConditions = [];
            pom.ShopPrice = 5;
            pom.IsShopItem = true;
            pom.StartsLocked = true;
            pom.OnUnlockUsesTHE = true;
            pom.UsesSpecialUnlockText = false;
            pom.SpecialUnlockID = UILocID.None;
            pom.item.AddItem("Locked_PomPom.png", AchievementIDs.Chapter1, Test);

            Basic_Item silver = new Basic_Item("Salt_SilverBullet_SW");
            silver.Name = "Silver Bullet";
            silver.Flavour = "\"Blessed death.\"";
            silver.Description = "On dealing damage to an enemy without Determined, apply 3 Determined to them.\nDeal double damage to enemies with Determined.";
            silver.Icon = ResourceLoader.LoadSprite("Item_SilverBullet.png");
            silver.EquippedModifiers = [];
            silver.TriggerOn = TriggerCalls.Count;
            silver.DoesPopUpInfo = false;
            silver.Conditions = [];
            silver.DoesActionOnTriggerAttached = false;
            silver.ConsumeOnTrigger = TriggerCalls.Count;
            silver.ConsumeOnUse = false;
            silver.ConsumeConditions = [];
            silver.ShopPrice = 2;
            silver.IsShopItem = true;
            silver.StartsLocked = true;
            silver.OnUnlockUsesTHE = true;
            silver.UsesSpecialUnlockText = false;
            silver.SpecialUnlockID = UILocID.None;
            silver.item._ItemTypeIDs = ["Magic"];
            silver.item.AddItem("Locked_SilverBullet.png", AchievementIDs.Chapter2, Test);

            PerformEffect_Item dues = new PerformEffect_Item("Salt_Dues_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<TimelineClearEffect>())]);
            dues.Name = "Dues";
            dues.Flavour = "\"You'll never catch me!\"";
            dues.Description = "At the start of the third turn, cancel all enemy abilities.";
            dues.Icon = ResourceLoader.LoadSprite("Item_Dues.png");
            dues.EquippedModifiers = [];
            dues.TriggerOn = TriggerCalls.OnTurnStart;
            dues.DoesPopUpInfo = true;
            dues.Conditions = [TurnPassedCondition.Create(3)];
            dues.DoesActionOnTriggerAttached = false;
            dues.ConsumeOnTrigger = TriggerCalls.Count;
            dues.ConsumeOnUse = false;
            dues.ConsumeConditions = [];
            dues.ShopPrice = 7;
            dues.IsShopItem = true;
            dues.StartsLocked = true;
            dues.OnUnlockUsesTHE = false;
            dues.UsesSpecialUnlockText = false;
            dues.SpecialUnlockID = UILocID.None;
            dues.item.AddItem("Locked_Dues.png", AchievementIDs.Chapter3, Test);

            Ability replicate = new Ability("Replicate", "Salt_Replicate_A");
            replicate.Description = "Perform the last ability used.";
            replicate.Rarity = Rarity.GetCustomRarity("rarity5");
            replicate.Cost = [Pigments.Purple];
            replicate.Effects = [Effects.GenerateEffect(ScriptableObject.CreateInstance<CopyLastAbilityEffect>(), 1, Slots.Self)];
            replicate.AddIntentsToTarget(Slots.Self, ["Misc"]);
            replicate.Visuals = null;
            replicate.AbilitySprite = ResourceLoader.LoadSprite("ability_replicate.png");
            ExtraAbility_Wearable_SMS add_replicate = ScriptableObject.CreateInstance<ExtraAbility_Wearable_SMS>();
            add_replicate._extraAbility = replicate.GenerateCharacterAbility();

            ((Passives.Construct as Connection_PerformEffectPassiveAbility).connectionEffects[1].effect as CasterAddRandomExtraAbilityEffect)._extraData.Add(add_replicate);

            Basic_Item cheat = new Basic_Item("Salt_CheatingMaterials_TW");
            cheat.Name = "Cheating Materials";
            cheat.Flavour = "\"...It's for single digit arithmatic.\"";
            cheat.Description = "Adds the extra ability \"Replicate\", which copies the last ability used.";
            cheat.Icon = ResourceLoader.LoadSprite("Item_CheatingMaterials.png");
            cheat.EquippedModifiers = [add_replicate];
            cheat.TriggerOn = TriggerCalls.Count;
            cheat.DoesPopUpInfo = false;
            cheat.Conditions = [];
            cheat.DoesActionOnTriggerAttached = false;
            cheat.ConsumeOnTrigger = TriggerCalls.Count;
            cheat.ConsumeOnUse = false;
            cheat.ConsumeConditions = [];
            cheat.ShopPrice = 5;
            cheat.IsShopItem = false;
            cheat.StartsLocked = true;
            cheat.OnUnlockUsesTHE = true;
            cheat.UsesSpecialUnlockText = false;
            cheat.SpecialUnlockID = UILocID.None;
            cheat.item.AddItem("Locked_CheatingMaterials.png", AchievementIDs.Chapter4, Test);

            //passive fruit we'll have to think about this one later. because.you know.
            ChildrenPassiveAbility whimsy = ScriptableObject.CreateInstance<ChildrenPassiveAbility>();
            whimsy._passiveName = "Whimsy";
            whimsy.m_PassiveID = "Whimsy_PA";
            whimsy.passiveIcon = ResourceLoader.LoadSprite("WileyPassive.png");
            whimsy._enemyDescription = "Most Status Effects and some Field Effects will no longer decrease while this unit is in combat.";
            whimsy._characterDescription = whimsy._enemyDescription;
            whimsy.doesPassiveTriggerInformationPanel = false;
            whimsy._triggerOn = [];

            AddPassiveEffect addWhimsy = ScriptableObject.CreateInstance<AddPassiveEffect>();
            addWhimsy._passiveToAdd = whimsy;

            PerformEffect_Item scary = new PerformEffect_Item("Salt_Passivefruit_TW", [Effects.GenerateEffect(addWhimsy, 1, Slots.Front)]);
            scary.Name = "Passivefruit";
            scary.Flavour = "\"Scary.\"";
            scary.Description = "At the start of combat, add \"Whimsy\" as a passive to the Opposing enemy.";
            scary.Icon = ResourceLoader.LoadSprite("Item_PassiveFruit.png");
            scary.EquippedModifiers = [];
            scary.TriggerOn = TriggerCalls.OnCombatStart;
            scary.DoesPopUpInfo = true;
            scary.Conditions = [];
            scary.DoesActionOnTriggerAttached = false;
            scary.ConsumeOnTrigger = TriggerCalls.Count;
            scary.ConsumeOnUse = false;
            scary.ConsumeConditions = [];
            scary.ShopPrice = 3;
            scary.IsShopItem = false;
            scary.StartsLocked = true;
            scary.OnUnlockUsesTHE = true;
            scary.UsesSpecialUnlockText = false;
            scary.SpecialUnlockID = UILocID.None;
            scary.item._ItemTypeIDs = ["Magic"];
            scary.item.AddItem("Locked_PassiveFruit.png", AchievementIDs.Chapter5, Test);

            PerformEffect_Item fossil = new PerformEffect_Item("Salt_UnknownFossil_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyRootsSlotEffect>(), 3, Targetting.Everything(false))]);
            fossil.Name = "Unknown Fossil";
            fossil.Flavour = "\"Relic of meaningless value.\"";
            fossil.Description = "At the start of every other turn, inflict 3 Roots on every enemy position.";
            fossil.Icon = ResourceLoader.LoadSprite("Item_UnknownFossil.png");
            fossil.EquippedModifiers = [];
            fossil.TriggerOn = TriggerCalls.OnTurnStart;
            fossil.DoesPopUpInfo = true;
            fossil.Conditions = [ScriptableObject.CreateInstance<EvenTurnCondition>()];
            fossil.DoesActionOnTriggerAttached = false;
            fossil.ConsumeOnTrigger = TriggerCalls.Count;
            fossil.ConsumeOnUse = false;
            fossil.ConsumeConditions = [];
            fossil.ShopPrice = 4;
            fossil.IsShopItem = false;
            fossil.StartsLocked = true;
            fossil.OnUnlockUsesTHE = true;
            fossil.UsesSpecialUnlockText = false;
            fossil.SpecialUnlockID = UILocID.None;
            fossil.item.AddItem("Locked_UnknownFossil.png", AchievementIDs.Chapter6, Test);

            PerformEffect_Item can = new PerformEffect_Item("Salt_TinCan_EW", [], true);
            can.Name = "Tin Can";
            can.Flavour = "\"You caught a... tin can!\"";
            can.Description = "On death, prevent it and heal 1 health.\nThis item is destroyed on activation and at the end of combat.";
            can.Icon = ResourceLoader.LoadSprite("Item_TinCan.png");
            can.EquippedModifiers = [];
            can.TriggerOn = TriggerCalls.CanDie;
            can.DoesPopUpInfo = true;
            can.Conditions = [ScriptableObject.CreateInstance<TinCanCondition>()];
            can.DoesActionOnTriggerAttached = false;
            can.ConsumeOnTrigger = TriggerCalls.OnCombatEnd;
            can.ConsumeOnUse = true;
            can.ConsumeConditions = [];
            can.ShopPrice = 3;
            can.IsShopItem = false;
            can.StartsLocked = true;
            can.OnUnlockUsesTHE = true;
            can.UsesSpecialUnlockText = true;
            can.SpecialUnlockID = UILocID.ItemFishLocationLabel;
            can.item.AddFishItem(2, "Locked_TinCan.png", AchievementIDs.Chapter7, Test);

            TrackIntegerReferenceCondition track = ScriptableObject.CreateInstance<TrackIntegerReferenceCondition>();
            track.StoredValue = "Echo_TW";
            
            MultiPerformEffectItem echo = new MultiPerformEffectItem("Salt_Echo_TW", []);
            echo.Name = "Echo";
            echo.Flavour = "\"Mediocre shot\"";
            echo.Description = "On dealing any damage, deal it again to the same position at the start of the next turn.\nTake all damage taken this combat at the end of each turn, from no one.";
            echo.Icon = ResourceLoader.LoadSprite("Item_Echo.png");
            echo.EquippedModifiers = [];
            echo.TriggerOn = TriggerCalls.OnDamaged;
            echo.DoesPopUpInfo = false;
            echo.Conditions = [track];
            echo.DoesActionOnTriggerAttached = false;
            echo.ConsumeOnTrigger = TriggerCalls.Count;
            echo.ConsumeOnUse = false;
            echo.ConsumeConditions = [];
            echo.ShopPrice = 8;
            echo.IsShopItem = false;
            echo.StartsLocked = true;
            echo.OnUnlockUsesTHE = true;
            echo.UsesSpecialUnlockText = false;
            echo.SpecialUnlockID = UILocID.None;
            EffectTrigger echo_second = new EffectTrigger([Effects.GenerateEffect(DamageByStoredValueFromNoOneEffect.Create("Echo_TW"), 1, Slots.Self)], [TriggerCalls.OnTurnFinished], [StoredValueCondition.Create("Echo_TW")]);
            echo.AddEffectTrigger(echo_second);
            echo.item._ItemTypeIDs = ["Magic"];
            echo.item.AddItem("Locked_Echo.png", AchievementIDs.Miriam, Test);

            PerformEffect_Item bell = new PerformEffect_Item("Salt_LittleBell_TW", [
                Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPaleEffect>(), 10, Targetting.HighestEnemy),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPaleEffect>(), 10, Targetting.HighestAlly)
                ]);
            bell.Name = "Little Bell";
            bell.Flavour = "\"When it rings we all go to hell.\"";
            bell.Description = "At the start of each turn, inflict 10 Pale on the highest health enemy and party member.";
            bell.Icon = ResourceLoader.LoadSprite("Item_LittleBell.png");
            bell.EquippedModifiers = [];
            bell.TriggerOn = TriggerCalls.OnTurnStart;
            bell.DoesPopUpInfo = true;
            bell.Conditions = [];
            bell.DoesActionOnTriggerAttached = false;
            bell.ConsumeOnTrigger = TriggerCalls.Count;
            bell.ConsumeOnUse = false;
            bell.ConsumeConditions = [];
            bell.ShopPrice = 5;
            bell.IsShopItem = false;
            bell.StartsLocked = true;
            bell.OnUnlockUsesTHE = true;
            bell.UsesSpecialUnlockText = false;
            bell.SpecialUnlockID = UILocID.None;
            bell.item._ItemTypeIDs = ["Magic"];
            bell.item.AddItem("Locked_LittleBell.png", AchievementIDs.Chapter11, Test);

            PerformEffect_Item frenzy = new PerformEffect_Item("Salt_FeedingFrenzy_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyHasteEffect>(), 1, Targeting.AllUnits)]);
            frenzy.Name = "Feeding Frenzy";
            frenzy.Flavour = "\"Blood excitement.\"";
            frenzy.Description = "On getting a kill, apply 1 Haste to all party members and enemies.";
            frenzy.Icon = ResourceLoader.LoadSprite("Item_FeedingFrenzy.png");
            frenzy.EquippedModifiers = [];
            frenzy.TriggerOn = TriggerCalls.OnKill;
            frenzy.DoesPopUpInfo = true;
            frenzy.Conditions = [];
            frenzy.DoesActionOnTriggerAttached = false;
            frenzy.ConsumeOnTrigger = TriggerCalls.Count;
            frenzy.ConsumeOnUse = false;
            frenzy.ConsumeConditions = [];
            frenzy.ShopPrice = 7;
            frenzy.IsShopItem = false;
            frenzy.StartsLocked = true;
            frenzy.OnUnlockUsesTHE = false;
            frenzy.UsesSpecialUnlockText = false;
            frenzy.SpecialUnlockID = UILocID.None;
            frenzy.item.AddItem("Locked_FeedingFrenzy.png", AchievementIDs.Chapter8, Test);

            PerformEffect_Item ear = new PerformEffect_Item("Salt_SpareEar_SW", [
                Effects.GenerateEffect(BasicEffects.GenPigment(Pigments.Red), 2, Slots.Self),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyShieldSlotEffect>(), 6, Slots.Self)
                ]);
            ear.Name = "Spare Ear";
            ear.Flavour = "\"Too old to be reattached.\"";
            ear.Description = "On taking any damage, produce 2 Red pigment and gain 6 Shield.";
            ear.Icon = ResourceLoader.LoadSprite("Item_SpareEar.png");
            ear.EquippedModifiers = [];
            ear.TriggerOn = TriggerCalls.OnDamaged;
            ear.DoesPopUpInfo = true;
            ear.Conditions = [];
            ear.DoesActionOnTriggerAttached = false;
            ear.ConsumeOnTrigger = TriggerCalls.Count;
            ear.ConsumeOnUse = false;
            ear.ConsumeConditions = [];
            ear.ShopPrice = 1;
            ear.IsShopItem = true;
            ear.StartsLocked = true;
            ear.OnUnlockUsesTHE = false;
            ear.UsesSpecialUnlockText = false;
            ear.SpecialUnlockID = UILocID.None;
            ear.item.AddItem("Locked_SpareEar.png", AchievementIDs.Chapter9, Test);

            PerformEffect_Item feather = new PerformEffect_Item("Salt_FeatherGun_TW", []);
            feather.Name = "Feather Gun";
            feather.Flavour = "\"The weapon imbues the wielder with the eternal hatred of the little crow.\"";
            feather.Description = "Deal 15% more damage.\nDeal 100% more damage if the target is a Bird.";
            feather.Icon = ResourceLoader.LoadSprite("Item_FeatherGun.png");
            feather.EquippedModifiers = [];
            feather.TriggerOn = TriggerCalls.OnWillApplyDamage;
            feather.DoesPopUpInfo = false;
            feather.Conditions = [ScriptableObject.CreateInstance<FeatherGunCondition>()];
            feather.DoesActionOnTriggerAttached = false;
            feather.ConsumeOnTrigger = TriggerCalls.Count;
            feather.ConsumeOnUse = false;
            feather.ConsumeConditions = [];
            feather.ShopPrice = 9;
            feather.IsShopItem = false;
            feather.StartsLocked = true;
            feather.OnUnlockUsesTHE = true;
            feather.UsesSpecialUnlockText = false;
            feather.SpecialUnlockID = UILocID.None;
            feather.item.AddItem("Locked_FeatherGun.png", AchievementIDs.Chapter12, Test);

            PerformEffect_Item stage = new PerformEffect_Item("Salt_StageFright_SW", []);
            stage.Name = "Stage Fright";
            stage.Flavour = "\"Imagine them all as potatoes.\"";
            stage.Description = "If there is no Opposing enemy deal 30% more damage.";
            stage.Icon = ResourceLoader.LoadSprite("Item_StageFreight.png");
            stage.EquippedModifiers = [];
            stage.TriggerOn = TriggerCalls.OnWillApplyDamage;
            stage.DoesPopUpInfo = false;
            stage.Conditions = [ScriptableObject.CreateInstance<StageFrightCondition>()];
            stage.DoesActionOnTriggerAttached = false;
            stage.ConsumeOnTrigger = TriggerCalls.Count;
            stage.ConsumeOnUse = false;
            stage.ConsumeConditions = [];
            stage.ShopPrice = 5;
            stage.IsShopItem = true;
            stage.StartsLocked = true;
            stage.OnUnlockUsesTHE = false;
            stage.UsesSpecialUnlockText = false;
            stage.SpecialUnlockID = UILocID.None;
            stage.item.AddItem("Locked_StageFreight.png", AchievementIDs.Chapter13, Test);

            PercentageEffectorCondition fish_fifteen = ScriptableObject.CreateInstance<PercentageEffectorCondition>();
            fish_fifteen.triggerPercentage = 15;

            PerformEffect_Item fish = new PerformEffect_Item("Salt_Coelacanth_EW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<HealEffect>(), 2, Slots.Self)]);
            fish.Name = "Coelacanth";
            fish.Flavour = "\"You caught a... coelacanth! 150cm.\"";
            fish.Description = "On taking any damage, heal 2 health. 15% chance to be destroyed on activation.";
            fish.Icon = ResourceLoader.LoadSprite("Item_Coelocanth.png");
            fish.EquippedModifiers = [];
            fish.TriggerOn = TriggerCalls.OnDamaged;
            fish.DoesPopUpInfo = true;
            fish.Conditions = [];
            fish.DoesActionOnTriggerAttached = false;
            fish.ConsumeOnTrigger = TriggerCalls.Count;
            fish.ConsumeOnUse = true;
            fish.ConsumeConditions = [fish_fifteen];
            fish.ShopPrice = 3;
            fish.IsShopItem = false;
            fish.StartsLocked = true;
            fish.OnUnlockUsesTHE = true;
            fish.UsesSpecialUnlockText = true;
            fish.SpecialUnlockID = UILocID.ItemFishLocationLabel;
            fish.item.AddFishItem(2, "Locked_Coelocanth.png", AchievementIDs.Chapter14, Test);

            PerformEffect_Item gas = new PerformEffect_Item("Salt_HormoneGasses_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPimplesEffect>(), 2, Slots.Front), Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPimplesEffect>(), 1, Slots.Front, Effects.ChanceCondition(50))]);
            gas.Name = "Hormone Gasses";
            gas.Flavour = "\"Untested for side effects.\"";
            gas.Description = "On using an ability, inflict 2-3 Pimples on the Opposing enemy.";
            gas.Icon = ResourceLoader.LoadSprite("Item_HormoneGasses.png");
            gas.EquippedModifiers = [];
            gas.TriggerOn = TriggerCalls.OnAbilityUsed;
            gas.DoesPopUpInfo = true;
            gas.Conditions = [];
            gas.DoesActionOnTriggerAttached = false;
            gas.ConsumeOnTrigger = TriggerCalls.Count;
            gas.ConsumeOnUse = false;
            gas.ConsumeConditions = [];
            gas.ShopPrice = 2;
            gas.IsShopItem = true;
            gas.StartsLocked = true;
            gas.OnUnlockUsesTHE = true;
            gas.UsesSpecialUnlockText = false;
            gas.SpecialUnlockID = UILocID.None;
            gas.item.AddItem("Locked_HormoneGasses.png", AchievementIDs.Chapter15, Test);

            Basic_Item hat = new Basic_Item("Salt_GlowingHat_SW");
            hat.Name = "Glowing Hat";
            hat.Flavour = "\"Makes you visible to those in the dark.\"";
            hat.Description = "Before taking direct damage, gain Spotlight.";
            hat.Icon = ResourceLoader.LoadSprite("Item_GlowingHat.png");
            hat.EquippedModifiers = [];
            hat.TriggerOn = TriggerCalls.Count;
            hat.DoesPopUpInfo = false;
            hat.Conditions = [];
            hat.DoesActionOnTriggerAttached = false;
            hat.ConsumeOnTrigger = TriggerCalls.Count;
            hat.ConsumeOnUse = false;
            hat.ConsumeConditions = [];
            hat.ShopPrice = 4;
            hat.IsShopItem = true;
            hat.StartsLocked = true;
            hat.OnUnlockUsesTHE = true;
            hat.UsesSpecialUnlockText = false;
            hat.SpecialUnlockID = UILocID.None;
            hat.item.AddItem("Locked_GlowingHat.png", AchievementIDs.Chapter16, Test);

            PerformEffect_Item wings = new PerformEffect_Item("Salt_ItsWings_TW", [
                Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPowerEffect>(), 7, Slots.Front),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPowerEffect>(), 7, Slots.Self, BasicEffects.DidThat(true))
                ]);
            wings.Name = "Its Wings";
            wings.Flavour = "\"As it spreads its wings for an old god, a heaven just for you burrows its way.\"";
            wings.Description = "At the start of combat, apply 7 Power to the Opposing enemy.\nIf successful, gain 7 Power.";
            wings.Icon = ResourceLoader.LoadSprite("Item_ItsWings.png");
            wings.EquippedModifiers = [];
            wings.TriggerOn = TriggerCalls.OnCombatStart;
            wings.DoesPopUpInfo = true;
            wings.Conditions = [];
            wings.DoesActionOnTriggerAttached = false;
            wings.ConsumeOnTrigger = TriggerCalls.Count;
            wings.ConsumeOnUse = false;
            wings.ConsumeConditions = [];
            wings.ShopPrice = 7;
            wings.IsShopItem = false;
            wings.StartsLocked = true;
            wings.OnUnlockUsesTHE = false;
            wings.UsesSpecialUnlockText = false;
            wings.SpecialUnlockID = UILocID.None;
            wings.item._ItemTypeIDs = ["Magic"];
            wings.item.AddItem("Locked_ItsWings.png", AchievementIDs.DeadGod, Test);

            PerformEffect_Item water = new PerformEffect_Item("Salt_DeepWater_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyAnestheticsEffect>(), 2, Slots.Self)]);
            water.Name = "Deep Waters";
            water.Flavour = "\"So blue it's pitch black.\"";
            water.Description = "On taking any damage, gain 2 Anesthetics.";
            water.Icon = ResourceLoader.LoadSprite("Item_DeepWater.png");
            water.EquippedModifiers = [];
            water.TriggerOn = TriggerCalls.OnDamaged;
            water.DoesPopUpInfo = true;
            water.Conditions = [];
            water.DoesActionOnTriggerAttached = false;
            water.ConsumeOnTrigger = TriggerCalls.Count;
            water.ConsumeOnUse = false;
            water.ConsumeConditions = [];
            water.ShopPrice = 6;
            water.IsShopItem = false;
            water.StartsLocked = true;
            water.OnUnlockUsesTHE = true;
            water.UsesSpecialUnlockText = false;
            water.SpecialUnlockID = UILocID.None;
            water.item.AddItem("Locked_DeepWater.png", AchievementIDs.Deep, Test);

            LockedInPassiveAbility lockedIn = ScriptableObject.CreateInstance<LockedInPassiveAbility>();
            lockedIn._passiveName = "Locked In";
            lockedIn.passiveIcon = ResourceLoader.LoadSprite("NoMenu.png");
            lockedIn._enemyDescription = "The Pause Menu can no longer be accessed.";
            lockedIn._characterDescription = "The Pause Menu can no longer be accessed.";
            lockedIn.m_PassiveID = "NoPause_PA";
            lockedIn.doesPassiveTriggerInformationPanel = false;
            lockedIn._triggerOn = new TriggerCalls[] { TriggerCalls.Count };
            AddPassiveEffect add_locked = ScriptableObject.CreateInstance<AddPassiveEffect>();
            add_locked._passiveToAdd = lockedIn;

            AnimationVisualsEffect visuals = ScriptableObject.CreateInstance<AnimationVisualsEffect>();
            visuals._visuals = ((LoadedAssetsHandler.GetEnemy("OsmanSinnoks_BOSS").passiveAbilities[0] as ExtraAttackPassiveAbility)._extraAbility.ability.effects[0].effect as AnimationVisualsIfUnitEffect)._visuals;
            visuals._animationTarget = Slots.Self;
            DoubleEffectCondition awaken_double = ScriptableObject.CreateInstance<DoubleEffectCondition>();
            awaken_double.first = BasicEffects.DidThat(true);
            awaken_double.second = Effects.ChanceCondition(50);
            awaken_double.And = true;
            MultiPreviousEffectCondition awaken_prev = ScriptableObject.CreateInstance<MultiPreviousEffectCondition>();
            awaken_prev.previousAmount = [1, 2];
            awaken_prev.wasSuccessful = [false, true];
            Ability awaken = new Ability("Awaken", "Salt_Awaken_A");
            awaken.Description = "10% chance to kill either a random enemy or this party member.";
            awaken.Cost = [Pigments.Purple];
            awaken.AbilitySprite = ResourceLoader.LoadSprite("ability_awaken.png");
            awaken.Rarity = Rarity.GetCustomRarity("rarity5");
            awaken.Effects = new EffectInfo[1];
            awaken.Effects[0] = Effects.GenerateEffect(ScriptableObject.CreateInstance<NineKeyEffect>());
            awaken.AddIntentsToTarget(Targeting.Unit_AllOpponents, ["Damage_Death"]);
            awaken.AddIntentsToTarget(Slots.Self, ["Damage_Death"]);
            awaken.Visuals = null;
            //awaken.GenerateEnemyAbility();
            ExtraAbility_Wearable_SMS awaken_a = ScriptableObject.CreateInstance<ExtraAbility_Wearable_SMS>();
            awaken_a._extraAbility = awaken.GenerateCharacterAbility();

            PerformEffect_Item nine = new PerformEffect_Item("Salt_NineKey_TW", [Effects.GenerateEffect(add_locked, 1, Targeting.Unit_AllAllies)]);
            nine.Name = "Nine Key";
            nine.Flavour = "\"It's all just a dream.\"";
            nine.Description = "Adds the extra ability \"Awaken\", which has a chance to kill either them or a random enemy.\nAdds \"Locked In\" as a passive to all party members on combat start.";
            nine.Icon = ResourceLoader.LoadSprite("Item_NineKey.png");
            nine.EquippedModifiers = [awaken_a];
            nine.TriggerOn = TriggerCalls.OnCombatStart;
            nine.DoesPopUpInfo = false;
            nine.Conditions = [];
            nine.DoesActionOnTriggerAttached = false;
            nine.ConsumeOnTrigger = TriggerCalls.Count;
            nine.ConsumeOnUse = false;
            nine.ConsumeConditions = [];
            nine.ShopPrice = 4;
            nine.IsShopItem = false;
            nine.StartsLocked = true;
            nine.OnUnlockUsesTHE = true;
            nine.UsesSpecialUnlockText = false;
            nine.SpecialUnlockID = UILocID.None;
            nine.item._ItemTypeIDs = ["Magic"];
            nine.item.AddItem("Locked_NineKey.png", AchievementIDs.Postmodern, Test);

            Ability reconfigure = new Ability("Transfiguration", "Salt_Reconfigure_A");
            reconfigure.Description = "Permenantly transform into a random party member of the same level.";
            reconfigure.Cost = [Pigments.Purple];
            reconfigure.Rarity = Rarity.GetCustomRarity("rarity5");
            reconfigure.Effects = [Effects.GenerateEffect(ScriptableObject.CreateInstance<PermenantTransformationEffect>(), 1, Slots.Self)];
            reconfigure.AddIntentsToTarget(Slots.Self, ["Misc_Hidden"]);
            reconfigure.Visuals = LoadedAssetsHandler.GetEnemyAbility("Repent_A").visuals;
            reconfigure.AnimationTarget = Slots.Self;
            reconfigure.AbilitySprite = ResourceLoader.LoadSprite("ability_reconfigure.png");
            ExtraAbility_Wearable_SMS add_recon = ScriptableObject.CreateInstance<ExtraAbility_Wearable_SMS>();
            add_recon._extraAbility = reconfigure.GenerateCharacterAbility();

            ((Passives.Construct as Connection_PerformEffectPassiveAbility).connectionEffects[1].effect as CasterAddRandomExtraAbilityEffect)._extraData.Add(add_recon);

            PercentageEffectorCondition p30 = ScriptableObject.CreateInstance<PercentageEffectorCondition>();
            p30.triggerPercentage = 30;

            PerformEffect_Item fone = new PerformEffect_Item("AbandonedArtifact_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<CasterRemoveItemExtraAbilityEffect>())]);
            fone.Name = "Abandoned Artifact";
            fone.Flavour = "\"Give AbandonedArtifact_TW\"";
            fone.Description = "Adds the extra ability \"Reconfigure,\" an unpredictable transformation.\n30% chance to be destroyed on taking any damage.";
            fone.Icon = ResourceLoader.LoadSprite("Item_AbandonedArtifact.png");
            fone.EquippedModifiers = [add_recon];
            fone.TriggerOn = TriggerCalls.OnDamaged;
            fone.DoesPopUpInfo = true;
            fone.Conditions = [p30];
            fone.DoesActionOnTriggerAttached = false;
            fone.ConsumeOnTrigger = TriggerCalls.Count;
            fone.ConsumeOnUse = true;
            fone.ConsumeConditions = [];
            fone.ShopPrice = 4;
            fone.IsShopItem = false;
            fone.StartsLocked = true;
            fone.OnUnlockUsesTHE = true;
            fone.UsesSpecialUnlockText = false;
            fone.SpecialUnlockID = UILocID.None;
            fone.item._ItemTypeIDs = ["Magic"];
            fone.item.AddItem("Locked_AbandonedArtifact.png", AchievementIDs.HelpMe, Test);

            PerformEffect_Item torture = new PerformEffect_Item("Salt_Torturepedia_SW", []);
            torture.Name = "Torturepedia";
            torture.Flavour = "\"I was just doing it like they tought me.\"";
            torture.Description = "Increase damage by 50%. Damaged targets gain an additional action.";
            torture.Icon = ResourceLoader.LoadSprite("Item_Torturepedia.png");
            torture.EquippedModifiers = [];
            torture.TriggerOn = TriggerCalls.OnWillApplyDamage;
            torture.DoesPopUpInfo = false;
            torture.Conditions = [IncreaseDamageMultiplyCondition.Create(1.5f)];
            torture.DoesActionOnTriggerAttached = false;
            torture.ConsumeOnTrigger = TriggerCalls.Count;
            torture.ConsumeOnUse = false;
            torture.ConsumeConditions = [];
            torture.ShopPrice = 7;
            torture.IsShopItem = true;
            torture.StartsLocked = true;
            torture.OnUnlockUsesTHE = true;
            torture.UsesSpecialUnlockText = false;
            torture.SpecialUnlockID = UILocID.None;
            torture.item._ItemTypeIDs = ["Magic"];
            torture.item.AddItem("Locked_Torturepedia.png", AchievementIDs.Chapter10, Test);

            AddPassiveEffect confuse = ScriptableObject.CreateInstance<AddPassiveEffect>();
            confuse._passiveToAdd = Passives.Confusion;

            MultiPerformEffectItem lullaby = new MultiPerformEffectItem("Salt_ImperfectLullaby_TW", [Effects.GenerateEffect(confuse, 1, Slots.Self)]);
            lullaby.Name = "Imperfect Lullaby";
            lullaby.Flavour = "\"Close your eyes. When you wake up, it will all be over.\"";
            lullaby.Description = "This party member is immune to all damage equal to or below 4.\nGain \"Confusion\" as a passive on taking any damage.";
            lullaby.Icon = ResourceLoader.LoadSprite("Item_ImperfectLullaby.png");
            lullaby.EquippedModifiers = [];
            lullaby.TriggerOn = TriggerCalls.OnDamaged;
            lullaby.DoesPopUpInfo = true;
            lullaby.Conditions = [];
            lullaby.DoesActionOnTriggerAttached = false;
            lullaby.ConsumeOnTrigger = TriggerCalls.Count;
            lullaby.ConsumeOnUse = false;
            lullaby.ConsumeConditions = [];
            lullaby.ShopPrice = 6;
            lullaby.IsShopItem = false;
            lullaby.StartsLocked = true;
            lullaby.OnUnlockUsesTHE = true;
            lullaby.UsesSpecialUnlockText = false;
            lullaby.SpecialUnlockID = UILocID.None;
            EffectTrigger lullaby_second = new EffectTrigger([], [TriggerCalls.OnBeingDamaged], [BulwarkCondition.Create(4)], false);
            lullaby.AddEffectTrigger(lullaby_second);
            lullaby.item._ItemTypeIDs = ["Magic"];
            lullaby.item.AddItem("Locked_ImperfectLullaby.png", AchievementIDs.Chapter19, Test);

            ExtraLootOptionsEffect more_angel = ScriptableObject.CreateInstance<ExtraLootOptionsEffect>();
            more_angel._itemName = "Salt_Angel_TW";

            MultiPerformEffectItem angel = new MultiPerformEffectItem("Salt_Angel_TW", [Effects.GenerateEffect(more_angel, 1)]);
            angel.Name = "Angel";
            angel.Flavour = "\"My little friend.\"";
            angel.Description = "This party member is now considered an Angel.\nIncrease all damage and healing dealt by 2 for each Angel in combat.\nOn combat start, if this party member is the only party member in combat, produce another Angel.";
            angel.Icon = ResourceLoader.LoadSprite("Item_Angel.png");
            angel.EquippedModifiers = [];
            angel.TriggerOn = TriggerCalls.OnCombatStart;
            angel.DoesPopUpInfo = true;
            angel.Conditions = [ScriptableObject.CreateInstance<OnlyPartyMemberCondition>()];
            angel.DoesActionOnTriggerAttached = false;
            angel.ConsumeOnTrigger = TriggerCalls.Count;
            angel.ConsumeOnUse = false;
            angel.ConsumeConditions = [];
            angel.ShopPrice = 8;
            angel.IsShopItem = false;
            angel.StartsLocked = true;
            angel.OnUnlockUsesTHE = true;
            angel.UsesSpecialUnlockText = false;
            angel.SpecialUnlockID = UILocID.None;
            EffectTrigger angel_second = new EffectTrigger([], [TriggerCalls.OnWillApplyDamage, TriggerCalls.OnWillApplyHeal], [ScriptableObject.CreateInstance<AngelCondition>()], false);
            angel.AddEffectTrigger(angel_second);
            angel.item._ItemTypeIDs = ["Angel"];
            angel.item.AddItem("Locked_Angel.png", AchievementIDs.Chapter18, Test);

            PercentageEffectorCondition p4 = ScriptableObject.CreateInstance<PercentageEffectorCondition>();
            p4.triggerPercentage = 10;

            MultiPerformEffectItem karma = new MultiPerformEffectItem("Salt_KarmicOffloading_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<HealEffect>(), 3, Slots.Self)]);
            karma.Name = "Karmic Offloading";
            karma.Flavour = "\"You've got all the time in the world.\"";
            karma.Description = "On taking any damage, heal 3 health if this party member is not dead.\nAt the end of each turn, 90% chance to do nothing.";
            karma.Icon = ResourceLoader.LoadSprite("Item_KarmicOffloading.png");
            karma.EquippedModifiers = [];
            karma.TriggerOn = TriggerCalls.OnDamaged;
            karma.DoesPopUpInfo = true;
            karma.Conditions = Passives.Slippery.conditions;
            karma.DoesActionOnTriggerAttached = false;
            karma.ConsumeOnTrigger = TriggerCalls.Count;
            karma.ConsumeOnUse = false;
            karma.ConsumeConditions = [];
            karma.ShopPrice = 3;
            karma.IsShopItem = false;
            karma.StartsLocked = true;
            karma.OnUnlockUsesTHE = false;
            karma.UsesSpecialUnlockText = false;
            karma.SpecialUnlockID = UILocID.None;
            EffectTrigger karma_second = new EffectTrigger([Effects.GenerateEffect(Hauntling.Spawn, 5, Slots.Self)], [TriggerCalls.OnTurnFinished], [p4]);
            karma.AddEffectTrigger(karma_second);
            karma.item._ItemTypeIDs = ["Magic"];
            karma.item.AddItem("Locked_KarmicOffloading.png", AchievementIDs.Chapter20, Test);

            PerformEffect_Item glue = new PerformEffect_Item("Salt_GlueEye_SW", []);
            glue.Name = "Glue Eye";
            glue.Flavour = "\"Stares at you grossly.\"";
            glue.Description = "Apply 1 Divine Protection to targets before damaging them.";
            glue.Icon = ResourceLoader.LoadSprite("Item_GlueEye.png");
            glue.EquippedModifiers = [];
            glue.TriggerOn = TriggerCalls.OnWillApplyDamage;
            glue.DoesPopUpInfo = false;
            glue.Conditions = [ScriptableObject.CreateInstance<GlueEyeCondition>()];
            glue.DoesActionOnTriggerAttached = false;
            glue.ConsumeOnTrigger = TriggerCalls.Count;
            glue.ConsumeOnUse = false;
            glue.ConsumeConditions = [];
            glue.ShopPrice = 2;
            glue.IsShopItem = true;
            glue.StartsLocked = true;
            glue.OnUnlockUsesTHE = true;
            glue.UsesSpecialUnlockText = false;
            glue.SpecialUnlockID = UILocID.None;
            glue.item.AddItem("Locked_GlueEye.png", AchievementIDs.Chapter21, Test);

            Basic_Item strepnut = new Basic_Item("Salt_Strepnut_SW");
            strepnut.Name = "Strepnut";
            strepnut.Flavour = "\"Madness, madness\"";
            strepnut.Description = "On dealing odd damage, 50% chance to deal it again.\nOn taking odd damage, 50% chance to take it again.";
            strepnut.Icon = ResourceLoader.LoadSprite("Item_Strepnut.png");
            strepnut.EquippedModifiers = [];
            strepnut.TriggerOn = TriggerCalls.Count;
            strepnut.DoesPopUpInfo = false;
            strepnut.Conditions = [];
            strepnut.DoesActionOnTriggerAttached = false;
            strepnut.ConsumeOnTrigger = TriggerCalls.Count;
            strepnut.ConsumeOnUse = false;
            strepnut.ConsumeConditions = [];
            strepnut.ShopPrice = 6;
            strepnut.IsShopItem = true;
            strepnut.StartsLocked = true;
            strepnut.OnUnlockUsesTHE = true;
            strepnut.UsesSpecialUnlockText = false;
            strepnut.SpecialUnlockID = UILocID.None;
            strepnut.item.AddItem("Locked_Strepnut.png", AchievementIDs.Chapter17, Test);

            Basic_Item mask = new Basic_Item("Salt_SmilerMask_TW");
            mask.Name = "Smiler Mask";
            mask.Flavour = "\"Grins!\"";
            mask.Description = "Ruptured deals double damage.";
            mask.Icon = ResourceLoader.LoadSprite("Item_SmilerMask.png");
            mask.EquippedModifiers = [];
            mask.TriggerOn = TriggerCalls.Count;
            mask.DoesPopUpInfo = false;
            mask.Conditions = [];
            mask.DoesActionOnTriggerAttached = false;
            mask.ConsumeOnTrigger = TriggerCalls.Count;
            mask.ConsumeOnUse = false;
            mask.ConsumeConditions = [];
            mask.ShopPrice = 4;
            mask.IsShopItem = false;
            mask.StartsLocked = true;
            mask.OnUnlockUsesTHE = true;
            mask.UsesSpecialUnlockText = false;
            mask.SpecialUnlockID = UILocID.None;
            mask.item._ItemTypeIDs = ["Face"];
            mask.item.AddItem("Locked_SmilerMask.png", AchievementIDs.Smilers, Test);

            PerformEffect_Item grudge = new PerformEffect_Item("Salt_Grudge_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyPaleEffect>(), 5, Targeting.Unit_AllOpponents)]);
            grudge.Name = "Grudge";
            grudge.Flavour = "\"The little crow answered with its deepest, darkest desire.\"";
            grudge.Description = "On taking any damage, inflict 5 Pale on all enemies.";
            grudge.Icon = ResourceLoader.LoadSprite("Item_Grudge.png");
            grudge.EquippedModifiers = [];
            grudge.TriggerOn = TriggerCalls.OnDamaged;
            grudge.DoesPopUpInfo = true;
            grudge.Conditions = [];
            grudge.DoesActionOnTriggerAttached = false;
            grudge.ConsumeOnTrigger = TriggerCalls.Count;
            grudge.ConsumeOnUse = false;
            grudge.ConsumeConditions = [];
            grudge.ShopPrice = 6;
            grudge.IsShopItem = false;
            grudge.StartsLocked = true;
            grudge.OnUnlockUsesTHE = true;
            grudge.UsesSpecialUnlockText = false;
            grudge.SpecialUnlockID = UILocID.None;
            grudge.item.AddItem("Locked_Grudge.png", AchievementIDs.Crow, Test);

            PerformEffect_Item bodybag = new PerformEffect_Item("Salt_Bodybag_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyWaterSlotEffect>(), 2, Slots.Front)]);
            bodybag.Name = "Bodybag";
            bodybag.Flavour = "\"Zip it up and dump it.\"";
            bodybag.Description = "On moving, inflict 2 Deep Water on the Opposing position.";
            bodybag.Icon = ResourceLoader.LoadSprite("Item_Bodybag.png");
            bodybag.EquippedModifiers = [];
            bodybag.TriggerOn = TriggerCalls.OnMoved;
            bodybag.DoesPopUpInfo = true;
            bodybag.Conditions = [];
            bodybag.DoesActionOnTriggerAttached = false;
            bodybag.ConsumeOnTrigger = TriggerCalls.Count;
            bodybag.ConsumeOnUse = false;
            bodybag.ConsumeConditions = [];
            bodybag.ShopPrice = 4;
            bodybag.IsShopItem = false;
            bodybag.StartsLocked = true;
            bodybag.OnUnlockUsesTHE = true;
            bodybag.UsesSpecialUnlockText = false;
            bodybag.SpecialUnlockID = UILocID.None;
            bodybag.item.AddItem("Locked_Bodybag.png", AchievementIDs.Black, Test);

            PerformEffect_Item rgb = new PerformEffect_Item("Salt_RGB_TW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<RandomizeLightsEffects>(), 1, MultiTargetting.Create(Targetting.Everything(true), Targetting.Everything(false)))]);
            rgb.Name = "RGB";
            rgb.Flavour = "\"Looks like crap\"";
            rgb.Description = "At the start of each turn, Adjust all Lights.";
            rgb.Icon = ResourceLoader.LoadSprite("Item_RGB.png");
            rgb.EquippedModifiers = [];
            rgb.TriggerOn = TriggerCalls.OnTurnStart;
            rgb.DoesPopUpInfo = true;
            rgb.Conditions = [];
            rgb.DoesActionOnTriggerAttached = false;
            rgb.ConsumeOnTrigger = TriggerCalls.Count;
            rgb.ConsumeOnUse = false;
            rgb.ConsumeConditions = [];
            rgb.ShopPrice = 4;
            rgb.IsShopItem = false;
            rgb.StartsLocked = true;
            rgb.OnUnlockUsesTHE = false;
            rgb.UsesSpecialUnlockText = false;
            rgb.SpecialUnlockID = UILocID.None;
            rgb.item.AddItem("Locked_RGB.png", AchievementIDs.Tv, Test);

            PerformEffect_Item glass = new PerformEffect_Item("Salt_GlassDiamond_TW", [
                Effects.GenerateEffect(BasicEffects.Empty, 1, Slots.Self, Effects.ChanceCondition(50)),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<DamageFromNoOneEffect>(), 2, Slots.Self, BasicEffects.DidThat(true)),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<HealEffect>(), 5, Slots.Self, BasicEffects.DidThat(false, 2))
                ]);
            glass.Name = "Glass Diamond";
            glass.Flavour = "\"Takes a lot of effort to keep it clean.\"";
            glass.Description = "On taking any damage, either heal 5 health or take 2 damage, from no one.";
            glass.Icon = ResourceLoader.LoadSprite("Item_GlassDiamond.png");
            glass.EquippedModifiers = [];
            glass.TriggerOn = TriggerCalls.OnDamaged;
            glass.DoesPopUpInfo = true;
            glass.Conditions = [];
            glass.DoesActionOnTriggerAttached = false;
            glass.ConsumeOnTrigger = TriggerCalls.Count;
            glass.ConsumeOnUse = false;
            glass.ConsumeConditions = [];
            glass.ShopPrice = 3;
            glass.IsShopItem = false;
            glass.StartsLocked = true;
            glass.OnUnlockUsesTHE = true;
            glass.UsesSpecialUnlockText = false;
            glass.SpecialUnlockID = UILocID.None;
            glass.item.AddItem("Locked_GlassDiamond.png", AchievementIDs.Invention, Test);

            CurrencyMultiplierChange_Wearable_SMS doubleMoney = ScriptableObject.CreateInstance<CurrencyMultiplierChange_Wearable_SMS>();
            doubleMoney._currencyMultiplier = 2;

            PerformEffect_Item dream = new PerformEffect_Item("Salt_RedDream_TW", [
                Effects.GenerateEffect(BasicEffects.GetVisuals("Salt/Curtains", false, Slots.Self)),
                Effects.GenerateEffect(UIActionEffect.Create(Effects.GenerateEffect(ScriptableObject.CreateInstance<MoveToGardenEffect>(), 1, Slots.Self).SelfArray()), 1, Targeting.Slot_SelfSlot),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<BoxAllEnemiesEffect>()),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<SpawnGardenEnemyBundleEffect>()),
                Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyFocusedEffect>(), 1, Targeting.Unit_AllAllies)
                ]);
            dream.Name = "Red Dream";
            dream.Flavour = "\"Exit into heaven.\"";
            dream.Description = "Double the rewards from combat.\nOnce per combat, on taking direct damage enter a dream.";
            dream.Icon = ResourceLoader.LoadSprite("Item_RedDream.png");
            dream.EquippedModifiers = [doubleMoney];
            dream.TriggerOn = TriggerCalls.OnDirectDamaged;
            dream.DoesPopUpInfo = true;
            dream.Conditions = [TriggerOnceEffectorCondition.Create("RedDream_TW")];
            dream.DoesActionOnTriggerAttached = false;
            dream.ConsumeOnTrigger = TriggerCalls.Count;
            dream.ConsumeOnUse = false;
            dream.ConsumeConditions = [];
            dream.ShopPrice = 10;
            dream.IsShopItem = false;
            dream.StartsLocked = true;
            dream.OnUnlockUsesTHE = true;
            dream.UsesSpecialUnlockText = false;
            dream.SpecialUnlockID = UILocID.None;
            dream.item._ItemTypeIDs = ["Magic", "Fabric"];
            dream.item.AddItem("Locked_RedDream.png", AchievementIDs.Blue, Test);

            MultiPerformEffectItem knife = new MultiPerformEffectItem("Salt_Knife_SW", [Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyTerrorEffect>(), 1, Targetting.Random(false))]);
            knife.Name = "Knife That Tells You To Do Things";
            knife.Flavour = "\"You should cut your face off.\"";
            knife.Description = "At the start of each turn, apply Terror to a random enemy.\nDeal 40% more damage to enemies with Terror.\nOn using an ability, gain Terror.";
            knife.Icon = ResourceLoader.LoadSprite("Item_Knife.png");
            knife.EquippedModifiers = [];
            knife.TriggerOn = TriggerCalls.OnTurnStart;
            knife.DoesPopUpInfo = true;
            knife.Conditions = [];
            knife.DoesActionOnTriggerAttached = false;
            knife.ConsumeOnTrigger = TriggerCalls.Count;
            knife.ConsumeOnUse = false;
            knife.ConsumeConditions = [];
            knife.ShopPrice = 6;
            knife.IsShopItem = true;
            knife.StartsLocked = true;
            knife.OnUnlockUsesTHE = true;
            knife.UsesSpecialUnlockText = false;
            knife.SpecialUnlockID = UILocID.None;
            knife.item._ItemTypeIDs = ["Knife"];
            EffectTrigger knife_second = new EffectTrigger([], [TriggerCalls.OnWillApplyDamage], [DamageToStatusCondition.Create(1.4f, Terror.StatusID)], false);
            EffectTrigger knife_third = new EffectTrigger([Effects.GenerateEffect(ScriptableObject.CreateInstance<ApplyTerrorEffect>(), 1, Slots.Self)], [TriggerCalls.OnAbilityUsed], []);
            knife.AddEffectTrigger(knife_second);
            knife.AddEffectTrigger(knife_third);
            knife.item.AddItem("Locked_Knife.png", AchievementIDs.ChapterBoss, Test);






        }
    }
}
